### ISSUE TITLE
Update `runClient` with additional server args

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1006]
Currently, the `util/test/runClient` script only takes `-nl` as an argument, but it would be great to be able to specify things like `--partition` and `--walltime`. It should just be able to pass those arguments to `arkouda_server`.

**Comment by ronawho** [comment]
👍  I keep taking the lazy way out and modifying the scripts when I want to make changes like this, but I agree it would be nice to have a way to just pass arguments to the server. Both for `runClient` and `run_benchmarks.py` (huh.. wonder why I did camelCase for one and underscore for the other..)
