### ISSUE TITLE
Add `uint64` dtype

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1011]
We've been toying with the idea of an unsigned integer type for a while, but I think we've finally reached a critical mass of use cases where it would be helpful. Most of the code can just be copied from what is defined for `DType.Int64`, unless we want to use this as an opportunity to consolidate code with dispatch or generic helper functions.

For the CI, we can `uint64` to the operator test and measure correctness against numpy.

Also, we can't forget I/O and casting.

**Comment by mhmerrill** [comment]
@Bears-R-Us/arkouda-core-dev we should have a discussion of this before we run off and do it. I have been puzzling over the operator code organization. there are a few different ways to organize the code and the current way keeps all of the operators for a specific type combination together. Remember we don't implement all operators for all type combinations.

**Comment by mhmerrill** [comment]
There will be additions to the client and the server...
I think the steps look something like this:
- [ ] add new dtype `uint64` to the server with conversions to chapel `uint` type
- [ ] add new dtype `uint64` to the client aliases and such
- [ ] add binOps for `uint64`
- [ ] add indexing for `uint64`
- [ ] add sorting for `uint64` : `argsort`, `sort`, `coargsort`
- [ ] add setops and stuff for `uint64` : `in1d`, `unique`, `union1d`,  etc...
- [ ] more stuff

**Comment by bmcdonald3** [comment]
With some help from Elliot, Pierce, and Mike, we've gotten https://github.com/Bears-R-Us/arkouda/pull/1070 passing CI tests and ready for review. 

This PR includes:
 * argsort, sort, coargsort (Thank you Elliot)
 * indexing for uint with [int] and [pdarray]
 * casting to/from uint64
 * Parquet uint64 reading/writing
 * Random uint array generation
 * '+' binary operation for uint+uint pdarrays
 
This PR does not implement:
 - most uint binary operations
 - HDF5 uint support 
 - setops for uints

**Comment by glitch** [comment]
For incremental follow up, here's the brief synopsis of my PR comments and spots I noticed we need to still address

- [ ] `sorting.py` - `sort` and `argsort` if the pdarray is size 0 we return `zeros(0, dtype=int64)` and there is also a check on the pdarray dtype which follows the size test.  We may want to flip the conditions and check the incoming dtype first.  Then we can make the zeros call do `zeros(0, dtype=pda.dtype)`.
- [ ] Duplicate logic in `ArrowFunctions.cpp` where ARROWINT64 & ARROWUINT64 are (lines 131-149).  If the code is the same the if condition could include both types.
- [ ] `IndexingMsg` the `ivUInt64Helper` and `ivInt64Helper` are _almost_ the same.  We could extra the common logic into a more generic helper function which the other two call into passing in their SymEntries as args.
- [ ] `RandMsg` `aMin` and `aMax` argument validation and casting to `uint` might need to be done / make sense here.
- [ ] `ArrayMsg` I don't think we can pass over a uint64 array at the moment, we'll need to add the functionality

**Comment by reuster986** [comment]
Great work, everyone! @mhmerrill asked me to compile a list of binary operator and type combinations that are needed. While eventually it would be convenient to have uint64 supported everywhere int64 is supported, these are the are the operators we would use in key workflows today:

* `uint64 <op> uint64`: +, -, ==, >=, >, <=, <, !=, >>, <<, >>>, <<<, &, |, ^
* `uint64 <op> int64`: +, -, >>, <<, >>>, <<<
* unary `uint64`: `popcount`, `clz`, `ctz`

Also, HDF5 I/O is going to be super important, in addition to the Parquet and socket-based I/O. I might be able to work on that tomorrow.

**Comment by glitch** [comment]
@reuster986 I'm happy to report that HDF5 reading/writing is ready for review here -> https://github.com/Bears-R-Us/arkouda/pull/1073

**Comment by reuster986** [comment]
@glitch excellent!!

**Comment by mhmerrill** [comment]
> 

I think we should also add `parity` and `cumsum`, which I have documented in PR #1080

**Comment by reuster986** [comment]
I'm going to close this because the bulk of the functionality is done and covered in CI. We can make separate issues for any gaps or bugs that come up in user testing.

Thank you all for your great work!
