### ISSUE TITLE
These assignments assign to a temp variable first and then immediately to the actual variable.  Why not just assign it directly?

### ISSUE THREAD

**Issue by zhihuidu** [Bears-R-Us/arkouda#1018]
These assignments assign to a temp variable first and then immediately to the actual variable.  Why not just assign it directly?

_Originally posted by @glitch in https://github.com/Bears-R-Us/arkouda/pull/983#discussion_r758354481_

**Comment by zhihuidu** [comment]
I remember I try to directly assign it to the actual variable. However, there are some compiling errors I cannot handle.

**Comment by ronawho** [comment]
The link does not take me to a comment. What is this in reference to?

**Comment by zhihuidu** [comment]
> The link does not take me to a comment. What is this in reference to?

Sorry, the original code has been updated and we do not need such an assignment.
However, I still do not understand why I cannot directly write an assignment like this
src=toSymEntry(gs, int)

The original assignments is like the following code
      srcName = srcNameA;
      // The try! is needed here because init cannot throw
      var gs = try! st.lookup(srcName);
      var tmpsrc = toSymEntry(gs, int): unmanaged SymEntry(int);
      src=tmpsrc;
