### ISSUE TITLE
Remove non-regex substring search?

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1031]
With the improvements from chapel 1.25.1, the regex substring search methods are outperforming the non-regex search methods even for string literals. We should probably do more extensive testing to make sure this is true for the situations we care about, maybe @reuster986  can help with that

If the regex substring search is more performant, I think we can eliminate the special purpose literal substring search code in `substringSearch` by doing something like this

```python
def contains(substr, regex = False):
  if not regex:
    substr = re.escape(substr)
  # now just do regex contains
```

I feel like this would be worthwhile to make the code simpler especially if it's also faster. I'll try to put a draft PR to give a better idea of what this will look like

**Comment by pierce314159** [comment]
I put up PR #1032 to show what this would look like. It's worth noting this change would require users build chapel with regex support to use substring search functions, regardless of if the regex flag is set to true or false

How do others feel about this?

**Comment by ronawho** [comment]
Just capturing some performance results for substring_search on 16-node-cd-hdr today to give some concrete perf numbers:

```
>>> arkouda substring search
numLocales = 16, N = 100,000,000
non-regex with literal substring Average time = 0.2461 sec
regex with literal substring Average time = 0.0772 sec
regex with pattern Average time = 0.0422 sec
non-regex with literal substring Average rate = 7.1897 GiB/sec
regex with literal substring Average rate = 22.9269 GiB/sec
regex with pattern Average rate = 41.9599 GiB/sec
```

So like you said much better perf for the regex versions.

Something important that's worth noting is that the benchmark we have has equal sized strings, which results in perfect data locality. It's possible that performance is different for real data where strings are variable sizes and we actually have to GET some strings to compute the regex (and like you said we probably need data from Bill 
 to get a sense for that.)

**Comment by reuster986** [comment]
> I put up PR #1032 to show what this would look like. It's worth noting this change would require users build chapel with regex support to use substring search functions, regardless of if the regex flag is set to true or false
> 
> How do others feel about this?

I think it is fine to require users to build with regex support, especially given the performance benefits.
