### ISSUE TITLE
Update Contributing.md with release & ticketing process

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#1040]
Update the CONTRIBUTING.md document with
- ticketing process and general rules of thumb for linking tickets with PRs / change-sets
- Release & versioning process (either make a wiki and link it or outline the process in te doc)

**Comment by glitch** [comment]
https://github.com/Bears-R-Us/arkouda/wiki/Release-Process  Wiki entry has been created on how to cut a new release and generate release-notes.  This is also linked under the Arkouda wiki `Development & Testing pages` section.

**Comment by pierce314159** [comment]
Closing because this issue has been captured by #1301
