### ISSUE TITLE
Allow modules from outside the Arkouda src directory to be modularly built

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#1046]
Today, the modular Arkouda build only works for modules in the Arkouda `src/` directory. Adding support for including modules from other directories is desirable.

The main challenges with this approach is adding client-side support for the new functions. One approach would be to have a generic function that could call any server function, but then users would be limited in return types, so something like this:
```
def server_function(cmd, args):
    repMsg = generic_msg(cmd=cmd, args=args)
    return repMsg
```

Another approach is expecting users to create their own client-side functions and require them to be imported into the Arkouda instance:
```
import arkouda as ak
from arkouda.client import generic_msg

def test_command():
    repMsg = generic_msg(cmd='test-command')
    return repMsg

ak.__dict__["test_command"] = test_command
```
This approach seems the most reasonable, since it allows the user full control over the arguments, any preprocessing of those arguments, and how the return type is handled, but it is definitely more work than the `server_function()` approach.

I have been considering additional solutions to somehow automate this process, but I just don't see how that could be done since there are any number of things that a user would want to do on the client side to handle their server call.

**Comment by glitch** [comment]
When trying to use this locally (setting `ARKOUDA_SERVER_USER_MODULES=/home/glitch/projects/arkouda-contrib` etc.) I get an error when issuing a `make`.  The full command and error look like this:
```
chpl --print-passes    --ccflags="-DH5_USE_110_API" --ccflags="-O1" -smemTrack=true -smemThreshold=1048576 --no-cache-remote --interleave-memory -I/home/glitch/miniconda3/envs/ak-base/include -L/home/glitch/miniconda3/envs/ak-base/lib --ldflags="-Wl,-rpath,/home/glitch/miniconda3/envs/ak-base/lib" -lhdf5 -lhdf5_hl -lzmq -sarkoudaVersion="\"pre-release-v2022.01.20+32.g28742e5a.dirty\"" /home/glitch/projects/arkouda//src/arkouda_server.chpl -M /home/glitch/projects/arkouda//src/compat/ge-125 /home/glitch/projects/arkouda-contrib -o arkouda_server
error: file '/home/glitch/projects/arkouda-contrib' does not have a recognized suffix
make: *** [Makefile:270: arkouda_server] Error 1
```

In the generated chpl compiler command the extra module dir ends up as an extra un-prefixed arg.  I _think_ we need to either add an additional `-M` to it (which works manually) or extend the previous module string and max it a CSV delimited value.

I think the issue is where `ARKOUDA_SERVER_USER_MODULES`

**Comment by bmcdonald3** [comment]
So, when you specify a module to include with `ARKOUDA_SERVER_USER_MODULES`, you need to specify the entire path to the module to be included, not just the directory that it is in. So, you would do `ARKOUDA_SERVER_USER_MODULES=/home/glitch/projects/arkouda-contrib/MyModule.chpl`. The module is added to the command line directly and that is how it is found by the `chpl` command. We had a version that `-M`ed the search directory instead, but decided that was not ideal because the likelihood of having a module name conflict with a module in that outside directory.

If you wanted to do more than one module, you can just set it to a string of modules separated by a space, e.g., `ARKOUDA_SERVER_USER_MODULES="/path/to/module1.chpl /path/to/module2.chpl"`.

**Comment by glitch** [comment]
Doh, this was poor reading skills be me.  You have an example in `Modular.md` which I completely skipped over.  Thanks!
