### ISSUE TITLE
Create a generic `ak.attach()`

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1086]
Currently, when attaching to registered arrays, the user must know ahead of time whether the array is a pdarray or Strings and call either `ak.attach_pdarray()` or `ak.Strings.attach()` accordingly. This makes programmatic attachment to multiple arrays difficult. For example, we'd like to be able to create a DataFrame with both string and numeric columns, register the columns with a common naming scheme, and then later attach to all of them to recover the DataFrame. See the `register_all` and `attach_all` functions in `akutil/util.py` for usage.

However, this would require a generic `ak.attach()` function that runs the "attach" server command and parses the output to determine whether it is a pdarray or Strings and returns the appropriate type. I believe this can be done with:

```python
def attach(name):
    repMsg = generic_msg(cmd="attach", args=name)
    dtype = repMsg.split()[2]
    if dtype == "str":
        return Strings.from_return_msg(repMsg)
    else:
        return create_pdarray(repMsg)
```

**Comment by Ethan-DeBandi99** [comment]
`akutil/util.py` has been moved to `arkouda/util.py`, so this function could be added to that file.
