### ISSUE TITLE
Should substring search benchmark scale by numLocales?

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1109]
Most benchmarks treat the `--size` argument as a per-locale size and multiply by `numLocales` when generating the test data. However, `benchmarks/substring_search.py` does not scale by `numLocales`:

https://github.com/Bears-R-Us/arkouda/blob/d0fda3917835e46f3a6abe080bd8a1cc3fa377d2/benchmarks/substring_search.py#L8-L14

Was this intentional, or should we update it?

**Comment by ronawho** [comment]
`benchmarks/flatten.py` as well

**Comment by pierce314159** [comment]
Yeah this was an oversight. This (along with `flatten.py`) were my first benchmarks so I was looking at the others when implementing and must have missed this. I think it should be updated to scale with the number of locales

**Comment by pierce314159** [comment]
It also looks like `array_transfer` is missing this scaling (if my memory serves, I think this the benchmark I was referencing)

https://github.com/Bears-R-Us/arkouda/blob/d9d2ce7e3ba4aea80b011c5712bc711d6659c8f2/benchmarks/array_transfer.py#L10-L16
