### ISSUE TITLE
Move `SegArray` and `Dataframe` from `akutil` into arkouda

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1118]
Part of #997

To incorporate `akutil`'s dataframe into arkouda:
- Move `akutil/row.py` into arkouda since dataframe depends on it
- Move `akutil/segarray.py` into arkouda since dataframe depends on it 
  - Note: this will be converted into a server-side object similar to `SegString` in a future issue
- Move `akutil/dataframe.py` into arkouda
  - This will be done in a limited capacity until the remaining dependencies from akutil are moved to arkouda. 
- Add tests verifying our dataframe functionality is consistent with pandas dataframes
- Add documentation for our dataframe's API

My thought process is moving over the python code first and developing tests based on it will help ensure no functionality is lost/changed when we port the logic over to chapel

**Comment by Ethan-DeBandi99** [comment]
Attach/Register functionality for GroupBy defined in akutil/segarray.py is being removed until #1122 is worked and Attach/Register is natively supported by the GroupBy class.

**Comment by Ethan-DeBandi99** [comment]
dataframe will be moved with limited functionality. Once other tickets are worked, additional functionality and testing will be added to arkouda/dataframe.py so that it will match akutil/dataframe.py
