### ISSUE TITLE
Move dtypes and util.py into Arkouda

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1126]
Part of #997 

- Integrate `akutil/dtypes.py` into arkouda. 
- Integrate `akutil/util.py` into arkouda. This relies on `akutil/dtypes.py` already being configured.
  - This will require `DataFrame` as well. A limited functionality will be available, allowing for the reference to not cause issues.
- Add `append()` and `concat()` functions to `arkouda/dataframe.py` from `akutil/dataframe.py`
- Add tests for the new dtypes to `tests/dtype_tests.py`
- Add tests for `append()` and `concat()` functionality 
- Update documentation to reflect new dataframe functionality.

**Comment by Ethan-DeBandi99** [comment]
Based on @reuster986 comment in #997, `akutil/dtypes.py` are going to remain as client-side classes for the time being. This ticket will move them into `arkouda/client_dtypes.py`. This will differentiate them from the server-side data types that stored in `arkouda/dtypes.py`. Organizationally, this seems to make the most sense to me, but I am open to suggestions. This is also simple enough to move if needed.

**Comment by Ethan-DeBandi99** [comment]
`arkouda/client_dtypes.py` and `arkouda/util.py` are ready. `arkouda/util.py` requires DataFrame reference to be added back once `arkouda/dataframe.py` is merged. `append()` and `concat()` will need to be added to `arkouda/dataframe.py` once it is merged as well.

**Comment by Ethan-DeBandi99** [comment]
Unit tests for `arkouda/client_dtypes.py` has been added.

**Comment by mhmerrill** [comment]
is this related or duplicative with respect to issue #1077 ??

**Comment by Ethan-DeBandi99** [comment]
@mhmerrill No this is in regards to moving features from `akutil` into arkouda proper. All dtypes that are being moved over are being kept client side for this for now per @reuster986 suggestion.
