### ISSUE TITLE
Support logical indexing on uint64

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1133]
Currently, uint64 arrays support indexing with a pdarray of (u)int64, but not a pdarray of bool (logical indexing). This pattern is quite widely used and should be supported (and probably tested in CI).

Reproducer:

```python
# uint64 array
>>> u = ak.cast(ak.arange(100), ak.uint64)
# Bool array alternating True and False
>>> i = (ak.arange(100) % 2) == 0
# Indexing uint64[bool] 
>>> u[i]
# Raises "Error: pdarrayIndexMsg: (uint64, bool) not implemented"
```

**Comment by reuster986** [comment]
While here, we should also add:
- support for indexing with uint64 pdarrays, i.e. `int64[uint64]` and `uint64[uint64]`
- an `indexing_test.py` in the CI, since it doesn't look like indexing is explicitly tested anywhere.

**Comment by pierce314159** [comment]
updated the comment because I almost mistakenly closed this issue before remembering the `indexing_test` is still TODO

**Comment by mhmerrill** [comment]
> updated the comment because I almost mistakenly closed this issue before remembering the `indexing_test` is still TODO

@pierce314159 FYI, some of these indexing modes are tested in `check.py`.
