### ISSUE TITLE
fix `make test-chapel` to not only compile arkouda-chapel unit tests but also run them

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1161]
fix `make test-chapel` to not only compile arkouda-chapel unit tests but also run them

**Comment by pierce314159** [comment]
I'm looking into this a bit more and remembered that @glitch did some work related to this which is on the arkouda wiki
https://github.com/Bears-R-Us/arkouda/wiki/Unit-Testing#how-to-run-chapel-tests

The chapel unit tests can be compiled, ran, and tested against the appropriate `*.good` files using the chapel utility `start_test`
```bash
start_test test
```
or a python wrapper of `start_test` that glitch wrote to run `start_test` in parallel
```bash
python3 util/test/parallel_start_test.py --dir=test --threads=1
```

I can work on updating the `Makefile` targets to run `parallel_start_test`
