### ISSUE TITLE
`ak.DataFrame` Add Missing GroupBy Functionality

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1166]
`pandas.DataFrame` supports more robust groupby functionality.

- Add `.first()` function to access the first group and display it
- Add `.groupby()` support for access and displaying a group by the value

**Comment by jaketrookman** [comment]
@Ethan-DeBandi99 
Just wanted to check in about the `.groupby()` feature. It seems that it may have already been implemented with the desired functionality. Let me know if you were looking for something esle.
https://github.com/Bears-R-Us/arkouda/blob/c32687e496e414f69ffd653371479f0092e4841b/arkouda/dataframe.py#L1314-L1346
and its lowercase version alias
https://github.com/Bears-R-Us/arkouda/blob/c32687e496e414f69ffd653371479f0092e4841b/arkouda/dataframe.py#L1749-L1762

**Comment by jaketrookman** [comment]
I have also done the `.first` implementation using a special case of the `.head` function.

**Comment by Ethan-DeBandi99** [comment]
@jaketrookman - I believe this issue is outdated. I know there were a few things Pandas has that Arkouda does not, but after discussions with users, I am not sure those components are necessary for Arkouda. I would proceed with your plan to have #2003 close this issue.
