### ISSUE TITLE
documentation version number shows up as 2020.07.07

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1176]
figure out how to either remove the version number or update it when generating the docs.
I think this is the offending line:
https://github.com/Bears-R-Us/arkouda/blob/20f0315bf8f3723f4bc9a8803f1f89cc01d98ae8/pydoc/conf.py#L25

**Comment by Ethan-DeBandi99** [comment]
@mhmerrill - The `2020.07.07` is hard-coded in the docs (assuming you mean the quickstart guide, here - https://bears-r-us.github.io/arkouda/setup/quickstart.html?highlight=2020#launch-arkouda-server). I can update this to be hard-coded to the current output and put in a generic example version for now. The `release` var found in `arkouda/pydoc/conf.py` is not used and could probably be removed.

Doing some quick looking I am not sure that we can get this to update on generation. If that is the preferred method I can dig a bit deeper to look for a solution.

My suggested replacement for the outdate blocks here:

`
**************************************************************************************************************
**************************************************************************************************************
*                                                                                                                                                                                        *
*                          server listening on tcp://<your_machine>.local:5555                                                                     *
*                             arkouda server version = v####.##.##+<server_version_number>                                          *
*                                         memory limit = 15461882265                                                                                            *
*                                          bytes of memory used = 0                                                                                                *
*                                                                                                                                                                                       *
**************************************************************************************************************
**************************************************************************************************************
`
Please let me know if this is an acceptable solution and I will get it updated. A
