### ISSUE TITLE
Bad arguments to C_HDF5.H5Literate()

### ISSUE THREAD

**Issue by bradcray** [Bears-R-Us/arkouda#1189]
The following calls to C_HDF5.H5Literate() have the wrong argument types for argument 3:

https://github.com/Bears-R-Us/arkouda/blob/master/src/HDF5Msg.chpl#L182-L187

Specifically, the third argument should be one of the following values:

```chapel
// H5_iter_order_t enum                                                     
    extern type H5_iter_order_t = c_int;
    extern const H5_ITER_UNKNOWN :H5_iter_order_t;
    extern const H5_ITER_INC :H5_iter_order_t;
    extern const H5_ITER_DEC :H5_iter_order_t;
    extern const H5_ITER_NATIVE :H5_iter_order_t;
    extern const H5_ITER_N :H5_iter_order_t;
```

where today, it is:

```c
C_HDF5.H5Literate(fid, C_HDF5.H5_INDEX_NAME, C_HDF5.H5_INDEX_NAME, idx_p, c_ptrTo(_get_item_count), c_ptrTo(nfields));
```

Chapel doesn't catch this error because of the way that these external C enums are represented as Chapel code; but turning on a bunch of C warnings in the generated C code will catch it.  I believe what's happening in practice is that the enum value whose integral value happens to match that of `C_HDF5.H5_INDEX_NAME` is being sent in instead and working out well enough that nobody has noticed.

I'm not familiar enough with these calls or their use in Arkouda to know what value should be getting used here instead.

**Comment by glitch** [comment]
As long as this isn't urgent, I think I can get to it this weekend. The fix looks to be relatively simple; we just need to decide on the replacement which I think would probably be `H5_ITER_NATIVE` or unknown upon first inspection.

**Comment by bradcray** [comment]
It's not urgent as far as I can tell, given that we've lived with it for this long.  I just stumbled across it and wanted to point it out in the vein of "if you see something, say something".
