### ISSUE TITLE
Set Documentation Version with Versioneer

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1199]
Previously, Arkouda documentation was being generated with a hardcoded version number. This was updated in issue #1176. The fix at that point was to correct the `./arkouda_server` output to show the current format and use a format string to depict the version and to update `release='2020.07.07' ` to `release=''`The version that is actually printed is generated via `versioneer`.  After discussing with @mhmerrill, we want to look into having versioneer supply a version for the documentation as well.

- Set `release='<current_version>'` in `pydoc/conf.py`
- We will likely need a `pydoc/_version.py` like in `arkouda`.

**Comment by mhmerrill** [comment]
@glitch added the `versioneer` support originally he may be able to point us in the right direction here.
