### ISSUE TITLE
Parquet int96 timestamp data read incorrectly

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#1200]
The Parquet int96 timestamp type is now deprecated, but it can, of course, still be in a file and is in the file located at `resources/parquet-testing/alltypes_plain.parquet`.

Today, we determine whether or not we are going to read a file based off of it's `arrow::Type`, so the int96 version of the timestamp still shares the timestamp type and it is read and treated as an int64 timestamp, even though it will be read incorrectly.

There should be a way to identify the column as an int96 based off of the metadata, but there does not appear to be a simple way to identify it based off of a small amount of effort investigating the issue.

**Comment by pierce314159** [comment]
Since we're not planning on fixing this, i think we should go ahead and close it
