### ISSUE TITLE
Problem with gather on uint index

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#1210]
Can't gather on index of type uint64. We often gather on data which was recently converted from type int64 to uint64.
```python
a = ak.arange(10) * 2
b = ak.array([3,0,8])

#this works
a[b]

b = ak.cast(b,ak.uint64)

# this fails
a[b]
```

**Comment by 21771** [comment]
bold was unintentional. just meant to comment instead. :-)

**Comment by pierce314159** [comment]
> bold was unintentional. just meant to comment instead. :-)

No problem! I edited it. In the future if you wrap you code in github markdown, it'll display better
````
```python
# your code here
```
````
you can also use `bash` or `C` to get different syntax highlighting or no keyword for no highlighting

**Comment by reuster986** [comment]
Related to #1133 and subtasks in the comments.
