### ISSUE TITLE
uint assignment with a logical index

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#1239]
Getting `"RuntimeError: Error: setPdarrayIndexToPdarrayMsg: (uint64,bool,uint64) not implemented"`

example:
```python
a = ak.arange(4,dtype=ak.uint64)
d = a>=2
x = a[d] * 100
a[d] = x   # expecting values GTE 2 to be multiples of 100
```

**Comment by pierce314159** [comment]
I believe this issue is solved by https://github.com/Bears-R-Us/arkouda/pull/1217

I just ran the reproducer on the most up to date version of master to verify
```python
In [3]: a = ak.arange(4,dtype=ak.uint64)

In [4]: d = a>=2

In [5]: d
Out[5]: array([False False True True])

In [6]: x = a[d] * 100

In [7]: x
Out[7]: array([200 300])

In [8]: a[d] = x

In [9]: a
Out[9]: array([0 1 200 300])
```
So I **think** this will be resolved in the next release.

**Comment by pierce314159** [comment]
Just to be sure there isn't something else weird going on, im going back to our latest tag to verify it fails. I'll update this comment once I've done that.

If you don't mind, could let me know the output of 
```python
ak.get_config()['arkoudaVersion']
```
which would make me confident that the fix for this hasn't reached you yet

**Comment by pierce314159** [comment]
I'm gonna go ahead and close this, please reopen if your version string doesn't match `'v2022.03.15'` or if this still is not resolved after the next release

**Comment by 21771** [comment]
Not able to access version number right now, but confident you've
already fixed it. Thanks! Will let you know if version isn't issue.
