### ISSUE TITLE
`radixSortLSDCore()` Domain Question

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1253]
I discussed this with @pierce314159 some and we decided posting a question would be the best path forward to discuss.

While working on the SetOps for SegArrays, I ran into an indexing issue with `radixSortLSDCore()` when passing slices into `setops1d` functions. As an example, if you have the SegArrays below:
```python
SegArray([
[0,1,2]
[3,4,5]
])

SegArray([
[1,2]
[3,5]
])
```
When computing a setop on the 2nd segments, the domains are `[3..5]` and `[2..3]`. The way radixSort computes the position something should be placed in, it assumes the array being passed in has a domain `[0..N]`.

This can be resolved by modifying ln 241 of radixSortLSD.chpl
https://github.com/Bears-R-Us/arkouda/blob/d2b490465f0aa833482d219a7ac7a0043b050651/src/RadixSortLSD.chpl#L241

To account for the beginning of the domain
```chapel
aggregator.copy(a[aD.low+pos], tempi);
```
`aD` is the domain of `a` and `a` is the array passed into `radixSortLSDCore()`. This properly positions the value in the domain available and prevents any out of bounds errors. I ran a few tests in the benchmark `segarray_setops.py` and there seems to be a minimal performance impact. I solved the issue I was having by reindexing the slices, so this is not an immediate issue, but I wanted to post this to see if anyone had any reservations about making this change.

**Comment by mhmerrill** [comment]
@ronawho @bradcray @mppf @Bears-R-Us/arkouda-core-dev anybody have anything to add on this question?

**Comment by ronawho** [comment]
Not really. I think this is more a question of whether you want your radix sort to work with non-0 based arrays.

**Comment by Ethan-DeBandi99** [comment]
@mhmerrill is this something we want to update? If so, I will close this issue and add a new issue tracking the work.

**Comment by mhmerrill** [comment]
We will make this change in the sort refactor #1338 .
