### ISSUE TITLE
Python positive Integer list becomes Float if values both GTE and LT 2^63

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#1297]
Using ak.array(x), python list x containing positive integer values <2^64  is converted to pdarray of float if list contains integer values >= 2^63 and also contains integer values < 2^63. 

Not a big issue because using numpy uint64 arrays instead of python list eliminates the problem.

**Comment by pierce314159** [comment]
Thanks for reporting this! If I'm understanding correctly, I think you just need to specify the `dtype` as `ak.uint64`

In our latest tagged release (`v2022.04.15`)
```python
>>> ak.get_config()['arkoudaVersion']
'v2022.04.15'
>>> x = [2**63, 6, 2**63-1, 2**63+1]
>>> x
[9223372036854775808, 6, 9223372036854775807, 9223372036854775809]
>>> ak.array(x)
array([9.2233720368547758e+18 6 9.2233720368547758e+18 9.2233720368547758e+18])
>>> ak.array(x, dtype=ak.uint64)
array([9223372036854775808 6 9223372036854775808 9223372036854775808])
```

Note if you're using values with the high bit set (i.e. `2**64-1`). There will still be problems this is captured in issue #1311 and will be resolved by #1312

Let me know if I didn't completely address your issue!

**Comment by pierce314159** [comment]
it's also worth noting this behavior is the same as numpy
```python
>>> x = [2**63, 6, 2**63-1, 2**63+1]
>>> np.array(x)
>>> array([9.22337204e+18, 6.00000000e+00, 9.22337204e+18, 9.22337204e+18])

>>> np.array(x, dtype=np.uint64)
array([9223372036854775808,                   6, 9223372036854775807,
       9223372036854775809], dtype=uint64)
```

**Comment by 21771** [comment]
Agree that it is consistent with numpy, but believe it is undesirable behavior for arkouda if avoidable. If all values can be represented as uint64 (e.g. 64 bit hashes) that is a better default option than float. One can always convert to a float if desired, but there is no way to get back the bits of precision lost in the float conversion. 

Not a bug -- but I offer the issue as suggested default behavior. Thanks.

This is related to a data error which was difficult to track down. (even though it was most likely generated by np.array(x) rather than ak.array(x))

**Comment by pierce314159** [comment]
hmmm i'm curious what @reuster986 and @mhmerrill think. Normally `numpy` is our gold standard as far as desired behavior but maybe it makes sense to deviate in this case?

**Comment by reuster986** [comment]
I think I agree with @21771 that we should deviate from numpy in this specific case, in order to preserve the precision of uint64 values like hashes.

**Comment by mhmerrill** [comment]
I am ok with the deviation in this case hopefully there are no unintended consequences.

**Comment by pierce314159** [comment]
Just to show how pandas and numpy handle this issue. It appears like numpy defaults to float and pandas errors unless dtype is specified
```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]:  x = [2**63, 6, 2**63-1, 2**63+1]

In [4]: np.array(x)
Out[4]: array([9.22337204e+18, 6.00000000e+00, 9.22337204e+18, 9.22337204e+18])

In [5]: pd.array(x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda3/envs/ak-work/lib/python3.7/site-packages/pandas/core/arrays/integer.py in safe_cast(values, dtype, copy)
    162         raise TypeError(
    163             f"cannot safely cast non-equivalent {values.dtype} to {np.dtype(dtype)}"
--> 164         ) from err
    165
    166

TypeError: cannot safely cast non-equivalent float64 to int64

In [6]: np.array(x, dtype=np.uint64)
Out[6]:
array([9223372036854775808,                   6, 9223372036854775807,
       9223372036854775809], dtype=uint64)

In [7]: pd.array(x, dtype=np.uint64)
Out[7]:
<PandasArray>
[9223372036854775808, 6, 9223372036854775807, 9223372036854775809]
Length: 4, dtype: uint64
```
