### ISSUE TITLE
Improve performance of dataframe display

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1300]
Interactive users working in Jupyter notebooks frequently print out the first and last few rows of a dataframe to see sample values or check the results of a transformation. The syntax for this is just to execute `df` as a statement, which shows an html table of the head and tail of the dataframe, just like pandas does. With pandas, this operation is instantaneous. I believe it is also fast with single-node arkouda, but when running with many nodes, it can take 5-10 seconds to show this "quick" view of the dataframe. As a developer, this feels like an annoyingly trivial place to worry about performance, but for the user, viewing a dataframe is probably the operation with the widest gap between expected and actual runtime, and it is so common that it tends to bog down interactive workflows. As a goal, I'd love to get to the point where a 20-column dataframe can display in under 1 second.

Probably the first thing to do is create a benchmark that builds a 10_000 x 20 dataframe of mixed dtypes (including Categoricals, which are especially slow) and simulates displaying it by calling `df._repr_html_()`. That call is the one to measure for the benchmark. I'm hoping that a 16 node CS run of this benchmark would replicate the several seconds of latency we're experiencing on our typical node allocations.

In theory, we should be able to make this operation go quite fast. The amount of data transferred to the client and displayed by this operation is bounded by the dimensions of the dataframe and by the pandas options `'display.max_rows'` and `'display.max_columns'`, which default to something under 100 and in practice never get set above a few thousand. For our test dataframe with 20 columns and a `display.max_rows=100`, that means 2k elements and ~16KB (depending on strings) transferred, so a very small amount of data. The problem today is that the client-side code for `df._repr_html_()` loops over columns and slices the head and tail of each column as a separate indexing message, which incurs both message overhead and comm aggregation startup for each column. I think we could address this by making a dedicated server message that processes all columns within a single message and bypasses aggregation for this small amount of data.

**Comment by Ethan-DeBandi99** [comment]
Noting here that the default is `display.max_rows=10`.
