### ISSUE TITLE
write dataframe or multiple aligned pdarrays into parquet file(s) as a Table

### ISSUE THREAD

**Issue by kellyjoy15** [Bears-R-Us/arkouda#1303]
I need to save multiple columns/arrays in parquet so that it can be read back as a Table. I attempted to save the pdarrays consecutively using foo.save_parquet(... mode='append'), but I kept getting errors. Even if those errors were fixed, I'm not sure it would solve my problem. I need to read the data into another application that is expecting Table objects. However, even if we ignore my specific application, I believe that most producers/consumers of parquet format files would expect Table objects rather than individual arrays.

**Comment by pierce314159** [comment]
Being able to write a dataframe/multiple pdarray as a Table seems worthwhile enhancement!

But I do want to make sure we have resolved the `.save_parquet(... mode='append')` bug. @kellyjoy15, would you mind dropping a reproducer for this?

**Comment by bmcdonald3** [comment]
Could you provide any more information on the errors that you were seeing?

You _should_ be able to `append` Parquet columns together, but they must be columns of the same length. Also, there should be no problem reading the Arkouda generated files with pyarrow or another implementation which expects a table (Arkouda actually writes the Parquet columns to a table when you `append` to a file).

**Comment by pierce314159** [comment]
This is really two issues in one:
- `save_parquet` in `append` mode bug
- user requested enhancement of writing dataframes to Table

I suggest that the first bullet be tracked by #1304 and this track the second
