### ISSUE TITLE
Should `mode='append'` create a file if the file is non-existent?

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#1308]
During a conversation with @kellyjoy15 on https://github.com/Bears-R-Us/arkouda/issues/1304, the question was raised: "Why doesn't `mode='append'` create a file if the file does not exist already?" and this seems like a reasonable feature to me.

It seems if you plan to append to a file, writing it with `mode='append'` the first time may make sense, since you would think something along the lines of "I am going to append to this file, so it probably needs to be created in append mode." Today, this will just generate an error and the first file needs to be generated with `mode='truncate'`.

**Comment by Ethan-DeBandi99** [comment]
@bmcdonald3 - i think this would be a good feature. If we don't want it on all the time, maybe a flag that a user can specify if they want to allow file creation if it does not exist.

**Comment by pierce314159** [comment]
I don't have the most experience with IO stuff so I'll defer to others but I feel like it makes sense to be able to create a file in append mode

**Comment by kellyjoy15** [comment]
As a reference, in [python's built-in open function](https://docs.python.org/3/library/functions.html#open), "append" mode means open for writing, appending to the end of the file if it exists.

"<html>
<body>


'a' | open for writing, appending to the end of file if it exists
-- | --



</body>
</html>

**Comment by pierce314159** [comment]
It seems like it would be a good idea to change this behavior. Does anyone have a reason not to? @mhmerrill @reuster986 @ronawho

**Comment by bmcdonald3** [comment]
To me, I think the difference between Python's `open` function and our `save()` function is we aren't just opening the file, we are 1. Opening the file 2. writing to the file and 3. closing the file, so our API is different from the Python API in that sense.

If Arkouda had a more similar workflow and API, maybe something like this:
```
my-file = ak.open_file('my-file', mode='append')
my-file.write(pdarray1)
my-file.write(pdarrau2)
...
my-file.close()
```
Then I think that would be a good reason to base our API off of Python, but I think that would require a reworking of the API. I am not arguing against that design and I actually think that would make a lot of sense, but I think it would be a change from what we have today is all.

**Comment by mhmerrill** [comment]
I really don't like leaving files open. All Arkouda operations currently leave state "complete" upon message completion. That said I am ok with file creation when appending to a nonexistent file.

**Comment by mhmerrill** [comment]
@Bears-R-Us/arkouda-core-dev @bmcdonald3 I think we came to resolution on this: we are going to incorporate this behavior into Arkouda. Did This get into a PR already? or should we make an issue to track it?

**Comment by bmcdonald3** [comment]
This did not get into a PR already, I could look into making this change (and use this issue to track it if that is alright).

**Comment by bmcdonald3** [comment]
Is the idea here that, if none of the files exist, we will create the files and if only some files exist (e.g., 8 files exist when running on 16 locales), we will error?

I am not sure how we would want the latter case to be handled because if we write with 16 locales, we will then have 24 files, creating another size mismatch.

I think I will work towards getting the case where no files exist working first and then we can save that other case for another PR if we want to support that as well.

**Comment by mhmerrill** [comment]
I am pretty sure that we are looking at the "no files exist" case.

**Comment by Ethan-DeBandi99** [comment]
Closing this issue. #1365 and #1366 were added to track the specific work and linked to this issue. PRs submitted against those issues are also linked to this question for reference to discussion.
