### ISSUE TITLE
Import akutil updates

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1310]
For context, akutil is a package of client-side enhancements for arkouda popular among users who can't contribute directly to arkouda. Most of the akutil functionality has been ported into arkouda proper (thanks everyone!), but there have been a few updates to akutil since then.

I have brought in three files recently updated in akutil and placed them in a new branch (https://github.com/Bears-R-Us/arkouda/tree/dataframe-updates2), but I need some help with the merge logic. Comparing against master, many of the "changes" in these files would effectively revert some of the work that has been done to port into arkouda, which of course we don't want to do. I'm trying to figure out how to separate these old, unwanted "changes" from the actual updates intended by the user who wrote them. It feels like git should have a way to do this, e.g. by resetting the branch to the time when akutil was first ported into arkouda, so that the porting commits get applied on top of these files. Can someone help me figure out how to do this?

**Comment by Ethan-DeBandi99** [comment]
@reuster986 are you trying to merge these changes into `akutil` or into the corresponding arkouda location after we moved them in?

**Comment by reuster986** [comment]
@Ethan-DeBandi99 into the corresponding arkouda location.

**Comment by Ethan-DeBandi99** [comment]
10-4. Thanks!

**Comment by pierce314159** [comment]
I honestly think it'll be easier to just manually apply the changes than to try and use git to do it. At least with my understanding of git.

I *think* this is how to do what you're saying
```
git checkout master
git checkout -b new_branch
git reset --hard e1b43dce1e2568a7c4e8cbd8b8a7bb5252600ff6
git cherry-pick edc88b901bc7eb55d0a2f4265889ec248907a694
# resolve merge conflicts
git merge master
```
it's gonna change the commit history for master is so certainly not ideal

e1b43dce1e2568a7c4e8cbd8b8a7bb5252600ff6 is the commit which originally added in the dataframe stuff from akutil
edc88b901bc7eb55d0a2f4265889ec248907a694 looks like the commit in your branch which has the new changes

there will be lots of merge conflicts when you do `git cherry-pick` which I think should mostly be applying the new changes 
then there will be lots more merge conflicts when you do `git merge master` which i think should mostly be applying @Ethan-DeBandi99's enhancements

@ronawho knows more about git than me so maybe there's an easier way to do this? But this is the best I got. I can certainly try to handle this if you'd like @reuster986, just let me know

**Comment by pierce314159** [comment]
oh there might actually be a better way that won't mess with the git history as much 
https://stackoverflow.com/questions/1526044/partly-cherry-picking-a-commit-with-git

**Comment by ronawho** [comment]
It looks you took files from an older tree and copied them over to a tree with an up-to-date master. git doesn't really have tricks for that (so far as I know beyond re-applying old commits on top). If you know what SHA your old tree is based on though, we should be able to start there and rebase.

**Comment by reuster986** [comment]
@pierce314159 thanks for looking into this. I would certainly appreciate it if you wanted to try to handle this. Let me know if you get stuck and I can take a look!

**Comment by Ethan-DeBandi99** [comment]
@reuster986 - I took a look at this and spoke with @pierce314159. Doing it manually should be very simple and we are probably going to knock it out that way. I am finishing up working with josh on the dataframe performance stuff. Once that is done, I will handle this.
