### ISSUE TITLE
Questions from review of 1330

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1349]
We wanted #1330 in this release if possible and none of my PR feedback was showstopping, so we went ahead and merged to give a few nights of testing. I wanted to capture my feedback here to make it doesn't get lost
- Update `unique` docstring to include `groupable/ Sequences of groupable`
https://github.com/Bears-R-Us/arkouda/blob/a073707e095c6756d10b092eb7ee09c4eafba89d/arkouda/groupbyclass.py#L49-L50
- Update `union1d` to accept `groupable` like `intersect1d`
- it looks like the only place `storeUniqueKeys` is called is commented out
https://github.com/Bears-R-Us/arkouda/blob/a073707e095c6756d10b092eb7ee09c4eafba89d/src/UniqueMsg.chpl#L71

**Comment by kaydoh** [comment]
I like the new label for questions

**Comment by pierce314159** [comment]
@reuster986, when you get a chance, could you take a look at these questions from the review of #1330
