### ISSUE TITLE
enhancements to generated arkouda documentation

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1356]
I have some questions about enhancing the Arkouda Documentation.

1. changing to a "dark" theme (mostly selfish because of my cataract)
2. including the markdown files from the repo into the generated doc
3.  producing a PDF version of the documentation

**Comment by mhmerrill** [comment]
Maybe use https://pypi.org/project/pydoc-markdown/ to include the markdown files.

**Comment by Ethan-DeBandi99** [comment]
> Maybe use https://pypi.org/project/pydoc-markdown/ to include the markdown files.

@mhmerrill - I believe `pydoc-markdown` creates the documentation in markdown format. However, it looks like there is a solution with sphinx, [here](https://www.sphinx-doc.org/en/master/usage/markdown.html).

For the "dark" theme in documentation, I am not sure about actually writing the docs at https://bears-r-us.github.io/arkouda/ out with a dark theme. However, for a quick fix, `Dark Reader` is an excellent browser extension that allows you to always use a dark theme, or only use it on specific websites. It is very easy to turn on and off as well. Here is a link, [Dark Reader](https://darkreader.org/). 

It also looks like Sphinx has themes that you can apply. Some information is available here https://www.sphinx-doc.org/en/master/usage/theming.html.

It should not be difficult to convert the documentation to PDF. I have done it in the past with tools like `pdfkit`. This will allow you to take the HTML output and save it as a pdf.

**Comment by mhmerrill** [comment]
@Ethan-DeBandi99 I don't have the ability to install anything in the organizationally managed version of Chrome ;-(

**Comment by Ethan-DeBandi99** [comment]
PR #1981 adds a dark theme and includes the markdown files. 

I am still looking into generating a PDF, but I am not sure that it gets us much

**Comment by Ethan-DeBandi99** [comment]
Quick search of Sphinx documentation looks like they recommend rinohtype for direct PDF creation, but that only support rst formatting so we would not be able to include our markdown files, which would be a problem.

Sphinx supports generating Latex source files that can be used to generate PDFs, but it requires an extra step. This method looks like we would be able to include markdown files though.

**Comment by Ethan-DeBandi99** [comment]
@pierce314159, @joshmarshall1 , @jaketrookman, @hokiegeek2 - do you think we need to have PDF formatted documentation? I am not convinced it will provide anything we don't already have.

**Comment by pierce314159** [comment]
> @pierce314159, @joshmarshall1 , @jaketrookman, @hokiegeek2 - do you think we need to have PDF formatted documentation? I am not convinced it will provide anything we don't already have.

i don't see any need to produce a pdf. As far as i know, all our users have access to our github pages documentation
