### ISSUE TITLE
Standardize `.objtype` across Arkouda Classes

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1385]
Should we standardize `.objtype`? It seems to vary quite a lot
```python
>>> ak.pdarray.objtype
# 'pdarray'
>>> ak.Strings.objtype
# 'str'
>>> ak.Categorical.objtype
# 'category'
```
with a lot classes not having an class attribute `objtype` at all (`Groupby`, `ArrayView`, `Dataframe`,...). 
___
It seems to me this is behaving like a slightly unpredictable alias for `.__name__`. So I think it makes sense to make a decorator, so we can straight up alias `__name__`
```python
def objtypedec(orig_cls):
    orig_cls.objtype = orig_cls.__name__
    return orig_cls
```
So in the arkouda classes we just have to do 
```python
from arkouda.decorators import objtypedec

@objtypedec
class myClass:
```
This will look like the following

```python
>>> ak.pdarray.objtype
# 'pdarray'
>>> ak.Strings.objtype
# 'Strings'
>>> ak.Categorical.objtype
# 'Categorical'
>>> ak.GroupBy.objtype
# 'GroupBy'
>>> ak.ArrayView.objtype
# 'ArrayView'
>>> ak.DataFrame.objtype
# 'DataFrame'
>>> ak.SegArray.objtype
# 'SegArray'
```

**Comment by mhmerrill** [comment]
@pierce314159 I think this sounds like a good proposal. @reuster986 what do you think?

**Comment by reuster986** [comment]
This sounds good to me. Note that it will require some find/replace in the Chapel code that will probably affect a lot of files.
