### ISSUE TITLE
DataFrame Display Update

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1397]
Functionality was added to make displaying `ak.DataFrame` more performant. A benchmark was created to ensure proper functionality before updating DataFrame to utilize the new code.

Once the benchmark is run and validated on a multi-locale system, `ak.DataFrame` should be updated to use `get_head_tail_server` in place of `get_head_tail`.

**Comment by Ethan-DeBandi99** [comment]
@ronawho - can you run the benchmark, `benchmarks/dataframe.py` and post the results in this issue for tracking?

**Comment by Ethan-DeBandi99** [comment]
Benchmark Results:
```
numLocales = 16, N = 160,000
  _get_head_tail_server Average time = 14.2314 sec
  _get_head_tail_server Average rate = 0.00 GiB/sec
  _get_head_tail Average time = 3.1467 sec
  _get_head_tail Average rate = 0.01 GiB/sec
```

This looks like the server method is performing much worse on multi-locale, so we will need to revisit that functionality.

**Comment by Ethan-DeBandi99** [comment]
It appears that the nightly test is showing a performance improvement with @ronawho's suggestion. 

@reuster986 - do you want us to go ahead and switch to using `_get_head_tail_server`?

**Comment by ronawho** [comment]
FYI results from last night were:

```
numLocales = 16, N = 160,000
  _get_head_tail_server Average time = 2.2628 sec
  _get_head_tail_server Average rate = 0.02 GiB/sec
  _get_head_tail Average time = 3.2797 sec
  _get_head_tail Average rate = 0.01 GiB/sec
```

So `_get_head_tail_server` is faster, but I expect there to be room for improvement still. If you want me to look into that a little more (probably won't have a chance till after next week) feel free to reopen https://github.com/Bears-R-Us/arkouda/issues/1398

(BTW I wonder if it makes sense for this graph to plot seconds instead of rate)

**Comment by Ethan-DeBandi99** [comment]
@ronawho I agree, we should probably be plotting seconds. I will add an issue to update that. I will reopen #1398. I can do some digging on it as well, but suspect you will have more luck. Thanks for the assistance!
