### ISSUE TITLE
ak.Datetime() has no attribute 'values' when provided np.datetime64 as argument to constructor

### ISSUE THREAD

**Issue by Ujustwaite** [Bears-R-Us/arkouda#1405]
When attempting to instantiate an ak.Datetime object from a np.datetime64 object, an error is thrown due to ak.Datetime having no 'values' attribute. 

Tested on Arkouda version 05-05-22 and 05-09-22. Source review indicates ak.Datetime() is intended to accept this as an input to the constructor. 

Code to reproduce: 

```
#create instance of np.datetime64 using arbitrary date
date = np.datetime64('2022-05-01')

#pass as argument to ak.Datetime()
ak.Datetime(date)
```

![image](https://user-images.githubusercontent.com/7268634/169177710-21170a83-472c-4067-b08c-a386379b9d34.png)

**Comment by Ethan-DeBandi99** [comment]
@Ujustwaite - the `ak.Datetime` object is currently only designed to be instantiated using an array of on of the types listed below:

- int64 pdarray
- pd.DatetimeIndex
- pd.Series
- np.datetime64 array

Here are some suggestions to get your provided example working:
```python
# create instance of np.datetime64 using arbitrary date
date = np.datetime64('2022-05-01')

# using datetime64 array
x = np.array([date])
ak_date = ak.Datetime(x)

# using int64 pdarray
date_int64 = date.astype('datetime64[ns]').astype('int')
ak_arr = ak.pdarray([date_int64])
ak_date = ak.Datetime(ak_arr)

# using pd.DatetimeIndex
date_idx = pd.DatetimeIndex(np.array([date]))
ak_date = ak.Datetime(date_idx)

# using pd.Series
date_series = pd.Series(date)
ak_date = ak.Datetime(date_series)
```
Hopefully, this helps. If you have any other issues, please let us know.

**Comment by Ujustwaite** [comment]
Thanks for that. I guess I missed the fact that it needed to be an array of np.datetime64 rather than just an object of that class. I guess that jives with the Arkouda model, but caught me off because I was only trying to instantiate a single value.
