### ISSUE TITLE
remove `CyclicDist` as an option for pdarrays from the codebase

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1437]
This should be a small change to this file
https://github.com/Bears-R-Us/arkouda/blob/master/src/SymArrayDmap.chpl
and maybe some other file which I can't remember, it may be more complex than this but...
unless someone wants to push back...
`CyclicDist` was an option in an extremely early version of Arkouda and was never removed after Chapel introduced parallel scans on `BlockDist` we switched away from `CyclicDist` being a viable option.

**Comment by ronawho** [comment]
They only other cyclic specific code I know of is a `read_files_into_distributed_array` variant in https://github.com/Bears-R-Us/arkouda/blob/master/src/HDF5Msg.chpl

**Comment by mhmerrill** [comment]
> They only other cyclic specific code I know of is a `read_files_into_distributed_array` variant in https://github.com/Bears-R-Us/arkouda/blob/master/src/HDF5Msg.chpl

I think that use of Cyclic is ok because it only used for work distribution.

**Comment by ronawho** [comment]
I think the code is correct, I just don't think it's needed anymore if you remove support for the cyclic distribution
