### ISSUE TITLE
Update Install Doc

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1471]
The documentation needs to be updated to include `make install-arrow` now that we require Parquet.

**Comment by Ethan-DeBandi99** [comment]
@bmcdonald3 - thanks for the input! I definitely agree with you just wanted to make sure I was not missing some reason we wouldn't want it

**Comment by bmcdonald3** [comment]
Actually, I think that I might be missing something here. Isn't that step already in `make install-deps`?

https://github.com/Bears-R-Us/arkouda/blob/499ecb502da214ee71e9923fda9487c65ec4d616/Makefile#L80

**Comment by Ethan-DeBandi99** [comment]
It appears that way. I assumed it was not because we were not requiring it before. I have to head out, but I will sort out the particulars tomorrow morning and get everything squared away.

**Comment by Ethan-DeBandi99** [comment]
I have updated the `README.md`. Once #1466, is merged, I will be updating those files with the Arrow package dependencies.
