### ISSUE TITLE
Need better way to include Jupyter notebooks in repo

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#148]

**Comment by mhmerrill** [comment]
I have been looking at nbstripout
`pip install --upgrade nbstripout`

**Comment by mhmerrill** [comment]
turns out you can install `nbstripout` as a git filter to run whenever pu push (I think)

**Comment by Ethan-DeBandi99** [comment]
We are using `nbstripout`. Recommend clossing this.

**Comment by mhmerrill** [comment]
i concur.
