### ISSUE TITLE
switch order of `conda-forge` and `defaults` channel in `.yml` conda config files

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1503]
i had a bunch of difficulty with the version of `pyarrow` on my x86_64 mac running catalina os.

basically i get unknown x86_64 symbols in `pyarrow` library.
i will note that this worked fine with brew installed chapel 1.25.1.1

`conda-forge` supplies `pyarrow` ver 7.0.0
`defaults` channel supplies `pyarrow` ver 4.0.1

this seems to be a bad interaction with the new brew install of chapel 1.26, the linker, and `pyarrow` 7.0.0, this could be an artifact of the way chapel 1.26 brew package is built or something.

the fix for me was to swap the channel order and put `defaults` first which installs `pyarrow` 4.0.1

**Comment by mhmerrill** [comment]
@joshmarshall1 @Ethan-DeBandi99 this might need to spawn a short discussion of which version of `pyarrow` to use or something.

**Comment by Ethan-DeBandi99** [comment]
@mhmerrill - running on an arm64 processor, the current order is functional for me. However, switching the order is not a problem. If any issues arise, I will simply document and update my env accordingly.
