### ISSUE TITLE
security alert for numpy<=1.21.6

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1525]
there is a security alert about numpy<=1.21.6 

I really don't understand the message but it also says versions effected are numpy<=1.21.6

(https://github.com/Bears-R-Us/arkouda/security/dependabot/3)

"Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects."

**Comment by Ethan-DeBandi99** [comment]
If both check out, my plan is to set `setup.py` and the 2 conda `.yml` files to `numpy>=1.22.3` otherwise, we will set to `==` for now.

**Comment by Ethan-DeBandi99** [comment]
According to [snyk](https://snyk.io/vuln/pip:numpy), it looks like 1.22.1 also has a low priority vulnerability as well. 1.22.2 is the first that does not. I am going to also test `numpy==1.22.2`. If it is functional as well, I would recommend we set the version to `numpy>=1.22.2`

**Comment by mhmerrill** [comment]
don't forget
(https://github.com/Bears-R-Us/arkouda/blob/dfa9ff041731e0e2ee42a6d6c25761ff74c614f3/pydoc/requirements.txt#L3)
