### ISSUE TITLE
Update Chapel Unit Tests to use `assert`

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1551]
We have run into issues with the `chapel_unit_test_linux` failing because of unexpected output being produced by the test. Specifically, when overriding a chapel module with a compatibility module of the same name. The warning produced is stored in the test output file. When this file is compared against the `.good` file, it fails because the `.good` does not contain the warning line.

In order to avoid these issues, the Chapel unit tests in the `test` directory should be updated to only use assertions. We should also remove the `.good` files because otherwise, they will be used and the warning will again cause failure.

**Comment by ronawho** [comment]
FWIW the Chapel testing system always uses `.good` files to compare. In this case if there's no .good file a script creates an empty one to compare against so this probably won't help.

Note that the testing system used here (`start_test`) was designed for the development of chapel itself (where we want end-to-end tests, not just assert based unit tests.)

Probably what we want to do here longer term is use mason's testing system, which is more unit-test based. I'm not very familiar with it, but just wanted to note as-is switching to asserts won't get you what you want. https://github.com/Bears-R-Us/arkouda/pull/312 (which originally started using start_test) has more info.

**Comment by Ethan-DeBandi99** [comment]
Based on feedback, this is not something that we will be able to complete in the desired way. If/when mason testing can be added to arkouda, that will be addressed separately.
