### ISSUE TITLE
Create Chapel helper class to parse and create JSON messages

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1587]
Part of #888

First steps in moving our message processing layer to use JSON instead of space delimited strings. We should create a Chapel helper class to parse and create JSON messages

**Comment by Ethan-DeBandi99** [comment]
@ronawho, @bmcdonald3, @bradcray - I wanted to check in on this. Currently, I am only see methods to read/write JSON in the TOML module. We want to move the message parsing to a more standard format, but I am not sure we want to write to a file and read the json out after sending it as a string in a message. We will know the number of elements in the JSON and can  allocate space. Is there a reason that JSON is only readable from a file at this point? I just want to make sure I am not missing something before looking into this more. Thanks!

**Comment by hokiegeek2** [comment]
@Ethan-DeBandi99 @pierce314159 I wrote the [Message](
![image](https://user-images.githubusercontent.com/10785153/179098870-f7b891d3-7944-45f9-97fe-06c918537421.png)
) module awhile back and it leverages the built-in JSON serialization/deserialization capability. This is how I implemented the partial conversion to JSON-formatted messages. I am wondering if you can just extend what's there?

**Comment by Ethan-DeBandi99** [comment]
@hokiegeek2 - I just took at look at that. I think that would be a great starting point. thanks!
