### ISSUE TITLE
Add `client_dtypes_test` to `pytest.ini` and issue with `test_is_ipv6`

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1591]
While working #1531, I ran into an failures with `test_is_ipv6` before i made any changes. I wasn't seeing these with `make test` and was confused until I realized that it's not being run by `make test`. We should investigate `test_is_ipv6` and add `client_dtypes_test` to `pytest.ini` (and any others that are missing)

**Comment by Ethan-DeBandi99** [comment]
@pierce314159 - what was the failure you experienced with `test_is_ipv6`? I am not getting anything but warnings on `pdarray.__del__` when running `client_dtypes_test` due to objects not have `name` properties.
