### ISSUE TITLE
Remove SILENT from Makefile

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#1594]
The SILENT in the Makefile is preventing commands from displaying their output and should be removed.

**Comment by pierce314159** [comment]
I wanted to note this was added in #1561. I added .SILENT to the Makefile in order to avoid errors I was seeing where changing the directory would interrupt the compile statement. This is unfortunate because it suppresses all output from the Makefile. Thanks for fixing this ben!
