### ISSUE TITLE
Allow MultiIndex to have mixed dtypes

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1607]
The `Index` class currently requires all columns of a MultiIndex to have the same dtype, but this should not be required. A toy example of where this should be allowed but is not:

```python
>>> df = ak.DataFrame({'a': ak.arange(10, dtype=ak.int64), 'b': ak.arange(10, dtype=ak.uint64)})
>>> df.groupby(['a', 'b']).count()
...
ValueError: All columns in MultiIndex must have same dtype
```

I'm not sure what the original reason for the dtype restriction was, but there are lots of situations like this where we want to form a Series based on a groupby of multiple columns with potentially different dtypes.

**Comment by pierce314159** [comment]
It was added by me in https://github.com/Bears-R-Us/arkouda/pull/1516 as a fix for a bug where the `__repr__` method inherited from `Index` expected a `dtype`
