### ISSUE TITLE
DataFrame index error on append

### ISSUE THREAD

**Issue by gnat79** [Bears-R-Us/arkouda#1614]
The expected behavior is that `df1` has dimensions (8,2). Instead, there is a `ValueError: Shape of passed values is (8,2), indices imply (4,2)`
```
a = ak.array([1,2,3,4])
b = ak.array(['a', 'b', 'c', 'd'])
df1 = ak.DataFrame(initialdata={'numbers':a, 'letters':b})
df2 = ak.DataFrame(initialdata={'numbers':a, 'letters':b})
df1.append(df2)
```
I can add the version info to this issue on Monday, 7/25, if the issue is still open.

**Comment by gnat79** [comment]
The version is 2022.07.08. 

Looks like you've identified the problem and fixed it already, many thanks!

**Comment by Ethan-DeBandi99** [comment]
> The version is 2022.07.08.
> 
> Looks like you've identified the problem and fixed it already, many thanks!

Thank you! I took a look at it and realized it was not due to the version you were using, so I went ahead and made the correction. Thanks for bringing this to our attention!
