### ISSUE TITLE
Add `UINT32` support for parquet/arrow

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1668]
`UINT32` is a "legacy" dtype in Parquet, but a few datasets still use it. In `ArrowFunctions.cpp`, the `cpp_getType()` function will recognize `arrow::Type::UINT32` and return `ARROWUINT32`, but in `ParquetMsg.chpl`, the `getArrType()` function does not handle the `ARROWUINT32` value returned by `cpp_getType` and instead throws a `ParquetError` with message "Unrecognized Parquet data type". I wonder if the fix is as simple as just adding another case to this function, or if there was a reason we intentionally left out `UINT32`?

**Comment by pierce314159** [comment]
@Ethan-DeBandi99 or @bmcdonald3, would either of you want to take this on?

**Comment by bmcdonald3** [comment]
Ya, I can add support for this, but may not get to it until a little later in the week if that is alright.

**Comment by bmcdonald3** [comment]
(and just noting that the reason that we intentionally left out `UINT32` on the Chapel side was that we only wanted to have types that were had full support for reading and writing be recognized there, but I think you are pointing out that doesn't really make much sense)

**Comment by bmcdonald3** [comment]
@reuster986 Just to make sure that I am understanding the feature request here, you are just hoping to have the ability to read `UINT32` datasets, is that correct?

**Comment by reuster986** [comment]
@bmcdonald3 that's correct -- just for reading, not writing. Thanks!

**Comment by bmcdonald3** [comment]
I was having some difficulty creating a `uint32` file to test against (pyarrow doesn't support writing `uint32` columns anymore...), but this PR _should_ resolve the issue I believe: https://github.com/Bears-R-Us/arkouda/pull/1669.

I'll keep trying to create a reproducer using the C++ implementation, it is just a bit more involved, so thought I'd push the fix up in the meantime.
