### ISSUE TITLE
Consider renaming / restructuring the `util` subpackage 

### ISSUE THREAD

**Issue by gnat79** [Bears-R-Us/arkouda#1695]
The `util.test.util` module has been useful in managing arkouda servers, and I think it should be available for import. BUT... having a sub-package called `util` presents opportunities for namespace conflicts, for example other packages named `util`. Maybe it could be called `server_utils`. It might be worth taking a look at the entire `util.test.util` in case there are other improvements that might help.

**Comment by pierce314159** [comment]
I'm not super familiar with that file. It looks like mostly @ronawho and a bit of @hokiegeek2 who wrote that stuff, I default to their opinion on this

**Comment by ronawho** [comment]
Renaming is definitely fine with me. This was chosen when automated testing was just being added in https://github.com/Bears-R-Us/arkouda/pull/243 and the focus was just on getting something working, so I can't imagine I put much thought into the name. `server_utils`, `server_test_utils`, `server_management_utils` or something along those lines seems reasonable to me.

**Comment by hokiegeek2** [comment]
I agree with @ronawho, renaming is fine and actually a good idea 👍 💯

**Comment by gnat79** [comment]
We wrote some code to manage arkouda connections and to run arkouda in a context manager. Perhaps I can get someone to approve sharing that code back; I think this is where it would go, and I think it would be broadly useful. There are one or two system-specific pieces which I hope could be resolved by finding the appropriate lines in slurm.conf (or maybe another way). The system specific code is to find node name prefixes in order to accurately determine how many nodes are used, what is the host node for a given server, etc.
