### ISSUE TITLE
add logic to call exit(0) in DefaultServerDaemon when 2..n ServerDaemons configured 

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#1719]
As @ronawho [reported](https://github.com/Bears-R-Us/arkouda/issues/1694) on 8/19, ServerDaemon.shutdown() fails on certain Cray machines due to a [Chapel bug](https://github.com/chapel-lang/chapel/issues/7521). Need to prevent invocation of the exit(0) function in the DefaultServerDaemon unless there are 2..n ServerDaemons configured; this update will fix the default arkouda_server configuration while a fix for the root cause will be done in another, follow-up issue.

**Comment by hokiegeek2** [comment]
Logic is working: exit(0) not called in default arkouda_server config...

![image](https://user-images.githubusercontent.com/10785153/186715079-c0eb5fa1-f241-4777-98bf-888be8e9a5f4.png)

...but is called if there are 2..n ArkoudaServerDaemons configured:

![image](https://user-images.githubusercontent.com/10785153/186715673-263917a3-9397-48ac-b3ea-b8542111c487.png)

**Comment by Ethan-DeBandi99** [comment]
Corresponding PR #1720 closed.
