### ISSUE TITLE
Add sqrt and power functions to operate on pdarray

### ISSUE THREAD

**Issue by milthorpe** [Bears-R-Us/arkouda#1725]
Square root and power operations are useful; this enhancement would add them as functions to the `arkouda` module alongside `exp` etc.

`arkouda.sqrt` would be a simple element-wise operation (like `exp`). 
`arkouda.power` would have a similar interface to [`numpy.power`](https://numpy.org/doc/stable/reference/generated/numpy.power.html), accepting as the second argument either a scalar value to which all elements of the first array are raised, or an array of powers to which corresponding elements of the first array are raised.

**Comment by milthorpe** [comment]
Immediately closing this issue after discovering that Arkouda has already implemented the `**` operator :-)
E.g. the following work just fine:
```
>>> ak.array([2,0,-1])**0.5
array([1.4142135623730951 0 nan])
>>> ak.array([10,5,2])**ak.array([2,3,4])
array([100 125 16])
```

**Comment by Ethan-DeBandi99** [comment]
@milthorpe - I am reopening this. Since your first thought was to use `.sqrt` and `.power` I am going to create those functions that will essentially be aliases for the `**` operator, but will at least exist.

**Comment by milthorpe** [comment]
If it fits with the Arkouda design philosophy, sure! As a little more background - you have probably guessed this already - I am attempting a 'verbatim' translation of existing numpy code to use Arkouda, and for whatever reason `sqrt` and `power` seem to be the preferred numpy style.

**Comment by Ethan-DeBandi99** [comment]
@milthorpe - if it is the preferred style by numpy, Arkouda should definitely include it. I already added the code. I already put up a PR for this so once the rest of the team reviews it will be merged and will be in the next release. Thanks for bringing this up!
