### ISSUE TITLE
Add `where` argument to `sqrt` and `power`

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1727]
Came up in PR #1726

The numpy `sqrt` and `power` functions have a `where` argument, so we should to in order to match their API. There is some question on how it should be implemented since there is some weirdness here (it doesn't behave in a way that feels intuitive to me)

From numpy's docs:
> where array_like, optional
    This condition is broadcast over the input. At locations where the condition is True, the out array will be set to the ufunc result. Elsewhere, the out array will retain its original value. Note that if an uninitialized out array is created via the default out=None, locations within it where the condition is False will remain uninitialized.

So in my head this means that the operation (sqrt or power) occurs where `where` is True and otherwise it should default to the original value of the input array. But this is not how it works at all
```python
# how it should work in my head
# >>> np.sqrt(np.array([4,9,16]), where=[True, False, True])
# array([2., 9., 4.])
# how it actually works
>>> np.sqrt(np.array([4,9,16]), where=[True, False, True])
array([2., 0., 4.])
```
This is because numpy the out array is uninitialized by default and locations within it where the condition is False will remain uninitialized. This makes the same function call inconsistent between runs
```python
>>> n = np.array([i**2 for i in range(10)])
>>> n
array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

# uninitialized so the output is garbage
>>> np.sqrt(n, where=False)
array([4.65907677e-310, 0.00000000e+000, 4.35287203e-114, 6.59025685e+246,
       1.51948310e+132, 3.52161575e+180, 3.99190445e+252, 7.10534150e+159,
       1.56649479e+208, 1.71872047e+161])

>>> np.sqrt(n, where=True)
array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# same function call with different output...
>>> np.sqrt(n, where=False)
array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

>>> np.sqrt(n, where= n%2 == 1)
array([0., 1., 0., 3., 0., 5., 0., 7., 0., 9.])

# same function call with different output again...
>>> np.sqrt(n, where=False)
array([0., 1., 0., 3., 0., 5., 0., 7., 0., 9.])
```

It's possible i'm misunderstanding but i feel like a much more useful design choice to return `n**(1/2)` where True and `n` where False. I would absolutely love feedback from @reuster986 here and any other users since this would be a deviation from numpy

This implementation with my suggested design choice is pretty easy:
```python
def power(pda, pwr, where = True):
    if where:
        return pda**pwr
    else:
        return where(where, pda**pwr, pda)

def sqrt(pda, where = True):
    self.power(pda, 0.5, where)
```

**Comment by reuster986** [comment]
I don't think I've ever used `where=` with `sqrt` or `power`, so I had never noticed this behavior, but I definitely agree that the numpy semantics are bizarre and confusing. I would support your proposed implementation, maybe with a note/example in the docstring highlighting the difference from numpy.
