### ISSUE TITLE
Move `Categorical.__init__` to the server

### ISSUE THREAD

**Issue by joshmarshall1** [Bears-R-Us/arkouda#1736]
To support the movement of `GroupBy` to the server it'd be beneficial to first move `Categorical` to be server-side. This issue tracks moving the `__init__` functionality

**Comment by joshmarshall1** [comment]
Status Update - Majority of work on this is complete. Remaining work is resolving issues found during `make test` that mostly have to do with calling the old constructor. This issue is on hold in favor of #1682

**Comment by Ethan-DeBandi99** [comment]
Due to functionality limitations with other complex objects, we will not be moving Categorical to the server. Closing Issue
