### ISSUE TITLE
Convert MultiTypeSymbolTable from storing nilable objects to non-nilable

### ISSUE THREAD

**Issue by bradcray** [Bears-R-Us/arkouda#176]
This issue notes that the current symbol table stores `SymEntry?` entries when it seems as though it could/should store (non-nilable) `SymEntry` entries instead.  We should convert to the non-nilable version to reduce the need for nil checks altogether.  This can be done at present, but only by abusing the language as noted in https://github.com/chapel-lang/chapel/issues/14367.

This issue also relates to #169 in that using a `map` seems like a nice replacement for the associative domain/array combo that's currently used, but likely runs into https://github.com/chapel-lang/chapel/issues/14361.

For this reason, I'm marking this as being in the Chapel team's court for now.

**Comment by glitch** [comment]
Issue cleanup: I'm going to close this one since the current code uses a Map with `GenSymEntry` (non-nillable) and we are expected to merge #786 which changes the map signature to AbstractSymEntry with a loose typing hierarchy.
