### ISSUE TITLE
Add documentation for adding new `SymEntry` class to the symbol table

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1779]
During the [arkouda weekly call](https://github.com/Bears-R-Us/ArkoudaWeeklyCall), it was expressed that we need documentation for more advanced contributions to arkouda (beyond the [how to add a new command-message](https://github.com/Bears-R-Us/arkouda/wiki/How-To:-Add-a-new-command-message-in-Arkouda))

In particular @zhihuidu is looking for in depth docs on how to add a new `SymEntry` class the symbol table. The most logical place for this to go seems to be the [development how to wiki](https://github.com/Bears-R-Us/arkouda/wiki/Development---HOW-TO)

**Comment by zhihuidu** [comment]
Yes, currently we have two symbol table entries. One is GraphSymEntry and the other is DomArraySymEntry. We use GraphSymEntry to abstract a complete graph.  However, DomArraySymEntry is used to abstract a special component of a graph. The edge and vertex arrays (distributed one dimension integer arrays) are components of a graph. All edge arrays have the same size. All vertex arrays also have the same size. However, for aligned arrays, their size can be different from each other.  Currently, we define GraphSymEntry and DomArraySymEntry as the son classes of CompositeSymEntry.

**Comment by mhmerrill** [comment]
I was thinking that the wiki is a bit to ephemeral for me and would like to see updated doc in the Arkouda documentation.

**Comment by kaydoh** [comment]
I will help the team accomplish this activity.
