### ISSUE TITLE
`SegArray.__getitem__` to Server

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1783]
Part of #1682 

Update `SegArray.__getitem__()` so that SegArray indexing is done server-side.

*Note: There is a good bit of the structure all ready in place for this from SegString. We should be able to reuse this functionality.*

**Comment by Ethan-DeBandi99** [comment]
@reuster986 - I just ran across something that I wanted to get your take on. Initially, when I moved SegArray over to the server, I did not update the `__init__` because I was worried it may interrupt user workflows. However, as I am moving functionality over it appears we will need to go to something in line with `Strings` in adding a class method `from_parts` with identical parameters to the existing `SegArray.__init__` and then we could update the `__init__` to build from the `st.attrib` call response method. I have a way to work around this, but it generates the SegArray on the server twice which I am not a fan of. What are your thoughts on update to a `from_parts` method to support the current constructor functionality?

**Comment by reuster986** [comment]
I'm not sure I understand all the pieces of this puzzle, but I think imitating the `Strings` implementation makes sense, since `Strings` are basically a special case of `SegArray` to begin with. In your proposal, would the user still be able to write `sa = ak.SegArray(segs, vals)` in Python? In other words, would the user ever need to call `from_parts`?

**Comment by Ethan-DeBandi99** [comment]
The user would need to call `ak.SegArray.from_parts(segs, vals)`. Strings doesn't do this because you can essentially just call `ak.array()`. The `__init__` for strings builds of the return from the message. I just did a quick outline to verify, but the only things that updates is having to call from parts. We could add a top level function that could be called like `ak.array`, something like `ak.segarray(segs, vals)` that would call `from_parts` behind the scenes.
