### ISSUE TITLE
Investigate failures with `pyzmq=24.0.0`

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1784]
`pyzmq` released version [`24.0.0`](https://pypi.org/project/pyzmq/24.0.0/) about 2 hours ago at the time of writing

We're seeing [failures in the CI](https://github.com/Bears-R-Us/arkouda/actions/runs/3061965110/jobs/4942558887) which seem related to this:
```
Building wheels for collected packages: pyzmq
  Building wheel for pyzmq (pyproject.toml): started
  Building wheel for pyzmq (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for pyzmq (pyproject.toml) did not run successfully.
```

Note their [docs for 24.0.0](https://pyzmq.readthedocs.io/en/latest/changelog.html#id1) do call out breaking changes and  one talks about wheels:
> Breaking changes:
> - Due to a libzmq bug causing unavoidable crashes for some users, Windows wheels no longer bundle libzmq with AF_UNIX support. In order to enable AF_UNIX on Windows, pyzmq must be built from source, linking an appropriate build of libzmq (e.g. libzmq-v142). AF_UNIX support will be re-enabled in pyzmq wheels when libzmq published fixed releases.
> - Using a [zmq.Context](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Context) as a context manager or deleting a context without closing it now calls [zmq.Context.destroy()](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Context.destroy) at exit instead of [zmq.Context.term()](https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Context.term). This will have little effect on most users, but changes what happens when user bugs result in a context being implicitly destroyed while sockets are left open. In almost all cases, this will turn what used to be a hang into a warning. However, there may be some cases where sockets are actively used in threads, which could result in a crash. To use sockets across threads, it is critical to properly and explicitly close your contexts and sockets, which will always avoid this issue.

For the time being, i think we should bind to previous version until we can get to the bottom of the failures

**Comment by pierce314159** [comment]
At first glance out of the 2 breaking changes, the first seems the most relevant and would imply that the issue would be fixed in a future version (once `libzmq` releases a fix), but the runner that failed is not windows
```
Operating System
  Ubuntu
  20.04.5
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20220905.1
```

So I'm guessing the second is our problem. I'm not super well versed in zmq but it seems there's a place where we need to `"properly and explicitly close our contexts and sockets"`

**Comment by ronawho** [comment]
Not sure when I'll have time to look, but just wanted to note that I have a fair amount of experience with zmq/pyzmq, so may be able to help.

**Comment by pierce314159** [comment]
> Not sure when I'll have time to look, but just wanted to note that I have a fair amount of experience with zmq/pyzmq, so may be able to help.

That'd be great! Thanks!

**Comment by ronawho** [comment]
Looks like an upstream issue that's already been reported -- https://github.com/zeromq/pyzmq/issues/1763

**Comment by ronawho** [comment]
Upstream issue has been resolved, think you should be safe to go back to using 24.0
