### ISSUE TITLE
`SegArray.unregister()` does not remove all components of an attached SegArray from registry 

### ISSUE THREAD

**Issue by joshmarshall1** [Bears-R-Us/arkouda#1796]
When registering a SegArray on the server, calling `.unregister()` on the original will remove all components from the symbol table. However, attaching to a registered SegArray then calling `.unregister()` on the attached version will only remove the `lengths` component from the symbol table, leaving `values` and `segments` registered.

**Comment by Ethan-DeBandi99** [comment]
@joshmarshall1 - I believe I know what is causing this to happen. When we build a SegArray on the server, we are taking the the `SymEntry` passed to creation and accessing its array and creating a new `SymEntry`. I believe I may have forgotten to carry over a flag for copy here. If I need to add the copy logic back, I will do that and hopefully that should resolve this as well. Let me do a little more digging and I will update once I am positive one way or the other.

**Comment by Ethan-DeBandi99** [comment]
Ok I just verified via git blame that we did have a `copy` flag used before `SegArray` was moved to the server. I added issue #1864. I am not certain that will resolve this after review the code more in-depth, but I am hopeful it will because the default is to not create a copy of the `SymEntry`.
