### ISSUE TITLE
idna encoding/decoding

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#1799]
Request implementation of idna codec in arkouda.

in python for ascii string x, x.encode().decode('idna') will fail if x is not a valid encoding of a unicode string. Rather than error, request the ability to choose returned unicode string value (.eg. "","INVALID STRING", etc.)

**Comment by 21771** [comment]
Yes. I think that's basically correct. The one minor exception is that the
round trip would probably start/end with idna strings. I believe all utf-8
values can be properly encoded by 'idna', but not all byte/ascii values can
be properly decoded by 'idna'. Errors include invalid bytes,
non-terminating values, and some decodes to utf-8 values that don't encode
back to the original 'idna" input. Ideally we'd check for the latter, but
the main requirement is to not throw an error for an invalid "idna" value.

Here's an example. Please let me know if this makes sense.

s1 = ak.array(['münchen','zürich'])
s1_idna = s1.idna_encode()

s1_idna

returns:

array(['xn--mnchen-3ya', 'xn--zrich-kva'])


Also:

# (valid, valid, non-round-trip, invalid characters)

s2 = ak.array([ 'xn--mnchen-3ya', 'xn--zrich-kva', ' xn--zrich-boguscode
','xn--!!'])
s2_uni =  s2.idna_decode()
s2_uni

returns:

array([ 'münchen','zürich', '' , '' ])

**Comment by Ethan-DeBandi99** [comment]
Chapel does not appear to support `encode`/`decode` operations currently in a way that makes this possible without manual conversions. I added Chapel issue [#20754](https://github.com/chapel-lang/chapel/issues/20754) to have support added for going between encodings in Chapel.

**Comment by Ethan-DeBandi99** [comment]
I have a solution for this in the interim. I am working on the tests for it now. I am having some issues with our the strings conversion `to_ndarray` not handling some situations properly.

**Comment by bradcray** [comment]
@Ethan-DeBandi99 : @bmcdonald3 has also been looking into this and ramping up on idna as part of https://github.com/chapel-lang/chapel/issues/20754.  It'd be good to hear about your approach to compare notes.

**Comment by Ethan-DeBandi99** [comment]
@bradcray - @bmcdonald3 and I were already planning to discuss. I am working on a work-around since Chapel does not have support natively. It is also worth noting, I am not sure that this is something that should be limited to a single encoding as it is likely others will be required in the future.

**Comment by 21771** [comment]
Agree expanding to other codecs probably useful. Want to highlight specific requirement that arkouda implementation not throw error on invalid input (and provide an option of values to return in that case). Didn't see this addressed in other discussions. Thanks.
