### ISSUE TITLE
Look into weakref for python to track all pdarrays and objects that reference server-side objects

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#18]

**Comment by ronawho** [comment]
@mhmerrill I'm looking into https://github.com/Bears-R-Us/arkouda/issues/924 and trying to figure out if there's any places where objects referencing server-side objects are getting GC'd before we're expecting them too.

Could you say what the motivation for using weakref is? Is this related to wanting more control over when things are GC'd or just being able to track things on the client side without impacting GC?

**Comment by mhmerrill** [comment]
> @mhmerrill I'm looking into #924 and trying to figure out if there's any places where objects referencing server-side objects are getting GC'd before we're expecting them too.
> 
> Could you say what the motivation for using weakref is? Is this related to wanting more control over when things are GC'd or just being able to track things on the client side without impacting GC?

the motivation for `weakref` is because it does not bump the reference count so things can be freed/gc'd without interference.
