### ISSUE TITLE
`ak.cast()` not working

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1806]
Using `v2022.08.30`, I see the following:

```python
>>> a = ak.arange(10)
>>> ak.cast(a, ak.uint64)

# RuntimeError: bad format: missing expected literal (while reading ioLiteral "[" with path "/tmp/<filename> (deleted)" offset 0)
```

Note that fancy client dtypes depend a lot on `ak.cast`, so things like `ak.ip_address` and `ak.Fields` are broken too. Looks like maybe the message format was supposed to be ported to JSON but was overlooked?

**Comment by Ethan-DeBandi99** [comment]
@reuster986 - I have tried running this a few ways and cannot reproduce the issue that you are seeing. I have listed out the things I have tried below.

- `v2022.08.30` with Chapel `1.28.0`
- `v2022.08.30` with Chapel `1.27.0`
- `arkouda/master` with Chapel `1.28.0`
- `arkouda/master` with Chapel `1.27.0`

Is there any other information that you can provide us to run this down.  I ran your provided example successfully in all of the environments listed above and was not able to reproduce.

**Comment by reuster986** [comment]
Sorry, this was totally my mistake. I had a mismatch between client and server version. Once I fixed that, I uncovered another bug, but I will close this and start another issue for that.
