### ISSUE TITLE
Bug in `SegmentedString` Indexing when `CHPL_COMM != 'none'` and `smallIdx` is true

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1832]
Issue #1831 has a user seeing strange behavior doing dataframe indexing with SegStrings
```python
>>> pdf = pd.DataFrame({'a': list(range(1000)), 'b': list(range(1000))})
>>> pdf['a'] = pdf['a'].apply(lambda x: 'AA'+str(x))
>>> pdf['b'] = pdf['b'].apply(lambda x: 'BB'+str(x))
>>> df = ak.DataFrame(pdf)
>>> df.head(5)
     a        b
0    AA0     BB0
1    AA1     BB1
2    AA2     BB2
3    AA3     BB3
4    AA4     BB4

>>> df
     a        b
0    AA0     BB0
1     A0      B0
2     0A      0B
3     AA      BB
4    AA1     BB1
```
_Originally posted by @brentcastle in https://github.com/Bears-R-Us/arkouda/issues/1831#issuecomment-1276431537_

This is working as expected locally with `CHPL_COMM=none`. Since the user has `gasnet` enabled and `DataFrameIndexing` is one of the few cases where `smallIdx` is True, we believe this was introduced by #1537. Specifically:
https://github.com/Bears-R-Us/arkouda/blob/9c0b365844d53749d3e9e06cdb4745450529220e/src/SegmentedString.chpl#L260-L266

tagging @bmcdonald3 for his awareness

**Comment by pierce314159** [comment]
Ethan is testing this out on his fork right now by adding a test and re-enabling gasnet: https://github.com/Ethan-DeBandi99/arkouda/actions/runs/3236676740/jobs/5303191834

github workflows is having issues right now, but hopefully this will give us more confidence that this is actually the cause

**Comment by bmcdonald3** [comment]
I can just revert this code to the previous state, some of Elliot's recent work has made the code that this was getting around much faster, so the performance benefit of this has since diminished. 

I'll throw together a PR for that now, my bad for having introduced this bug.

**Comment by bmcdonald3** [comment]
I think https://github.com/Bears-R-Us/arkouda/pull/1833 should solve the problem.

**Comment by pierce314159** [comment]
> I can just revert this code to the previous state, some of Elliot's recent work has made the code that this was getting around much faster, so the performance benefit of this has since diminished.
> 
> I'll throw together a PR for that now, my bad for having introduced this bug.

No worries! Thanks for getting it taken care of so quickly!
