### ISSUE TITLE
Add python 3.11 to CI testing

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#1882]
Once all our deps support 3.11, re-add python 3.11 (and 3.X) to CI testing. 

I know we're waiting on pyarrow wheels (https://issues.apache.org/jira/browse/ARROW-17487), and when that is fixed we'll want to check if there's any other issues.

**Comment by pierce314159** [comment]
Fixed by #1883

**Comment by ronawho** [comment]
pyarrow 10 supports python 3.11 now. Look like we're waiting on h5py now

**Comment by Ethan-DeBandi99** [comment]
Just as a note here. I was messing around with some things this morning and tried installing Python 3.11 to see if anything else broke. Install it into a conda environment with our other dependency produces a ton of conflicts. Just noting in case we were hoping h5py would be the last thing. Most notably, `numpy` states in the release notes for 1.24 that Python 3.8-3.11 is supported, but on the attempted install, it requires `Python<3.11`. Something to keep an eye on.
