### ISSUE TITLE
Standardize component registration naming convention

### ISSUE THREAD

**Issue by joshmarshall1** [Bears-R-Us/arkouda#1902]
For objects that contain multiple underlying components, we have some instances where we use a `.extension` convention and some instances where we use a `_extension` convention. We should standardize this to use one or the other to maintain consistence in our naming.

**Comment by Ethan-DeBandi99** [comment]
With Categorical being moved to the server in #1736, this will be null and void.  That work is currently in progress, so we will not need to update this.
