### ISSUE TITLE
Add Documentation on Running Arkouda from a Script

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1922]
Users have presented a case where they are starting an Arkouda server from a python script and want to connect to it, perform some operations and then shutdown on exit. We need to provide documentation on this process with the flags added in PRs #1920 and #1916.

I put together some example code to be used in the documentation below
```python
import arkouda as ak

import subprocess
import json

cmd = "/Users/ethandebandi/Documents/git/arkouda/./arkouda_server -nl 1 --serverInfoNoSplash=true --autoShutdown=true"
p = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
# get the output as a string
connect_str = p.stdout.readline()

server_data = json.loads(connect_str)
server, port = server_data['serverHostname'], server_data['ServerPort']

ak.connect(server=server, port=int(port))

# Perform whatever Arkouda actions you need

ak.disconnect()
```

**Comment by ronawho** [comment]
The CI and benchmarking infrastructure do something like this with help from `util/test/util.py`. `util/test/runClient` is probably the easiest place to see how it's used.
