### ISSUE TITLE
save_all() and load_all() treat filenames differently if multiple "."

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#1956]
If a filename string has more than one '.' (e.g.  "test_1.0.hdf"), the files produced by save_all() are different than the filenames looked for by load_all().

Saved to "test_1.0_\<locales\>.hdf"
load_all() looks for "test_1*.0"

**Comment by Ethan-DeBandi99** [comment]
@21771 - First I want to note that `save_all` has been deprecated and will be removed in the next release. `to_hdf` will support the same functionality for HDF5 files. 

The design of the workflow is such that it uses the `.` to determine the file extension. This is most likely not going to be something that we can work around with the current workflow. Are you able to change it to something like `test_1_0.hdf`?

Of course, there is a solution, but it would require a bit of modification to parameters. What I would propose is having `prefix_path` be updated to only be the path and filename with NO extension. Then, we would add a `file_ext` parameter that would default to empty string. This mainly avoids the need to parse prefix path to determine the extension. We could update so that it only looks at the last `.` for the extension, but if you had a file name with no extension, this would still be an issue.

Additionally, I have plans to add an `isGlob` parameter or add processing to determine if the provide path is a glob expression. I am leaning towards adding the processing so that a user does not have to explicitly state whether or not they want it to be treated as a glob. 

I wanted to get your input before working this, since it will potentially change a few things and did not want to make any assumptions. Please let me know if separating the `filepath/filename` and `file_extension` into separate parameters is an acceptable solution for you.

**Comment by 21771** [comment]
To my knowledge, this is not a significant issue. Just wanted to be sure it
was a knob behavior. In my case I was easily able to "rename" the existing
files and then use a different naming convention. Thanks for looking into
it.


On Friday, December 23, 2022, Ethan-DeBandi99 ***@***.***>
wrote:
> @21771 - First I want to note that save_all has been deprecated and will
be removed in the next release. to_hdf will support the same functionality
for HDF5 files.
>
> The design of the workflow is such that it uses the . to determine the
file extension. This is most likely not going to be something that we can
work around with the current workflow. Are you able to change it to
something like test_1_0.hdf?
>
> Of course, there is a solution, but it would require a bit of
modification to parameters. What I would propose is having prefix_path be
updated to only be the path and filename with NO extension. Then, we would
add a file_ext parameter that would default to empty string. This mainly
avoids the need to parse prefix path to determine the extension. We could
update so that it only looks at the last . for the extension, but if you
had a file name with no extension, this would still be an issue.
>
> Additionally, I have plans to add an isGlob parameter or add processing
to determine if the provide path is a glob expression. I am leaning towards
adding the processing so that a user does not have to explicitly state
whether or not they want it to be treated as a glob.
>
> I wanted to get your input before working this, since it will potentially
change a few things and did not want to make any assumptions. Please let me
know if separating the filepath/filename and file_extension into separate
parameters is an acceptable solution for you.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci5.googleusercontent.com/proxy/rU5JpKI7uPBXAwDBoC5v5AMVjY4uBgTciORnoyOu7RDc9GFWkSfvu8oUEF4eZ0cyjOkM-p_R1XAmCsotQG05rTlT_0DkcE9ryFdWT_ye9JAAZMm8Ja3hzhh9AF6VhGtqRSFQjjpf7FGvvjRTlDMKQnNJ20u9mcApwSirVZ3hdvu8KSSUJCJxx6Eq4B_-3884j_d6aMtrelqWPu3EXdpHxFZkbqdugQspgpAc_d3h_0jUtYKUnQ=s0-d-e1-ft#https://github.com/notifications/beacon/AYBTBA2OAJSTMXUZNIZ5BXDWOWVSLA5CNFSM6AAAAAASW6LNGGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSRJSKBQ.gif>Message
ID: ***@***.***>

**Comment by Ethan-DeBandi99** [comment]
Ok great. No problem. I will add a note in the docstring that filenames including `.` will cause issues and should be avoided. It sounds like that should suffice for now. As I said, I would be happy to add the parameter. I am also looking into the glob functionality separately as we have seen some other issues with that.

**Comment by Ethan-DeBandi99** [comment]
Adding a note to wait until PR #1993 is merged to add the note to the docstring.

**Comment by 21771** [comment]
Looks like I missed a main question. Separating the filename and directory
pathname would not be an ideal change for me if it was only addressing this
situation. (But the result would only be a minor inconvenience) I would
invite polling of other users. I will continue to use file extensions,
especially now that parquet is an option.

I don't have any insight on isGlob proposal.

On Friday, December 23, 2022, Todd Larsen ***@***.***>
wrote:
> To my knowledge, this is not a significant issue. Just wanted to be sure
it was a knob behavior. In my case I was easily able to "rename" the
existing files and then use a different naming convention. Thanks for
looking into it.
>
>
> On Friday, December 23, 2022, Ethan-DeBandi99 ***@***.***>
wrote:
>> @21771 - First I want to note that save_all has been deprecated and will
be removed in the next release. to_hdf will support the same functionality
for HDF5 files.
>>
>> The design of the workflow is such that it uses the . to determine the
file extension. This is most likely not going to be something that we can
work around with the current workflow. Are you able to change it to
something like test_1_0.hdf?
>>
>> Of course, there is a solution, but it would require a bit of
modification to parameters. What I would propose is having prefix_path be
updated to only be the path and filename with NO extension. Then, we would
add a file_ext parameter that would default to empty string. This mainly
avoids the need to parse prefix path to determine the extension. We could
update so that it only looks at the last . for the extension, but if you
had a file name with no extension, this would still be an issue.
>>
>> Additionally, I have plans to add an isGlob parameter or add processing
to determine if the provide path is a glob expression. I am leaning towards
adding the processing so that a user does not have to explicitly state
whether or not they want it to be treated as a glob.
>>
>> I wanted to get your input before working this, since it will
potentially change a few things and did not want to make any assumptions.
Please let me know if separating the filepath/filename and file_extension
into separate parameters is an acceptable solution for you.
>>
>> —
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> You are receiving this because you were mentioned.<
https://ci5.googleusercontent.com/proxy/rU5JpKI7uPBXAwDBoC5v5AMVjY4uBgTciORnoyOu7RDc9GFWkSfvu8oUEF4eZ0cyjOkM-p_R1XAmCsotQG05rTlT_0DkcE9ryFdWT_ye9JAAZMm8Ja3hzhh9AF6VhGtqRSFQjjpf7FGvvjRTlDMKQnNJ20u9mcApwSirVZ3hdvu8KSSUJCJxx6Eq4B_-3884j_d6aMtrelqWPu3EXdpHxFZkbqdugQspgpAc_d3h_0jUtYKUnQ=s0-d-e1-ft#https://github.com/notifications/beacon/AYBTBA2OAJSTMXUZNIZ5BXDWOWVSLA5CNFSM6AAAAAASW6LNGGWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTSRJSKBQ.gif>Message
ID: ***@***.***>

**Comment by Ethan-DeBandi99** [comment]
@21771 - Sounds good thanks. I will just add a note to the docstring to avoid `.` in the filename for now to alert anyone else that may have the same thing happen. I think the issue with the glob expression is more of an issue on our end to ensure that we are accessing the files you'd expect. It should be easy to handle. 

My thought would be to not separate the filename and the extension as it adds something else to set, but will check with others. If that is something people want to do, I will add a separate issue.
