### ISSUE TITLE
Figure out hotfixes for bigint bugs

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#1961]
Pierce has reported a few bigint bugs upstream:
 - https://github.com/chapel-lang/chapel/issues/21206
 - https://github.com/chapel-lang/chapel/issues/21194

Once those are fixed (and assuming we don't want to wait for Chapel 1.30) we'll want to figure out some way to bring these fixes in.  This has been done in the past for things like random module fixes in https://github.com/Bears-R-Us/arkouda/issues/1220, so don't think will be too hard, just wanted to capture that we'll want to do something here.

**Comment by ronawho** [comment]
@bmcdonald3 @pierce314159 anything to do here or have you already worked around the bugs?

**Comment by bmcdonald3** [comment]
As far as the Chapel side goes:
1. resolved by: https://github.com/chapel-lang/chapel/pull/21207
2. resolved by: https://github.com/chapel-lang/chapel/pull/21244

For 1, in Arkouda, looking at https://github.com/Bears-R-Us/arkouda/blob/b7401622729286c38bc24489ebf253b8f1f37df4/src/BinOp.chpl#L1144-L1153, there is a note to undo the workaround after 1.30.

For 2, in Arkouda, looking at https://github.com/Bears-R-Us/arkouda/blob/b7401622729286c38bc24489ebf253b8f1f37df4/src/BinOp.chpl#L1217-L1230, I don't know if the fix of casting the LHS to int made it in, but I am not entirely sure what that `has_max_bit` check is doing.

Do you know if that `**` issue is still happening in Arkouda today Pierce?

**Comment by bmcdonald3** [comment]
If so, I think we just need to cast the RHS of that operation to be an `int` instead of a `bigint`.

**Comment by pierce314159** [comment]
The `has_max_bits` case is just when we have something like `max_bits=64`, we are gonna want to do the exponentiation mod `2**64`. So in that case the `ei.powMod` is exactly what we want and it avoids the bug.

However in the `tmp = la ** ra` case (when `max_bits` is not set), you are completely right that is still incorrect. I just verified on master
```python
>>> ak.array([2**64-1, 2**64-2, 2**64-3], dtype=ak.bigint) ** ak.arange(3, dtype=ak.bigint)
array(["1" "0" "0"])
```

I also think casting `ra:int` will solve this and that should be the last workaround needed for this issue. I'll put a PR real quick to add that which closes this issue

**Comment by pierce314159** [comment]
ooo one other thing I've encounter that I haven't put in a chapel issue. I'm not sure if it's a bug or a design choice, but we can't cast from bool to bigint. We have to first cast to int and then cast to bigint. This kinda makes sense (just 1 or 0 in a bigint seems a bit silly), but since we do things generically a lot of time it sometimes results in a corner case
https://github.com/Bears-R-Us/arkouda/blob/b7401622729286c38bc24489ebf253b8f1f37df4/src/BinOp.chpl#L1621
