### ISSUE TITLE
Improve/Correct examples in the documentation

### ISSUE THREAD

**Issue by gnat79** [Bears-R-Us/arkouda#1965]
Some parts of the documentation are in need of updates, specifically this page which seems to have misled more than one individual.

https://bears-r-us.github.io/arkouda/examples.html

It would be nice to have a high level introduction to dataframes, and maybe some of the other features of arkouda.

**Comment by Ethan-DeBandi99** [comment]
Awesome, thank you. I think my notebook covers most of that, So I will point there and basically just add that information to the examples file.
