### ISSUE TITLE
overflow notification for GroupBy aggregations

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2010]
Ran into an issue with overflows for ak.GroupBy.avg(). Should there be some warning or indicator? I saw references to overflow checking elsewhere in the code. Thanks.

**Comment by 21771** [comment]
Just wanted to correct typo. Issue applies to ak.GroupBy.mean().

**Comment by Ethan-DeBandi99** [comment]
@21771 - It appears that only one of the components is actually running a check for this. I am looking into the best path forward. If possible, could you provide the error message so we may be able to locate where the failure point was? Thanks!

**Comment by Ethan-DeBandi99** [comment]
@21771 - could you also provide what `skipna` is set to? Are you using the default of `True`?

**Comment by Ethan-DeBandi99** [comment]
Based on my initial review of this code, We definitely need to add a memory check when we are working with `real` and `skipna=True`. This case creates a copy of the array with `NaN` values replaced by `0.0`.

If we want to be extra safe, we can validate that there is enough memory to create the `counts`, `sums` and `res` objects. We could do something like 
```chapel
overMemLimit((numbytes(int) * D.size * 2) + (numbytes(real) * D.size))
```
I am not sure that this additional check is needed, but we definitely need to check before making a copy of values.

**Comment by 21771** [comment]
Not sure if this is OBE, but I received no error message, just incorrect
results for aggregations of many very large int64s. The sums appear to
overflow 64 bits. I'm not able to test it now, but a test would be to use a
column containing values= 2**63-1  as a target for the .mean() of a
GroupBy. Sorry I can't verify this right now, but given my results from
Tuesday I believe this will return values of less than 2**63-1 as a result
of an overflow. I saw the same behavior with .sum() where the sum was less
than the value of individual elements.

**Comment by pierce314159** [comment]
I believe we still want to look into this especially since the issue seems to be an integer overflow providing incorrect results not a server crash due to running out of memory

if i'm misreading @Ethan-DeBandi99 feel free to close again

**Comment by pierce314159** [comment]
Closing in favor of #2076
