### ISSUE TITLE
Gasnet error in 1999

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#2013]
PR #1999 is resulting a gasnet error, specifically `var low = tmp % block_size;` in `bigint_to_uint_arrays`.

**Comment by bmcdonald3** [comment]
This is an issue with the Chapel bigint code and will be fixed on Chapel `main` by https://github.com/chapel-lang/chapel/pull/21321, but we will still need to come up with a fix for Arkouda in the meantime.
