### ISSUE TITLE
CSV Support

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2047]
Ability for Arkouda to natively support CSV files for 
- Read
- Write

**Comment by Ethan-DeBandi99** [comment]
CSV is a bit different from other file formats we currently support. Since columns do not have to be named, `ls` like functionality gets a bit tricky. Additionally, this presents challenges with a user selecting a subset of columns if the columns are not named. I see a few options here:

1. Always assume that the columns will be named. Removes the need for a `named_columns` flag that the user would set to indicate if the file contains column names.
2. Eliminate `ls` functionality for CSV. This would assume if no columns are provided to select, the user wants all data. Error will be returned if a column does not exist (checked on the server once the names are parsed). This also requires a `named_columns` flag be set when selecting a subset of columns.
3. Provide separate client function for getting csv datasets that would provide some notification that columns are not named in the event that names do not exist. Again this requires the user to set a `named_columns` flag and operate off that.

My current implementation will always write column names if the file is written with Arkouda. However, based on previous requirements, I thought it would be beneficial to be able to read data without columns even though it does not really fit into our model. I am leaning towards the assumption that columns are always named though because than we can maintain the same workflows for CSV.

@pierce314159, @hokiegeek2, @joshmarshall1, @jaketrookman - do you have any thoughts on this?

**Comment by pierce314159** [comment]
I don't have much expertise here, but I think there's a fair chance that users will want csv support for files without column names. I think this is fine to add in later if that functionality is requested. So a roundabout way of saying i agree with you lol

**Comment by Ethan-DeBandi99** [comment]
Added issue #2063 to handle CSV without column names as separate task.
