### ISSUE TITLE
File of Origin on Read

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2050]
When reading data from HDF5/Parquet files that are distributed, add a flag to return a column indicating the `File of Origin` as a column in the dataset. When returned to the client, this should be a `Categorical` object.

The intention is to allow users to easily determine where the data came from.

**Comment by 21771** [comment]
Works perfectly. Thank you!

**Comment by 21771** [comment]
Works perfectly! Thanks!
