### ISSUE TITLE
add pdarray data type and size to metrics

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#2060]
**Feature Description**
The arkouda metrics include a variety of metric types including number of requests, number of requests per user, etc..., but a user would like the pdarray data type and size to be included. 

**Additional context**
Will require changes with MetricsMsg.chpl and ServerDaemon.chpl

**Comment by hokiegeek2** [comment]
example logging:

![image](https://user-images.githubusercontent.com/10785153/213540501-bd3bcda4-c91d-4895-9686-e02365248c4b.png)

debug logging showing addition of response time value to avg response time metric:

![image](https://user-images.githubusercontent.com/10785153/213540956-435b9e3c-0c0f-4754-a397-79b50bebddaa.png)

**Comment by pierce314159** [comment]
closed by https://github.com/Bears-R-Us/arkouda/pull/2067
