### ISSUE TITLE
Improve bigint creation performance

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#2088]
There's been feedback that performance for creating bigint pdarrays is really poor especially when the `max_bits` flag is set. I'll work on speeding this up a bit and create a benchmark to track the perf changes.

It is definitely possible that just creating a large array of bigints is too slow for the common use cases. If that's the case, we might want to investigate a different implementation that keeps up with `2/4` uint arrays when `max bits <= 128/256` respectively and use the current implementation only when `max_bits` is not set or is `>256`. Maybe @ronawho will have a better idea of this

Edit:
Sorry I don't think i made it clear, this is specifically creating `bigint` pdarray using the `bigint_from_uint_arrays` function

**Comment by ronawho** [comment]
I haven't seen bigint array creation be too expensive. It is more expensive than creating int arrays since we have to do a small heap allocation for each element, but I wouldn't expect it to be massively behind. I think I was seeing maybe a 4x perf hit compared to `int(64)` array creation when I checked a standalone chapel test. 

I was seeing much slower array deinit, which I noted in https://github.com/chapel-lang/chapel/issues/15215, but I think that'll have a pretty easy fix.

---

Here's a quick perf test:

```chpl
use TestBase;
use BigInteger;

config const N = 10**8;
proc testit(type elemType) {
  writeln(elemType:string);
  const D = makeDistDom(N*numLocales);

  var d: Diags;
  {
    d.start();
    var A: [D] elemType;
    d.stop("array create");

    d.start();
    forall a in A do a += 4;
    d.stop("array add");

    d.start();
  }
  d.stop("array delete");
  writeln();
}

testit(int);
testit(bigint);
```

16-node-cs-hdr results:
```
 make test-bin/BigintCreation
./test-bin/BigintCreation -nl 16 --N=$((2**30))

int(64)
array create: 0.13s
array add: 0.15s
array delete: 0.00s

bigint
array create: 0.38s
array add: 0.57s
array delete: 25.62s
```

So bigint creation is ~3x slower than int64 creation, operators are maybe ~4x (though will get more expensive with more digits/limbs), and deletion is a lot slower. That's because deinit is currently serialized (which doesn't matter for POD types since there's nothing to deinit.) Parallelizing deinit with some upstream chapel changes brings this much closer to creation times:

```
./test-bin-par-deinit/BigintCreation -nl 16 --N=$((2**30))

int(64)
array create: 0.13s
array add: 0.15s
array delete: 0.00s

bigint
array create: 0.37s
array add: 0.58s
array delete: 0.33s
```

None of that looks bad to me, so I'd definitely be interested in seeing a benchmark or getting a pointer to the arkouda init code. 

---

If we need to, we could consider creating larger fixed-width types that have inline storage instead of small heap allocations. It'd basically be an array of tuples of limb that we then call much lower level gmp mpn functions on. This is a rather large effort, but it's possible. Personally, I'd see how far we can get with bigint and consider that a potential future optimization.

**Comment by pierce314159** [comment]
Okay that's good news! I hadn't looked into it too much yet, this was just based on user feedback. They were seeing large creation times when using the `bigint_from_uint_arrays` function. In that function we cast large uint64 arrays to bigint, shift them into the correct spot and add them in. 

https://github.com/Bears-R-Us/arkouda/blob/fa4c587eafb1efcf0abf0a595b08cc12ac6bd341/src/BigIntMsg.chpl#L28-L44

I remember mppf said the `mod` for the `max_bits` was not the most efficient and we should do `& 2**max_bits -1`, so that's the first thing I was planning on trying to see if we can get better peformance

**Comment by ronawho** [comment]
Yeah, we can definitely improve that code. I think the most optimal thing would be to just iterate over all the arrays at once and use some of the internal gmp functions to directly write to limbs instead of shifting. I'd also be curious to learn more about why/when you need to take array's of uints and turn them into bigint arrays. I think this could be useful to go over in the next dev meeting

**Comment by pierce314159** [comment]
> Yeah, we can definitely improve that code. I think the most optimal thing would be to just iterate over all the arrays at once and use some of the internal gmp functions to directly write to limbs instead of shifting. I'd also be curious to learn more about why/when you need to take array's of uints and turn them into bigint arrays. I think this could be useful to go over in the next dev meeting

This sounds great! And unfortunately, that's what I'm doing under the hood for every bigint array creation. It was the best solution I came up with for how to take an array created on the client and replicate it on the server. So i take the array and do a divmod of sorts to break into it's 64 bit chunks and then recombine
https://github.com/Bears-R-Us/arkouda/blob/fa4c587eafb1efcf0abf0a595b08cc12ac6bd341/arkouda/pdarraycreation.py#L270-L275

**Comment by pierce314159** [comment]
the only other way i could think to this would be to create a string of arrays and cast to bigint. This seemed like the easier approach to me, so it's the one i went with for the first iteration

**Comment by ronawho** [comment]
Ah, so the arrays-of-uints is how you serialize on the client side.. Yeah, that's interesting and I don't have any better ideas off the top of my head. What's the type on client side before serialization? Is it a numpy array of python integer objects?

This is actually not so different from chapel aggregation of bigints. Somehow you need to serialize, transmit, and deserialize the data. Creating arrays of fixed-width ints is one option, but pretty inefficient. On the chapel side we know how to serialize/deserialize bigints, but here it's serializing python integer objects and deserializing into bigints which is more complex.

If we could serialize the number of limbs and the data into a bytes buffer we could probably do something really efficient here, but it's not as obvious how to do that on the client side to me. Will need to think on that some more.

**Comment by ronawho** [comment]
Array of strings is interesting too, but I suspect that's pretty inefficient (both converting to strings on the client side and converting from strings on the server side.)

Oh.. and I don't know how this didn't jump to me before -- I was thinking you had a distributed bigint array and distributed uint arrays, but if the uint arrays are coming from the client, they must be local arrays. So there's probably communication overhead in here as well. Ok, I definitely think we can do something better here, but will need some time to think and make suggestions. Is it ok to delay until dev meeting to start brainstorming? (not sure what your timeline is, but I'm spread a little thin at the moment)

**Comment by pierce314159** [comment]
> Ah, so the arrays-of-uints is how you serialize on the client side.. Yeah, that's interesting and I don't have any better ideas off the top of my head. What's the type on client side before serialization? Is it a numpy array of python integer objects?
Exactly! And they are numpy arrays of type `object`, i.e. any python object
```python
In [2]: np.array([2**200])
Out[2]: 
array([1606938044258990275541962092341162602522202993782792835301376],
      dtype=object)
```

> This is actually not so different from chapel aggregation of bigints. Somehow you need to serialize, transmit, and deserialize the data. Creating arrays of fixed-width ints is one option, but pretty inefficient. On the chapel side we know how to serialize/deserialize bigints, but here it's serializing python integer objects and deserializing into bigints which is more complex.
> 
> If we could serialize the number of limbs and the data into a bytes buffer we could probably do something really efficient here, but it's not as obvious how to do that on the client side to me. Will need to think on that some more.

it seems there's a python lib for gmp ([gmpy](https://pypi.org/project/gmpy/)) so maybe we could use that to get at the limbs? (disclaimer, i know next to nothing about the internal workings of gmp)

**Comment by pierce314159** [comment]
> Oh.. and I don't know how this didn't jump to me before -- I was thinking you had a distributed bigint array and distributed uint arrays, but if the uint arrays are coming from the client, they must be local arrays. So there's probably communication overhead in here as well. Ok, I definitely think we can do something better here, but will need some time to think and make suggestions. Is it ok to delay until dev meeting to start brainstorming? (not sure what your timeline is, but I'm spread a little thin at the moment)

That's totally fine! Any help you can provide is very appreciated

**Comment by ronawho** [comment]
I think we can make use of `int.to_bytes()` and `int.from_bytes()` to serialize/deserialize on the client side -- https://docs.python.org/3/library/stdtypes.html#additional-methods-on-integer-types


For for a client->server serialization, it'd be something like:

```python
serialized_bytes = bytes()
for e in arr:
  byte_size = (e.bit_length() + 7) // 8
  serialized_size = byte_size.to_bytes(8, byteorder='big')
  serialized_val = e.to_bytes(byte_size, byteorder='big')
  serialized_bytes += serialized_size
  serialized_bytes += serialized_val
```

Where the end result should be a big-endian encoding of 8-byte-size+variable-length-value. There's a few things to improve here:
 - growing `serialized_bytes` each time will likely be slow. I think we could do a first pass to calculate the total size, create a bytearray and just copy the values in. Should time/profile this though
 - this does not handle negative numbers. On the server side bigints store the sign as part of the size. Here I think we should do the same and store the sign as part of size and serialize the absolute value
 - I think byteorder should match the server's byte order. `get_server_byteorder()` is available for this already

**Comment by ronawho** [comment]
Note that the above is for the client<->server transfer serialization. Pierce also mentioned performance issues for creating distributed arrays of bigints from 2 distributed uint arrays.

**Comment by ronawho** [comment]
Here's a quick test for `bigint_from_uint_arrays`:

```python
#!/usr/bin/env python3

import argparse, time
import arkouda as ak

parser = argparse.ArgumentParser("bigint_from_uint_arrays perf test")
parser.add_argument("hostname")
parser.add_argument("port", type=int)
parser.add_argument("-n", "--size", type=int, default=10**8)
args = parser.parse_args()

ak.connect(args.hostname, args.port)

a = ak.randint(0, 2**32, args.size, dtype=ak.uint64)
b = ak.randint(0, 2**32, args.size, dtype=ak.uint64)

start = time.time()
ba = ak.bigint_from_uint_arrays([a, b])
end = time.time()
print("time (N={}): {:.4f} sec".format(args.size, end-start))
```

16 node perf results with (2) 8G arrays (1G per node total):
```sh
runClient -nl 16 uint_to_bigint_perf.py --size=$((2**30))
# time (N=1073741824): 52.5788 sec
```

And taking a quick look at the code, I think there's a few performance issues:
 - `+reduce` on a distributed array will result in creating a distributed array per iteration and then trying to do something at the end of the forall to merge the arrays together. I'm not sure that merging today is particularly efficient and we're creating a lot of arrays anyways
 - There's array creation to convert the uint array to a bigint array, but I think we can just do that with task-local vars

Here's a patch that switches to serially updating the bigint array "limb" at a time using task-local bigints. This could be further optimized by just modifying limbs directly, but that's more complicated work. 

```diff
diff --git a/src/BigIntMsg.chpl b/src/BigIntMsg.chpl
index fb7141fd..4351db38 100644
--- a/src/BigIntMsg.chpl
+++ b/src/BigIntMsg.chpl
@@ -29,10 +29,13 @@ module BigIntMsg {
         // block size is 2**64
         var block_size = 1:bigint;
         block_size <<= 64;
-        forall (name, i) in zip(arrayNames, 0..<num_arrays by -1) with (+ reduce bigIntArray) {
-            var tmp = toSymEntry(getGenericTypedArrayEntry(name, st), uint).a:bigint;
-            tmp <<= (64*i);
-            bigIntArray += tmp;
+        for (name, i) in zip(arrayNames, 0..<num_arrays by -1) {
+            ref uintA = toSymEntry(getGenericTypedArrayEntry(name, st), uint).a;
+            forall (uA, bA) in zip(uintA, bigIntArray) with (var tmp: bigint) {
+              tmp = uA;
+              tmp <<= (64*i);
+              bA += tmp;
+            }
         }
         var retname = st.nextName();
```


Timings with that:
```sh
runClient -nl 16 uint_to_bigint_perf.py --size=$((2**30))
# time (N=1073741824): 0.1336 sec
```

So ~50 -> ~0.1 seconds. I'm not confident the implementation is correct, but I think the general strategy is sound.

**Comment by ronawho** [comment]
https://github.com/Bears-R-Us/arkouda/pull/2131 implements the above optimization and one to the max_bits modding.

**Comment by ronawho** [comment]
https://github.com/Bears-R-Us/arkouda/issues/2139 optimized `bigint_to_uint_arrays`

@pierce314159 what's remaining to complete this issue? client<->server transfers?

**Comment by pierce314159** [comment]
> @pierce314159 what's remaining to complete this issue? client<->server transfers?

I think the PRs you mentioned cover this work. The user request was here was really performance of `bigint_to/from_uint_arrays`, so I think we can close this. We certainly want to improve perf of other aspects of bigint including transfers, but I think tracking that in #2134 makes more sense.

Thanks for all the help on this!

**Comment by ronawho** [comment]
Sounds good. I've forked the serialization ideas off into https://github.com/Bears-R-Us/arkouda/issues/2143 but don't think it's worth spending time on unless benchmark results show us that performance is bad enough that we need to optimize (just wanted to avoid losing the idea until we decide whether we need it or not)
