### ISSUE TITLE
Disable bulk transfer when using quick compile

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#2092]
Opening PR for work from and behalf of @e-kayrakli. 

When investigating ways to improve Arkouda compilation time for developers, @e-kayrakli discovered that if we disable the bulk transfer optimization we can see significant build time improvements when compiling with gasnet (>2 minutes observed on my machine). This disables a performance optimization, so we only want to use it when doing a developer build.

| CHPL_COMM | master | this branch |
| --------- | ------:| -----------:|
| none      | 426s   | 424s        |
| gasnet    | 1332s  | 1185s       |

**Comment by Ethan-DeBandi99** [comment]
@bmcdonald3 - Thanks!
