### ISSUE TITLE
bug loading `dataframe` containing a `segarray` with an `_` in column name

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2105]
**Feature Description**
When saving dataframes containing segarrays I have not found a straight forward way to read the data back into a dataframe. Is there a command or flags to enable automatic recreation of the segarrays from the _segments and _values arrays? This may exist but I have not found it.

```
**Example Behavior**
example:    df = ak.DataFrame(ak.recreate_segarrays(ak.read('foo.hdf')))
or               df = ak.DataFrame(ak.read('foo.hdf',restore_segarrays=True))
or               df = ak.DataFrame(ak.read('foo.hdf'),restore_segarrays=True)
```

**Describe Workarounds**
currently have a function to do this based on dataset names and array lengths, but am looking for a more robust capability.

**Comment by pierce314159** [comment]
@21771 i think this is a bug and segarray should be read back in by default but @Ethan-DeBandi99 would know better. I've only looked into this a bit, but it definitely seems like the code to try and rebuild the segarray is there. It looks like it's trying to read `c` as the column instead of `c3` here
```python
In [3]:         df_dict = {
   ...:             "i": ak.arange(3),
   ...:             "c_1": ak.arange(3, 6, 1),
   ...:             "c_2": ak.arange(6, 9, 1),
   ...:             "c_3": ak.segarray(ak.array([0, 9, 14]), ak.arange(20)),
   ...:         }
   ...:         akdf = ak.DataFrame(df_dict)

In [4]: akdf.to_hdf('seg_test.h5')

In [5]: ak_loaded = ak.DataFrame.load("seg_test.h5")
dict_keys(['c_1', 'c_2', 'c_3_segments', 'c_3_values', 'i'])
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[5], line 1
----> 1 ak_loaded = ak.DataFrame.load("seg_test.h5")

File ~/proj/arkouda/arkouda/dataframe.py:1611, in DataFrame.load(cls, prefix_path, file_format)
   1609 # update dict to contain segarrays where applicable if any exist
   1610 if len(seg_cols) > 0:
-> 1611     df_dict = {
   1612         col: SegArray.from_parts(df_dict[col + "_segments"], df_dict[col + "_values"])
   1613         if col in seg_cols
   1614         else df_dict[col]
   1615         for col in df_dict_keys
   1616     }
   1618 df = cls(df_dict)
   1619 if filetype == "HDF5":

File ~/proj/arkouda/arkouda/dataframe.py:1612, in <dictcomp>(.0)
   1609 # update dict to contain segarrays where applicable if any exist
   1610 if len(seg_cols) > 0:
   1611     df_dict = {
-> 1612         col: SegArray.from_parts(df_dict[col + "_segments"], df_dict[col + "_values"])
   1613         if col in seg_cols
   1614         else df_dict[col]
   1615         for col in df_dict_keys
   1616     }
   1618 df = cls(df_dict)
   1619 if filetype == "HDF5":

KeyError: 'c_segments'
```

**Comment by pierce314159** [comment]
@21771 I think I found the issue, can you verify something for me real quick? Does the column name for the segarray in your dataframe contain any `_`?

**Comment by pierce314159** [comment]
with the PR i just posted, the example I provided works
```python
In [3]: df_dict = {"c_1": ak.arange(3, 6, 1),"c_2": ak.arange(6, 9, 1),"c_3": ak.segarray(ak.array([0, 9, 14]), ak.arange(20))}
   ...: akdf = ak.DataFrame(df_dict)

In [4]: akdf
Out[4]: 
   c_1  c_2                          c_3
0    3    6  [0, 1, 2, 3, 4, 5, 6, 7, 8]
1    4    7          [9, 10, 11, 12, 13]
2    5    8     [14, 15, 16, 17, 18, 19] (3 rows x 3 columns)

In [5]: akdf.to_hdf('seg_test.h5')

In [6]: ak.DataFrame.load("seg_test.h5")
Out[6]: 
   c_1  c_2                          c_3
0    3    6  [0, 1, 2, 3, 4, 5, 6, 7, 8]
1    4    7          [9, 10, 11, 12, 13]
2    5    8     [14, 15, 16, 17, 18, 19] (3 rows x 3 columns)
```
As long as the column name of the segarray within your dataframe contains an underscore, I believe it will solve your issue

**Comment by 21771** [comment]
Apologies for the late response. In my case the original column names do not have underscores ('_'). The only underscores in the column names were before "segments" and "values" in the data read in.  

When trying to cast as an ak.DataFrame() it returns:
ValueError: Input arrays must have equal size

It's possible that it is cause by a read error (ak.load_all()) that appears only in the logs. There is no warning or error returned to the client and the data looks fine except for the separate "_segment" and "_value" columns for the segarrays.

In the server logs are lines like:
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread  <#>:
  #000: HD5.c line 292 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: H5Dint.c line 1205 in H5D__open_name(): not found
..
  #002: H5Gloc.c line 422 in H5G_loc_find(): can't find object
  #003: H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
  #004: H5Gtraverse.c line 741 in H5G__traverse_real(): component not found
  #000: H5D.c line 372 in H5Dget_space(): not a dataset
  #000: H5Shyper.c line 7053 in H5Sselect_hyperslab(): not a dataspace
  #000: H5Dio.c line 177 in H5Dread(): dset_id is not a dataset ID
..

**Comment by 21771** [comment]
Looks like user error

The following works fine:
```
<ak.DataFrame>.save(<path>)
ak.DataFrame.load(<path>)

```

Problem only occurs with the following (which I'll avoid):

ak.DataFrame(ak.load_all(<path>))

**Comment by pierce314159** [comment]
@21771 Oh! Well your issue lead to the discovery of the underscore column name bug! So this worked out really well

I'll open a separate issue to track potentially adding the `ak.DataFrame(ak.load_all())` workflow

**Comment by 21771** [comment]
Yes it would probably be good to have the segarrays reconstituted by read() and load_all() in case a user wasn't using dataframes.

Thanks again!

**Comment by pierce314159** [comment]
Issue #2111 added to track adding the `load_all` and `read` workflows!
