### ISSUE TITLE
implement join-on-eq between int64 arrays

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#211]
We need to implement a simple join between two int64 arrays to allow for multi-hop graph simple pattern match.

server message will look something like:
join-eq (result-limit) (pda1,...) (pda2,...) (scalars) (where-clause)
 * (result-limit) => number of results to allocate space for and potentially return
 * (pda1,...) => first pda to join on and other pda parallel to pda1
 * (pda2,...) => second pda to join on and other pda parallel to pda2
 * (scalars) => scalars to use in the where-clause
 * (where-clause) => boolean clause to test on matching value-indices,
```
if (pda1[i] == pda2[j]) {
    if (eval where-clause(i,j)) {
        put (i,j) into result set;
    }
}
```

```python
# DestIP and TimeStamp1 are pdarrays of the same size/length
# SrcIP and TimeStamp2 are pdarrays of the same size/length
ak.join_eq(limit=1000000, (DestIP,  TimeStamp1), (SrcIP,  TimeStamp2),  (dt = 1800),
                  (abs(TimeStamp1 - TimeStamp2) < dt))

```

This might result in a client to server message like:

```msg = "join-eq (1_000_000) (id_1, id_2) (id_3, id_4) (dt = int64 1800) (abs(id_2 - id_4) < dt)"```

**Comment by mhmerrill** [comment]
**Sketch of general strategy to follow:**

```
allocate two result-limit long arrays for indices from each satisfying result pair
G1 = GroupBy(pda1) and G2 = GroupBy(pda2)
forall ((v1,seg1) in G1) {
    (found, seg2) = match(v1, G2)
    if (found) {
        for (i in G1.seg1) {
            for (j in G2.seg2) {
                if (eval(where-clause, i, j) {
                    put (i, j) into result
                }
            }
        }
    }
}
````

**Comment by mhmerrill** [comment]
I am thinking we should make the expressions to interpret simple lisp-like expressions:
```lisp
(< (abs (- TimeStamp1 TimeStamp2)) 1800)
```
this should make it easier to parse and interpret.

**Comment by bradcray** [comment]
Talking about this a bit with Mike today about the "permit the user to write a general where-clause function" challenge, my head went toward an approach in which the where-clause function would be:
* written in, or compiled down to C
* wrapped in a .so
* dynamically loaded into the arkouda server
* invoked through an external C function pointer

I'm not certain that this would work, and I think there would be challenges here, such as:
* where is the C compiler invoked?
  - on the host?  what if the binary isn't compatible with the server?  cross-compile?
  - on the server's compute nodes?  is a C compiler available there?
* can the .so be loaded in a scalable manner?
* are Chapel's C function pointers sufficient to support this pattern?
* how would argument matching / validation be done?

But I just wanted to capture the thought for consideration.  Tagging @dlongnecke-cray and @vasslitvinov who helped talk through this idea and helped identify some of these challenges, and @mppf who has thought a fair bit about dynamically generating or incorporating code into running Chapel programs.

**Comment by mhmerrill** [comment]
I think I am going to back off from arbitrary code for the `where-clause` in the sort term.
At least to start we will define a couple of pre-defined predicates, something like:
```chapel
/* think of a and b as time stamps and delta as +/- delta time */
proc absWindowDelta(a: int, b: int, delta: int): bool {
    var diff = a - b;
    var absDiff = if (diff < 0) then (-diff) else diff;
    return (absDiff < delta);
}
/* think of a and b as time stamps and delta as positive delta time */
proc posWindowDelta(a: int, b: int, delta: int): bool {
    return ((a < b) && ((a + delta) > b));
}
```

**Comment by mppf** [comment]
You might have the "where clause" simply point to one of a library of predicates known to Arkouda (I think that's one way of viewing what you posted in the last comment).


I think it's notionally possible to move a Python expression to the compute nodes and run it in a Python interpreter on the compute node.

It's also possible to consider having support for an `eval` in Chapel code that accepts a Chapel snippet as input, but this requires a bunch of work we have planned but is not done yet.

Generating C code into a .so and then loading and running it seems workable to me, though. There will be challenges but it seems sufficiently performant and general. Generating such a C function seems no harder (to me) than creating a simple lisp interpreter.

**Comment by gbtitus** [comment]
By now it seems this is probably beyond-topic, but just as a note for the future ...

When you get around to supporting dynamically executing arbitrary code compiled just-in-time during execution, don't create a shared object on the client side and drop it on Lustre for the server nodes to `dlopen()`.  That won't scale, because of hot-spotting Lustre.  Instead, send the contents of the shared object via ZMQ broadcast, which ought to be scalable (*), and have the server nodes drop the bits into a local `/tmp` shared object and `dlopen()` that instead.

(*) And if ZMQ doesn't have a scalable broadcast already that seems like a problem you'd want to solve anyway, so this still seems like the right way to go.

**Comment by ronawho** [comment]
I agree that it makes the most sense to have a couple of pre-defined predicates to start.

For extending to arbitrary expressions, one option would be to embed a python interpreter, which looks pretty straightforward: https://docs.python.org/3.8/extending/embedding.html. If the speed of the where clause evaluation is important you might need to go down the compiled route, but compiling and dynamically loading an expression seems like it'll be a lot more complicated.

---

Implementing the join with `idx = fetch-and-increment(results-found)` will introduce a comm bottleneck. That will be very slow for non-ugni configs, but even under ugni where remote atomics are fast that will probably be a bottleneck. You'll probably want to batch locally and reserve a bunch of indices at once.

Do the results need to be deterministic or is it ok if the results differ from call to call?

**Comment by mhmerrill** [comment]
> I agree that it makes the most sense to have a couple of pre-defined predicates to start.
> 
> For extending to arbitrary expressions, one option would be to embed a python interpreter, which looks pretty straightforward: https://docs.python.org/3.8/extending/embedding.html. If the speed of the where clause evaluation is important you might need to go down the compiled route, but compiling and dynamically loading an expression seems like it'll be a lot more complicated.

I have a prototype lisp expression interpreter which allows for evaluation in a `forall` across parallel array elements. I'm still not satisfied with the approach to **linkage** with chapel program variables.
https://github.com/mhmerrill/arkouda/blob/LisExpr-toy/toys/LisExpr.chpl

> 
> Implementing the join with `idx = fetch-and-increment(results-found)` will introduce a comm bottleneck. That will be very slow for non-ugni configs, but even under ugni where remote atomics are fast that will probably be a bottleneck. You'll probably want to batch locally and reserve a bunch of indices at once.

I am planning to batch locally, say 100 or 1000 at a time and `fetch-and-add` instead.

> 
> Do the results need to be deterministic or is it ok if the results differ from call to call?

I have not promised determinism in the results just promised correct results ;-)

**Comment by mhmerrill** [comment]
initial implementation in PR #270

**Comment by mhmerrill** [comment]
i'm going to close this. i'm thinking of moving the join module into arkouda-contrib.
