### ISSUE TITLE
maxTransferBytes not effective

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2177]
**Describe the bug**

Cannot create arkouda pdarray from np.ndarray

RuntimeError: Array exceeds allowed transfer size. Increase ak.maxTransferBytes to allow

(in arkouda/v2023.02.08/arkouda/pdarraycreation.py in array(a, dtype, max_bits)

setting ak.maxTransferBytes to very large number and running the following still results in same RuntimeError.

`
if ak.maxTranferBytes > p.size * p.itemsize:
    ps = ak.array(p)
`

**To Reproduce**

**Expected behavior**

**Error Message**

**Is this a Blocking Issue**
Yes

**Additional context**
Attempted bypass issue by making single column pandas dataframe and transfering data using .from_pandas() but receive the same error.

**Comment by ronawho** [comment]
How are you setting `maxTransferBytes`? Based on my only experience with this (from the transfer benchmark added in ee242d389ee0cbc59c10f0790b4a5f8d18ecd201) I think it's `ak.client.maxTransferBytes  = <value>` and not just `ak.maxTransferBytes = <value>`

If that's true, then probably the error message should be updated

**Comment by pierce314159** [comment]
Yeah I just saw the same thing. We should 100% update the error message but this means the workaround for you @21771 should be very straightforward. You just need to updated `ak.client.maxTransferBytes`

**Comment by 21771** [comment]
Thanks! I'll use the workaround tomorrow. Really appreciate the quick response.

**Comment by 21771** [comment]
Confirming that assignment of ak.client.maxTransferBytes resolved the issue. (As expected). Thanks again!
