### ISSUE TITLE
`ak.coargsort` unexpected behavior with empty Strings arrays

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2240]
When `ak.coargsort` is run against a `Strings` array that is empty, it attempts to return an array of zeros. This is an issue because it passes the `dtype` of the strings array through, but `ak.zeros` expects a numeric dtype.

The chances of this actually occurring are slim (I found it running a benchmark with a problem size that was too small). 

This should be a fairly simple fix. Simply add a return case for `size==0 and dtype=="str"`, that does not error.

**Comment by pierce314159** [comment]
This also needs to be fixed for empty categoricals
Reproducer:
```python
>>> empty_str = ak.random_strings_uniform(1, 16, 0)
>>> empty_cat = ak.Categorical(empty_str)
>>> empty_pda = ak.array([], int)
>>> ak.coargsort([empty_pda])
array([])

>>> ak.coargsort([empty_str])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/proj/arkouda/arkouda/sorting.py:162, in coargsort(arrays, algorithm)

TypeError: unsupported dtype <U0

In [8]: ak.coargsort([empty_cat])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/proj/arkouda/arkouda/sorting.py:162, in coargsort(arrays, algorithm)

TypeError: unsupported dtype <U0
```
