### ISSUE TITLE
v.2023.03.01 issue with large segarray

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2263]
**Describe the bug**
Some large dataframes which include segarrays cannot be read in if saved with v.2023.03.01. If files containing the same internal data are created using v.2023.02.08 then the files can be read into either of these versions.

Reading with v.2023.03.01
-- results in server appearing to hang. No error messages are produced, Just no new lines are written to log and command doesn't complete. Server must be killed manually. It won't accept connections. (Normal "busy server" behavior)

Reading with v.2023.02.08 
-- results in the following error lines
RuntimeError
/proj/HPDA/software/arkouda/v2023.02.08/arkouda/io.py in load(path_prefix, file_format, dataset, calc_string_offsets)  line 1366

RuntimeError: Other error in accessing file <filepath>: Error 1661 HDF5Msg:get_info in get_info illegal argument 'bad cast from int '3' to enum 'ObjType': '

Related specifically to segarrays
Files can be read using ak.read(<filepath*>,datasets=<column_list_excluding_segarrays>) using either version.

Also, appears to be size specific. Writing out data frames in 1M record slices with v.2023.03.01 results in files that can each be read back in individually, but writing out 50M record slice creates file that cannot be read back in.

**To Reproduce**
have not been able to reproduce the behavior in simple fashion

**Expected behavior**

**Error Message**
If you are receiving any error messages, please provide them here.

**Is this a Blocking Issue**
Falling back to v.2023.02.08 is the only known workaround

**`ak.get_config()` Output**
Providing the output of `ak.get_config()` provides crucial debugging information.

**Additional context**

**Comment by Ethan-DeBandi99** [comment]
Dug into this some yesterday with @pierce314159. It looks like changes to `fixupSegBoundaries` were causing the issue. I added some timers to verify. I also wanted to note that this will impact `SegArray` on their own as well as `Strings`. Running with a SegArray configured as below and 4 locales, I identified that `fixupSegBoundaries` was in fact the cause of the slowness.
```
val = ak.arange(10**6)
idx = ak.arange(0, 10**6, 5)

s = ak.SegArray.from_parts(idx, val)
```

With the timers in place, we get 30 seconds of run time with the existing code. I am working on a solution with better locality that should resolve this slow down.

**Comment by Ethan-DeBandi99** [comment]
Confirming that with the fix implemented, the execution time drops to 0 seconds for `fixupSegBoundaries`. I am confident that this was the issue because we were able to replicate the "hanging" of the server and that the issue appeared to worsen with larger problem sets.
