### ISSUE TITLE
Server crashes writing few rows of parquet strings

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2266]
**Describe the bug**
Arkouda server crashes when trying to write Parquet (HDF is OK) if there's more than one string column and fewer rows than the number of Arkouda locales.

**To Reproduce**
ak.DataFrame({ "blank1": ak.array([""]), "blank2": ak.array([""]) }).to_parquet("blank.parquet")  # when running on 2 or more nodes

**Expected behavior**

**Error Message**
From Server logs:
*** Caught a fatal signal (proc 2): SIGSEV(11)

**Is this a Blocking Issue**
No practical workaround.

**`ak.get_config()` Output**
Providing the output of `ak.get_config()` provides crucial debugging information.

**Additional context**
This issue comes up while working on ETL stuff and sometimes files are small.

**Comment by 21771** [comment]
Note: I'm submitting this bug for a colleague. I believe he should be able to use HDF5 output format until this is resolved.

**Comment by Ethan-DeBandi99** [comment]
@21771 - This was actually resolved with code added to the `Strings` case in PR #2210. I verified that it is functional for 1-4 nodes on my machine. This will be available in the next release (should be coming late this week or early next).

Closing Issue
