### ISSUE TITLE
Sporadic failures of Parquet `segarray_write` test with gasnet

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#2268]
**Describe the bug**
This failure:
```
        # bool with empty segments
        a = [0, 1, 1]
        c = [1, 0]
        s = ak.SegArray.from_parts(ak.array([0, 0, len(a), len(a), len(a), len(a) + len(c)]), ak.array(a + c,
                                   dtype=ak.bool))
        with tempfile.TemporaryDirectory(dir=ParquetTest.par_test_base_tmp) as tmp_dirname:
            s.to_parquet(f"{tmp_dirname}/int_test")

            rd_data = ak.read_parquet(f"{tmp_dirname}/int_test*")
            for i in range(6):
>               self.assertListEqual(s[i].tolist(), rd_data[i].tolist())
E               AssertionError: Lists differ: [False, True, True] != []
E
E               First list contains 3 additional elements.
E               First extra element 0:
E               False
E
E               - [False, True, True]
E               + []

tests/parquet_test.py:483: AssertionError
```
popped up on nightly testing. I am able to reproduce this issue on 16 locales, but it appears to only show up about once in every 100 trials.

**To Reproduce**

- Edit `pytest.ini` to run with 4 or more locales (not sure if this is necessary, but I couldn't reproduce with 2 locales, but could with 16; fairly confident anything 4 or over would work based on the type of failure and what we've seen here in the past)
- Modify `test_segarray_write` to run a large number of trials (I seem to catch this about 1 in every 100 runs)
- Run `python3 -m pytest tests/parquet_test.py -k "test_segarray_write"` to run just this test

**Comment by Ethan-DeBandi99** [comment]
I believe I located the issue causing this. While working Issue #2493, I discovered that there is an issue when a locale has no values being written. In `writeSegArrayComponent` in ParquetMsg.chpl, if the `localVals` variable has a size 0, there is an error.

**Comment by Ethan-DeBandi99** [comment]
Through testing I am able to replicate issue with 3 locales running this test. However, based on the error I am seeing it appears to be an allocation error. I am working to track this down, but it is proving rather tricky to locate.
