### ISSUE TITLE
SegArray Filters

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2295]
Ability to filter out values from a `SegArray`. The segments will need to be maintained. Thus, when values are removed the offsets will need to be adjusted appropriately. 

We will need to implement this with a `remove_empty` flag. This will default to `False`, but when set to `True` will remove any empty segments in the result of the filter.

**Comment by 21771** [comment]
Thank you. This will be very helpful.
