### ISSUE TITLE
File writes report success when directory does not exist

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2299]
It was reported that when attempting to write a file, success is reported in cases when the directory the file is being written to does not exist. This should check that the directory exists and raise an exception in the case that it does not.

The report was specific to Parquet files, but we should definitely also check/apply the same handling for HDF5.

I believe we should be able to do this check from the client.

**Comment by ronawho** [comment]
FYI that the client might not be running on a machine that has access to the server's filesystem (that's why we do things like implement something like `h5ls` on the server)

**Comment by Ethan-DeBandi99** [comment]
> FYI that the client might not be running on a machine that has access to the server's filesystem (that's why we do things like implement something like `h5ls` on the server)

Good point. Either way, I believe the check should be extremely simple to configure.

**Comment by Ethan-DeBandi99** [comment]
Tested this for HDF5. It does not report success, but fails during attempted creation. Error below:
```
RuntimeError: 1 errors: FileNotFoundError: No such file or directory (FileNotFoundError 191 HDF5Msg:coforall_fn The file /Users/ethandebandi/Documents/save_load_testing/no_dir/hdf_file_LOCALE0000 cannot be created)
```

**Comment by Ujustwaite** [comment]
```
files = glob('/some/path/read/hdf5/*'
df = ak.read(files)
[ak.to](http://ak.to/)_parquet(df, '/some/output/path/that/does/not/exist/prefix')
```
Outputs:
`wrote array to file`

**Comment by Ethan-DeBandi99** [comment]
@Ujustwaite - Thanks for the reproducer. I am able to replicate what you are seeing now.

**Comment by Ethan-DeBandi99** [comment]
@Ujustwaite - Thanks for the reproducer. I am able to replicate what you are seeing now.

**Comment by Ujustwaite** [comment]
Awesome. No sweat.
