### ISSUE TITLE
`Datetime.date` scaling issue

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2306]
**Feature Description**
DateTime.date does not appear to scale particularly well. Suggest examining whether implementing it in a more direct manner could help.

**Example Behavior**
```
first = pd.to_datetime('1970-01-01')
last = pd.to_datetime('2023-03-27')
for i in range(8):
    size = 10**i
    aktimestamps = ak.Datetime(ak.randint(first.value,last.value,size))
    timer1 = pd.Timestamp.now()
    a = aktimestamps.date
    timer2 = pd.Timestamp.now()
    b = ak.Datetime(aktimestamps.values - aktimestamps.values % (24 * 3600 * 10**9))
    timer3 = pd.Timestamp.now()

    print((a==b).all())

    print(size, timer2-timer1, timer3-timer2)
```

**Describe Workarounds**
roll-your-own date function shown above

**Additional context**

**Comment by pierce314159** [comment]
Hmmm it seems this is just a wrapper for `dt.floor('d')`, which is essentially implemented by doing 
```python
f = 24 * 3600 * 10**9
ak.Datetime(dt.values // f, unit='d')
```

so implementing this way could improve the performance of `floor` for free if we changed it to 
```python
f = 24 * 3600 * 10**9
ak.Datetime(dt.values - dt.values % f, unit='d')
```

**Comment by pierce314159** [comment]
Oh never mind, the existing way is actually faster (doing the `//`), but it's preceded by an expensive `_ensure_components()` call to calculate all the server components in one go. But it isn't actually need for `date`, so this just removing that should do the trick

**Comment by pierce314159** [comment]
After removing the unnecessary `_ensure_components` im seeing slightly better performance from `.date` than the proposed method with gasnet enabled locally (oversubscribed with 2 locales, this is without runtime optimizations)
```python
In [3]: def date_test(i):
   ...:     import pandas as pd
   ...:     first = pd.to_datetime('1970-01-01')
   ...:     last = pd.to_datetime('2023-03-27')
   ...:     size = 10**i
   ...:     aktimestamps = ak.Datetime(ak.randint(first.value,last.value,size))
   ...:     timer1 = pd.Timestamp.now()
   ...:     a = aktimestamps.date
   ...:     timer2 = pd.Timestamp.now()
   ...:     b = ak.Datetime(aktimestamps.values - aktimestamps.values % (24 * 3600 * 10**9))
   ...:     timer3 = pd.Timestamp.now()
   ...: 
   ...:     print((a==b).all())
   ...:     print(size, timer2-timer1, timer3-timer2)
   ...: 

In [4]: date_test(8)
True
100000000 0 days 00:00:04.017719 0 days 00:00:06.341203
```

So I think this should resolve the poor scaling you were seeing for `.date`. However it may be worthwhile to look into the datetime components to see where the bottle neck is

**Comment by 21771** [comment]
Looks great. Thanks! I wasn't sure what _ensure_components() did, but it didn't seem directly needed for the date() call.
