### ISSUE TITLE
Evaluate impact of bulk transfer on compilation times with 1.30

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#2311]
We disabled bulk transfer for quick compile in https://github.com/Bears-R-Us/arkouda/pull/2090 since it resulted in a non-trivial speedup for gasnet compilation times with Chapel 1.29. Chapel 1.30 has significantly improved compilation times though and it's not clear to me how much it still helps and it has a substantial impact on execution time, which can make initial perf debugging more complicated if you forget to disable quick compile.

If the impact on compilation time is minor with 1.30 I'd suggest we stop disabling bulk transfer.

Related to suggestion to use bulk transfer in https://github.com/Bears-R-Us/arkouda/pull/2310

**Comment by Ethan-DeBandi99** [comment]
I am in agreement with @bmcdonald3 - I think it would be good to reenable.
