### ISSUE TITLE
Wrap `corrMsg` in `try except`

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#2344]
We need to wrap `corrHelper` call in `corrMsg` in `StatsMsg.chpl` in a `try except` block. I think this is the only spot but we should check that there are no other other places in `StatsMsg` where we could raise an error without passing back a `MsgTuple(errorMsg, MsgType.ERROR)` to the client

**Comment by jaketrookman** [comment]
@Ethan-DeBandi99 The current implementation of the thrown error does not shut the server down and the error message on the server does not change, so this issue may need to be closed.
Discussed with @pierce314159

**Comment by Ethan-DeBandi99** [comment]
Spoke with @jaketrookman offline on this. I asked him to backtrace just to make sure we won't get caught in the future with the error not being handled properly. I don't think its an issue, but would rather be sure we know why it is handled properly now. Once that is documented, we can close the issue.

**Comment by jaketrookman** [comment]
After making the requested changes, everything is exactly the same on the client side. On the server side there is only one difference. There is an extra error logged through `ServerDaemon.chpl`.
` [ServerDaemon] run Line 710 ERROR [Chapel] <<< corr resulted in error: Error: corrHelper: unrecognized type: (bigint,int64) in 0.000865936279296875 sec `
After talking with @Ethan-DeBandi99 , we believe that the current implementation of Chapel handles this well and we do not need to make the change.
