### ISSUE TITLE
README.md broken links

### ISSUE THREAD

**Issue by bradcray** [Bears-R-Us/arkouda#2347]
**Describe the bug**

The links to [INSTALL.md](https://github.com/Bears-R-Us/arkouda/blob/master/pydoc/setup/INSTALL.md) and [BUILD.md](https://github.com/Bears-R-Us/arkouda/blob/master/BUILD.md) in Arkouda's README.md are broken.

**To Reproduce**
1. Go to https://github.com/Bears-R-Us/arkouda/
2. Scroll down to the `INSTALL.md` or `BUILD.md` links
3. Click on either `INSTALL.md` or `BUILD.md`
4. See 404 error page

**Expected behavior**
I was expecting these to take me to the installation / build instructions.

**Error Message**
I got a GitHub-style 404 error page

**Is this a Blocking Issue**
No.  I suspect the files have been renamed or reconfigured, but didn't go looking for them (I was just trying to reproduce another user's steps when I stumbled across this).

**`ak.get_config()` Output**
N/A

**Comment by Ethan-DeBandi99** [comment]
@bradcray - thanks for pointing this out. We moved most of these into our github pages instead of maintaining 2 copies. I guess we missed the links. We will get them updated.
