### ISSUE TITLE
Bug Removing IPv4 from DataFrame Columns by .values()

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2348]
**Describe the bug**
df['col'].values returns valid pdarray of uint64, but 
executing df['col'] = df['col'].values on data causes errors

**To Reproduce**
'''
df=ak.DataFrame({  ''ip":ak.IPv4(ak.arange(10)) })

df.save('foo')
'''

**Expected behavior**
Expect IPv4 dtype/wrapper to be removed and leave a column of ak.uint64 values.

**Error Message**
For Save: RuntimeError: Unknown SymbolError line 244 In MultiTypeSymbollTable.checkTable: Error: lookup: unknown symbol: <id>
For print: RuntimeError: Expected 80 bytes but received 178

**Is this a Blocking Issue**
No: Easy workaround with:
df['col'] = ak.cast(df['col'],ak.uint64)

**`ak.get_config()` Output**

**Additional context**

**Comment by Ethan-DeBandi99** [comment]
@21771 - just for awareness, `df.save` is deprecated and will be removed in a future release. It would be better to use `ak.to_parquet` or `ak.to_hdf`

**Comment by 21771** [comment]
Thanks for the reminder

**Comment by Ethan-DeBandi99** [comment]
Looking at this, it appears that garbage collection is running because the `IPv4` object is dereferenced (since it is being removed) and this is resulting in the associated `.values` pdarray being removed from the Symbol Table. This would also explain why `ak.cast(df['col'].values, ak.uint64)` works because it generates a new pdarray.

**Comment by Ethan-DeBandi99** [comment]
A possible solution to this would be to update `IPv4.values` to `IPv4._values` and add a property definition so that calling `IPv4.values` will simply return `ak.cast(IPv4.values, ak.uint64)`. The only issue here is then we are creating a new array in cases when we may want to only reference the existing.

**Comment by Ethan-DeBandi99** [comment]
I chatted with @hokiegeek2 about this a bit. We both have the same concern with setting up `.values` to also return essentially a copy of the pdarray via a property function. The better avenue here would be to go the route of adding an `IPv4.export_uint()` function that would return the new array. This prevents `.values` from always returning a copy of the array (which could cause other issues), but allows the desired functionality in this case. The workflow would change to 

```python
df['col'] = df['col'].export_uint()
```

@21771 - would this be an acceptable solution for you?

**Comment by 21771** [comment]
Unless there's another need for that additional functionality, then:

'''
df['col'] = ak.cast(df['col'],ak.uint64)
'''

works fine for me -- unless there are other issues you're aware of. We'll
just need to be aware of the limitation for .values.
This issue just surfaced because of the problems saving IPv4 columns and
needing to save just the underlying uint64s.

Also (unrelated), I noticed that when a DataFrame is created from a
dictionary, adding columns to the DataFrame adds keys to the originating
dictionary. That continued linkage was a surprise to me. Is that
intentional? I had expected only the underlying arrays to be the same.

**Comment by Ethan-DeBandi99** [comment]
@21771 
I see no harm in adding it, so its in there and the PR is up. If it gets used, great. If not, no harm done. The saving issues should also be fully resolved and will be released tomorrow.

In response to the underlying linkage. I can't say it totally surprised by it, but I also would not expect/prefer that. If that is causing a problem for you, go ahead and put up an issue and I will start looking into it.
