### ISSUE TITLE
Inconsistent percent mem used

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#2414]
In different places of the logs the percent of memory used number can vary (see examples below where one is `80%` and the other is `4%`. We should update these to match
```
[ServerDaemon] run line XXX INFO [Chapel] bytes of memory <a large number> used after binopsv command is 80% of max memory <a bigger large number>
...
[ServerConfig] overMemLimit Line XXX INFO [Chapel] memory high water mark <a large number> memory limit <a bigger large number> percentage used = 4%
```

**Comment by pierce314159** [comment]
The user who encountered this thinks the per command number is correct and the overMemLimit check is off, but we should validate that's the case

**Comment by hokiegeek2** [comment]
@pierce314159 on it now

**Comment by hokiegeek2** [comment]
@pierce314159 okay, I see what's going on. Only the denominator is multiplied by the numLocales in calculating the pct used.

![image](https://github.com/Bears-R-Us/arkouda/assets/10785153/970a36c2-6ac1-4d98-a8ab-0f28711592f8)

**Comment by hokiegeek2** [comment]
@21771 @pierce314159 got it fixed:

![image](https://github.com/Bears-R-Us/arkouda/assets/10785153/776e8fd1-ec81-4d90-a194-39f0919382ed)

**Comment by hokiegeek2** [comment]
reformatted error message with project pct memory used:

![image](https://github.com/Bears-R-Us/arkouda/assets/10785153/e2ebc03c-889a-4149-ad8d-e0fe4b635bd6)
