### ISSUE TITLE
Allow dataframe rows to contain lists of strings (i.e. segarray or similar)

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2424]
**Feature Description**
Allow dataframe rows to contain lists of strings (i.e. segarray or similar). Either arkouda strings or categorical representation underneath not as important as being able to represent lists of text.

**Example Behavior**
```python
language = ak.array(['english','spanish'])
words = ak.array(['one,two,three','uno,dos,tres'])
strs, segs = words.split(',', return_segments=True)
```

### would like something like this to work and be supported in dataframes
```python
x = ak.segarray(segs, strs)
df = ak.DataFrame({'language':language, 'examples': x })
```

**Describe Workarounds**
none to my knowledge

**Additional context**
Part of request to have general import/export of lists from/to pandas.

**Comment by Ethan-DeBandi99** [comment]
In order to add this functionality, we are going to need to make some major changes to SegArray. These will be handled in issue #2432. Once that the code resolving that issue is merged, this can be worked.

**Comment by Ethan-DeBandi99** [comment]
I have most of the functionality working for this. I just need to verify a few things for set operations before posting a PR.
