### ISSUE TITLE
Import/Export lists from/to pandas

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2425]
**Feature Description**
Export segarrays to pandas as a list and import columns containing lists as segarrays

**Comment by Ethan-DeBandi99** [comment]
@21771 - the exporting to Pandas should be functional if you have an Arkouda DataFrame. For example, 

```python
adf = ak.DataFrame({
    "sa": ak.SegArray.from_parts(ak.arange(0, 10, 2), ak.arange(10))
})
print(adf.__repr__())
print(adf.to_pandas())
```
should output

```python
# arkouda dataframe
      sa
0  [0, 1]
1  [2, 3]
2  [4, 5]
3  [6, 7]
4  [8, 9] (5 rows x 1 columns)

# pandas dataframe
       sa
0  [0, 1]
1  [2, 3]
2  [4, 5]
3  [6, 7]
4  [8, 9]
```

However, creating an Arkouda DataFrame is not currently functional with list columns so I will make sure to implement that. A SegArray can be created from a list using `ak.SegArray.from_multi_array`. So this should be simple enough to add for DataFrame.

**Comment by 21771** [comment]
Awesome. Thanks!
