### ISSUE TITLE
Bigint groupby test failing in multi locale configurations

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#2449]
The newly added `test_broadcast_bigints` in `groupby_test.py` from https://github.com/Bears-R-Us/arkouda/pull/2437 is failing with:
```
/arkouda//src/Broadcast.chpl:116: error: halt reached - The source locale ID (361805184) for Communication.get is out of bounds.
/arkouda//src/Broadcast.chpl:116: error: halt reached - The source locale ID (361805184) for Communication.get is out of bounds.
```
Which is this line:
```
res.max_bits = vals.max_bits;
```

**To Reproduce**
I was able to reproduce this failure on my mac by running a 2 locale server and then running the test with the command `ARKOUDA_RUNNING_MODE=CLIENT python3 -m pytest tests/groupby_test.py -k "test_broadcast_bigints"`. The minimal modules required to run this test are:
```
IndexingMsg
BigIntMsg
SequenceMsg
RandMsg
BroadcastMsg
ReductionMsg
GroupByMsg
CastMsg
OperatorMsg
```

Also, I ran with `ARKOUDA_RUNTIME_CHECKS=1` to get a helpful error message (you will just get a message saying gasnet error if you run with runtime checks enabled).

**Error Message**
```
/arkouda//src/Broadcast.chpl:116: error: halt reached - The source locale ID (361805184) for Communication.get is out of bounds.
/arkouda//src/Broadcast.chpl:116: error: halt reached - The source locale ID (361805184) for Communication.get is out of bounds.
```

**Additional context**
This fails in all distributed runs.

**Comment by pierce314159** [comment]
Oh actually. That seems to be `line 116` of `BroadcastMsg.chpl`, but it looks like the error is referencing `line 116` of `Broadcast.chpl`, which would be this
https://github.com/Bears-R-Us/arkouda/blob/9449193c681c0dc558ce98ed0ceaec3c84b49865/src/Broadcast.chpl#L116
and that seems like a more likely place to have a multilocale error

**Comment by pierce314159** [comment]
before i start digging into this too much, @bmcdonald3 do u happen to know off hand if `+ scan` is supported on `bigint` arrays? I have def been operating under the assumption that it does. It's possible it's just doing the operation in place is causing problems and if i create a new array to store the result it'd be fine

**Comment by bmcdonald3** [comment]
```chpl
use BigInteger;
use BlockDist;

var a = Block.createArray({1..10}, bigint);
a = 5:bigint;

var res = + scan a;
```
With this small reproducer, I am getting a crash, so it does not look like `+ scan` works on bigint arrays.

**Comment by pierce314159** [comment]
oh interesting! That reproducer seems to work just fine for me, so maybe it's good in chpl 1.30 and not chpl main?
```chapel
use BigInteger;
use BlockDist;

var a = Block.createArray({1..10}, bigint);
a = 5:bigint;

var res = + scan a;
writeln(res);
```
```
% chpl PlayingAround.chpl -o playing
% ./playing                         
5 10 15 20 25 30 35 40 45 50
```

**Comment by bmcdonald3** [comment]
Yes, thank you for reminding me!
