### ISSUE TITLE
`SegArray.__getitem__` Returns `ndarray`. Should It?

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2454]
@pierce314159 and I have had sever discussions about this, but I wanted to post a question about this to everyone. Feedback is appreciated.

Currently, `SegArray.__getitem__` returns an `ndarray`. This has always seemed a bit odd, but I want to make sure that any existing workflows are not relying on this. I would like to update this to return a `pdarray` if there are no objections.

**Comment by JamesPerreault** [comment]
I was thinking maybe some sort of wrapped ndarray, that could be converted to a (also wrapped) pdarray,

**Comment by pierce314159** [comment]
> I was thinking maybe some sort of wrapped ndarray, that could be converted to a (also wrapped) pdarray,

hey @JamesPerreault, do u mind elaborating a bit. I'm not exactly sure what u mean by a wrapped ndarray. As it stands today, `SegArray.__getitem__` functions like the below
```python
>>> sa = ak.segarray(ak.array([0,3,6,9]), ak.array([0,1,2,3,4,5,0,1,2,5,5,5,5]))
>>> sa
SegArray([
[0 1 2]
[3 4 5]
[0 1 2]
[5 5 5 5]
])

>>> sa[3]
array([5, 5, 5, 5])

>>> type(sa[3])
numpy.ndarray
```
except for the `type(sa[3])` this is exactly what i would expect. But to me, each segment of segarray should a `pdarray`, i don't really know why we would dip back into numpy land (especially without a user explicitly saying that's what they want). You could imagine a case where a segment could be quite large and this automatic conversion to an `ndarray` could cause issues, for example
```
# construct a segarray where one segments is much larger than the others
>>> rand_vals = ak.randint(0, 10, 10**4 + 2)
>>> sa = ak.SegArray(ak.array([0, 1, 10**4 + 1]), rand_vals)
>>> sa
SegArray([
[2]
[1 3 1 ... 9 1 5]
[1]
])

>>> sa[1]
array([1, 3, 1, ..., 9, 1, 5])

# artificially lower `maxTransferBytes` (it's much easier to exceed the default on bigger machines than my laptop)
>>> ak.client.maxTransferBytes = 10**4
# now we can't view `sa` or index it since it tries to convert the pdarray to an ndarray first
>>> sa
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)

RuntimeError: Array exceeds allowed size for transfer. Increase client.maxTransferBytes to allow

>>> sa[1]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)

RuntimeError: Array exceeds allowed size for transfer. Increase client.maxTransferBytes to allow
```

if we update to return pdarray by default then users can still get the existing behavior, but they'll have to call `to_ndarray` themselves
```python
>>> rand_vals = ak.randint(0, 10, 10**4 + 2)
>>> sa = ak.SegArray(ak.array([0, 1, 10**4 + 1]), rand_vals)
>>> sa[1]
array([8 4 0 ... 2 8 9])

>>> type(sa[1])
arkouda.pdarrayclass.pdarray

# we can still get old behavior with an explicit to_ndarray() call
>>> sa[1].to_ndarray()
array([8, 4, 0, ..., 2, 8, 9])

>>> type(sa[1].to_ndarray())
numpy.ndarray

# but now we don't have to worry about large segments causing unexpected errors
>>> ak.client.maxTransferBytes = 10**4
>>> sa
SegArray([
[3]
[8 4 0 ... 2 8 9]
[7]
])

>>> sa[1]
array([8 4 0 ... 2 8 9])
```

**Comment by Ethan-DeBandi99** [comment]
I got some feedback from users that returning a pdarray instead of an ndarray should not be an issue.

**Comment by JamesPerreault** [comment]
I was thinking that there may be cases where the SeqArray item is too large to be a Pandas array (or at least large enough that it might be preferable to leave as a ndarray).  A wrapped ndarray is probably not be necessary.   For some background on my use case, I am writing code that has an abstraction layer so that either Arkouda or Pandas DataFrames can be used, and the part of the code where SeqArrays appear needs some work.  They arise when you do a groupby().unique()
