### ISSUE TITLE
05.05 unable to load saved dataframes from previous versions containing Categorical types

### ISSUE THREAD

**Issue by Ujustwaite** [Bears-R-Us/arkouda#2506]
Dataframes saved to disk with ak.DataFrame.to_hdf() with Arkouda versions earlier than 05.05 AND containing ak.Categorical types are unable to be loaded by version 05.05. This issue appears to result from arkouda/io.py in the _dict_recombine_segarrays_categoricals() function that expects all categoricals to have the .permutation key set. 

KeyError: 'appIP_ipowner.permutation'

Attempted to workaround by reloading each dataset individually and reconstructing the dataframe, which almost works, but causes a journey into the layers of inception to figure out what codes actually go with what categories and reconstructing the NA value appropriately. 

Dataframes saved from and loaded into version 05.05 seem to work fine and this appears to only be a backward compatibility issue. I'm assuming this relates to segarray implementations in 05.05, but the on disk storage of the arrays also appears different as 05.05 does not appear to create the ._akNAcode, .categories, and .codes files as before. 

If possible, would like backwards compatibility to allow users to load existing stored dataframes.

**Comment by Ethan-DeBandi99** [comment]
@Ujustwaite - Just want to confirm that you are having issues when a Categorical does not have a `permutation` assigned to it. I ran a few quick tests and everything appears functional (saving in v2023.04.07 and loading in v2023.05.05) with the exception of that case. I will implement the fix and be sure it is in the next release.
