### ISSUE TITLE
Merge `ObjType` and `ObjectType` enums

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#2522]
We got 2 different enums for object types. One used primarily for message / parameter objects and the other used for file IO / most select statements. We should dig into this to see if these can be merged into one thing

**Comment by Ethan-DeBandi99** [comment]
Its worth noting here that these do vary slightly. The `ObjType` enum is strictly for Arkouda objects. The `ObjectType` enum used by the message parameter parser also includes values for Scalar and JSON. I am not positive that merging these is the right course of action based on their intended purpose. It may be more beneficial to rename `ObjectType` to `ParameterType` or something of that nature.

**Comment by pierce314159** [comment]
Okay the rename is seems fine to me!
