### ISSUE TITLE
`io_test.py`/`parquet_test.py`/`import_export_test.py` conversion for new test framework

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2539]
Convert `io_test.py`, `parquet_test.py` and `import_export_test.py` to work in the new framework.

- This should be done as 1 file with 3 classes: `HDF5Test`, `ParquetTest`, `CSVTest`, and `ImportExportTest`. 
- Ensure that all dtypes supported are being tested
- Update tests to allow for variable/dynamic problem sizes to ensure we are testing different cases. This seems to be the one area where the distribution of arrays has a massive impact on proper functionality.

Breaking this up into three separate issues to avoid PRs being too long and reviews suffering
- [x] #2585
- [x] #2602
- [x] #2624

**Comment by pierce314159** [comment]
closing since all the underlying issues have been resolved
