### ISSUE TITLE
`ak.GroupBy` fails for single limb `BigInt`

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2553]
While working issue #2547, it was discovered that when a `ak.bigint` `pdarray` contains values with only a single limb, the `ak.GroupBy` call during processing of `in1d` will fail. 

The issue is in the code here:
```python
 if nkeys == 1:
     unique_keys = pda[unique_key_indices]
```
In this case, a list is being indexed by a pdarray which is not defined behavior.

In order to resolve this, we need to update to
```python
 if nkeys == 1 and not isinstance(pda, Sequence):
     unique_keys = pda[unique_key_indices]
```
This will push processing to the else case where it can handle lists and tuples of pdarrays.

**Comment by pierce314159** [comment]
Closed by #2556
