### ISSUE TITLE
`SegArray` SetOps incorrect ordering for `Strings` Values

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2665]
While updating the SegArray testing for the new framework, I discovered that SetOps on `Strings` value SegArrays do not properly order the results. This makes it somewhat difficult to test properly and is inconsistent with our other set operations. For the time being, I left out the `Strings` case from the new testing, but this will need to be addressed. There is a note in the new test file to update when this is corrected.

**Comment by pierce314159** [comment]
I imagine this is due to sorts / uniques on strings being a grouping rather than lexicographical sort. This is captured in https://github.com/Bears-R-Us/arkouda/issues/1348
