### ISSUE TITLE
Server crashes reading CSV file with missing values 

### ISSUE THREAD

**Issue by alvaradoo** [Bears-R-Us/arkouda#2804]
**Describe the bug**
Reading in a CSV file with the Arkouda `read_csv` method causes the server to shutdown or return a non-descriptive error message if some column data is missing for some of the rows in the CSV file. 

There are two possible outcomes.
1. The server shuts down with a `Caught a fatal signal (proc 0): SIGSEGV(11)` error.
2. The server does not shut down but the user gets a `RuntimeError: 0 errors:` message in Python with accompanying server message: `run Line 720 ERROR [Chapel] <<< readcsv resulted in error: 0 errors:`.

**To Reproduce**
Run the Python code below and attempt to read in a CSV file with at least one missing "cell".

Code:
```Python
nodes_df = ak.read_csv("path/to/nodes.csv")
```

File:
```
**HEADER**
int64,str,int64,str,str
*/HEADER/*
vertex,name,born,brand,model
34,Ann,1990,,
69,Dan,1975,,
89,,,Tesla,Model X
89,,,Tesla,Model X
```

**Expected behavior**
Have the server not shut down and return a descriptive message to the user saying empty cells in CSV files are not currently accepted, or load in the data with `NaN`s or empty cells.

**Error Message**
Provided in error description above.

**Is this a Blocking Issue**
The only work-around I came up with was loading in placeholder data for the cells. This would probably not be feasible for larger CSV files. 

Example:
```
**HEADER**
int64,str,int64,str,str
*/HEADER/*
vertex,name,born,brand,model
34,Ann,1990,X,X
69,Dan,1975,X,X
89,X,0,Tesla,Model X
89,X,0,Tesla,Model X
```

**`ak.get_config()` Output**
Providing the output of `ak.get_config()` provides crucial debugging information.
```
{'arkoudaVersion': 'v2023.09.06', 'chplVersion': '1.32.0', 'ZMQVersion': '4.3.4', 'HDF5Version': '1.12.2', 'serverHostname': 'n61.cluster.local', 'ServerPort': 5555, 'numLocales': 2, 'numPUs': 128, 'maxTaskPar': 128, 'physicalMemory': 549739035728, 'distributionType': 'BlockDom(1,int(64),one,unmanaged DefaultDist)', 'LocaleConfigs': [{'id': 0, 'name': 'n61.cluster.local', 'numPUs': 128, 'maxTaskPar': 128, 'physicalMemory': 549739035728}, {'id': 1, 'name': 'n62.cluster.local', 'numPUs': 128, 'maxTaskPar': 128, 'physicalMemory': 549739035728}], 'authenticate': False, 'logLevel': 'INFO', 'logChannel': 'CONSOLE', 'regexMaxCaptures': 20, 'byteorder': 'little', 'autoShutdown': False, 'serverInfoNoSplash': False}
```

**Additional context**
None.

**Comment by pierce314159** [comment]
Without gasnet enabled, I see the following error:
```chapel
In [3]: ak.read_csv("empty_test.csv")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 ak.read_csv("empty_test.csv")

File ~/proj/arkouda/arkouda/io.py:995, in read_csv(filenames, datasets, column_delim, allow_errors)
    992 elif datasets is None:
    993     datasets = get_columns(filenames, col_delim=column_delim, allow_errors=allow_errors)
--> 995 rep_msg = generic_msg(
    996     cmd="readcsv",
    997     args={
    998         "filenames": filenames,
    999         "nfiles": len(filenames),
   1000         "datasets": datasets,
   1001         "num_dsets": len(datasets),
   1002         "col_delim": column_delim,
   1003         "allow_errors": allow_errors,
   1004     },
   1005 )
   1006 rep = json.loads(rep_msg)  # See GenSymIO._buildReadAllMsgJson for json structure
   1007 _parse_errors(rep, allow_errors)

File ~/proj/arkouda/arkouda/client.py:970, in generic_msg(cmd, args, payload, send_binary, recv_binary)
    968     else:
    969         assert payload is None
--> 970         return cast(Channel, channel).send_string_message(cmd=cmd, args=msg_args,
    971                                                           size=size, recv_binary=recv_binary)
    972 except KeyboardInterrupt as e:
    973     # if the user interrupts during command execution, the socket gets out
    974     # of sync reset the socket before raising the interrupt exception
    975     cast(Channel, channel).connect(timeout=0)

File ~/proj/arkouda/arkouda/client.py:503, in ZmqChannel.send_string_message(self, cmd, recv_binary, args, size, request_id)
    501 # raise errors or warnings sent back from the server
    502 if return_message.msgType == MessageType.ERROR:
--> 503     raise RuntimeError(return_message.msg)
    504 elif return_message.msgType == MessageType.WARNING:
    505     warnings.warn(return_message.msg)

RuntimeError: 2 errors: IllegalArgumentError: bad cast from empty string to int(64) ... IllegalArgumentError: bad cast from empty string to int(64)
```
So it's attempting to cast the empty string to an `int64` in the third column. This makes sense and hopefully won't be hard to fix. I'm building with gasnet and the developer flags set now

**Comment by pierce314159** [comment]
@alvaradoo, im digging into this. I'm not sure what the expected behavior should be when you have an empty cell in an integer column since there isn't a `nan` value for integers in arkouda. Do you have any idea of what you would like to see here?

**Comment by pierce314159** [comment]
I did a quick implementation of the method I suggested and this is what the error and resulting read looks like:
```python
In [3]: ak.read_csv("empty_test.csv")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 ak.read_csv("empty_test.csv")

File ~/proj/arkouda/arkouda/io.py:995, in read_csv(filenames, datasets, column_delim, allow_errors)
    992 elif datasets is None:
    993     datasets = get_columns(filenames, col_delim=column_delim, allow_errors=allow_errors)
--> 995 rep_msg = generic_msg(
    996     cmd="readcsv",
    997     args={
    998         "filenames": filenames,
    999         "nfiles": len(filenames),
   1000         "datasets": datasets,
   1001         "num_dsets": len(datasets),
   1002         "col_delim": column_delim,
   1003         "allow_errors": allow_errors,
   1004     },
   1005 )
   1006 rep = json.loads(rep_msg)  # See GenSymIO._buildReadAllMsgJson for json structure
   1007 _parse_errors(rep, allow_errors)

File ~/proj/arkouda/arkouda/client.py:970, in generic_msg(cmd, args, payload, send_binary, recv_binary)
    968     else:
    969         assert payload is None
--> 970         return cast(Channel, channel).send_string_message(cmd=cmd, args=msg_args,
    971                                                           size=size, recv_binary=recv_binary)
    972 except KeyboardInterrupt as e:
    973     # if the user interrupts during command execution, the socket gets out
    974     # of sync reset the socket before raising the interrupt exception
    975     cast(Channel, channel).connect(timeout=0)

File ~/proj/arkouda/arkouda/client.py:503, in ZmqChannel.send_string_message(self, cmd, recv_binary, args, size, request_id)
    501 # raise errors or warnings sent back from the server
    502 if return_message.msgType == MessageType.ERROR:
--> 503     raise RuntimeError(return_message.msg)
    504 elif return_message.msgType == MessageType.WARNING:
    505     warnings.warn(return_message.msg)

RuntimeError: 2 errors: Error: IOError 374 CSVMsg:coforall_fn This CSV is missing values. To read anyway and replace these with min(col_dtype), set allow_errors to True ... Error: IOError 374 CSVMsg:coforall_fn This CSV is missing values. To read anyway and replace these with min(col_dtype), set allow_errors to True

In [4]: ak.read_csv("empty_test.csv", allow_errors=True)
Out[4]:
{'vertex': array([34 69 89 89]),
 'name': array(['Ann', 'Dan', '', '']),
 'born': array([1990 1975 -9223372036854775808 -9223372036854775808]),
 'brand': array(['', '', 'Tesla', 'Tesla']),
 'model': array(['', '', 'Model X', 'Model X'])}
```

**Comment by alvaradoo** [comment]
@pierce314159 I think erroring unless `allow_errors` is set and populating with `NaT` sounds like the best solution. I did some digging and it seems like [Pandas](https://pandas.pydata.org/docs/user_guide/missing_data.html#integer-dtypes-and-missing-data) casts the read column with missing values to float and assigns `NaN` for the missing values. However, directly in the following section they talk about `NaT`s for datetimes. Seems like more natural to not do a cast and just assign missing integer values with `NaT`s.

**Comment by pierce314159** [comment]
i had also thought about that, but it seemed weird if the file had explicitly been written with the column dtype to be `int64` to then cast that to a `float`. But if that's what pandas does, then it might be the best solution for us

**Comment by alvaradoo** [comment]
If we do go the route of casting the column from `int64` to `float` then maybe a warning could be printed out to the user saying something like "missing values detected, column converted to `float` and missing items set as `Nan`s".

**Comment by pierce314159** [comment]
Yah, the casting to float is in line with what @egelberg was looking into doing for the merge functionality as well. I think that's prob the right thing to do, but I might hold off for this initial bug fix and try to think about other places that casting would make sense. I agree that we'd need to communicate to the user that a cast to float took place due to missing values

**Comment by pierce314159** [comment]
Just an update on this, everything looks good with comm=none, but this is currently hung up on a weird issue in multi-locale where chapel is unable to recognize the type of an error if it's thrown within a coforall

**Comment by pierce314159** [comment]
okay i just got it fixed. Just for future reference, it was this error being thrown inside a `forall/coforall` that was causing the weird error message of `0 errors:` and the random `SIGSEGV(11)/SIGBUS(10)`s I was seeing. 

I got around this by having a boolean variable `hadError` to track if an error happened and doing a `with (| reduce hadError)` on the parallel loop. That allowed me to throw the error after the fact which preserved the error type and message. I should have a PR up for this by end of day
