### ISSUE TITLE
Install on MacOS/Python 3.11.5 fails

### ISSUE THREAD

**Issue by tofutofu** [Bears-R-Us/arkouda#2805]
**Describe the bug**
Install on MacOS (Ventura 13.5.2) for Python 3.11.5 currently fails because two dependencies fail to install.

**To Reproduce**
1. `conda create -n ark python=3.11`
2. `conda install cython`
3. `conda install .`

**Expected behavior**
```
pip install .
 ```
should succeed inside a new conda environment for Python 3.11.

**Error Message**
1. For tables: same stack trace as in https://github.com/PyTables/PyTables/issues/1040
2. For pyarrow:
```Building wheel for pyarrow (pyproject.toml) ... error
  error: subprocess-exited-with-error
  ...
  -- Running cmake for pyarrow
  ...
  -- Checking for module 'arrow'
     ...
      --   No package 'arrow' found
      CMake Error at /opt/homebrew/Cellar/cmake/3.27.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Arrow (missing: ARROW_INCLUDE_DIR ARROW_LIB_DIR
        ARROW_FULL_SO_VERSION ARROW_SO_VERSION)
      Call Stack (most recent call first):
        /opt/homebrew/Cellar/cmake/3.27.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        cmake_modules/FindArrow.cmake:450 (find_package_handle_standard_args)
        cmake_modules/FindArrowPython.cmake:46 (find_package)
        CMakeLists.txt:236 (find_package)
      
      -- Configuring incomplete, errors occurred!
      error: command '/opt/homebrew/bin/cmake' failed with exit code 1
      [end of output]
  ```

**Is this a Blocking Issue**
Work-around for tables install, see: https://github.com/PyTables/PyTables/issues/1040
```pip install git+https://github.com/PyTables/PyTables```

Work-around for pyarrow:
First run
```conda install pyarrow``` (installs pyarrow 11.0)
Then modify setup.py (no longer pinning to pyarrow==9.0.0)

I don't know if it's OK to unpin pyarrow, but this does make the `pip install` succeed.

**Comment by pierce314159** [comment]
Yeah [our CI is failing ](https://github.com/Bears-R-Us/arkouda/actions/runs/6421296595/job/17435712872?pr=2793)for seemingly the same reasons... With the relevant versions being
- python 3.8
- tables 3.9.0

The tables 3.9 release was about 6 hours ago which lines up with our Ci failures:
https://pypi.org/project/tables/

**Comment by pierce314159** [comment]
It's possible this is related to [this issue](https://github.com/Bears-R-Us/arkouda/issues/1881), but that was a while back so imagine pyarrow has build wheels for 3.11 by now

**Comment by pierce314159** [comment]
hi @tofutofu, i believe if you pull down the latest from github, this will be resolved. If you're still having issues, please reopen!
