### ISSUE TITLE
Add back python 3.12 check to CI

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#2843]
Unpinning tables and pyarrow seems to fix our dependency issues with the 3.12 check. These are the only two deps that have an upper bound so arkouda should be compatible with all the latest versions. I need to double check with @bmcdonald3 to see if the arrow version in the makefile has to match the one in yaml files

**Comment by bmcdonald3** [comment]
I don't think it's a big deal if the arrow version match. Parquet is a small part of the arrow library and most of the changes release-to-release for arrow don't actually make any Parquet changes at all, so I don't think the version is particularly important for arrow.

**Comment by pierce314159** [comment]
awesome!! Thanks Ben!
