### ISSUE TITLE
bug in `getEnv`

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#2849]
This was brought to my attention by @hokiegeek2 

My fix to `getEnv` in https://github.com/Bears-R-Us/arkouda/pull/2817 left the cast to string (`:string`) since this is what the old code did. But due to the `c_string` deprecation this was returning a string of the pointer instead

So instead of getting something like `"MY_ENV_VAL"` I would get `"0x16b167e28"`

After finding the below link, I found that I need to use `string.createCopyingBuffer` instead
https://chapel-lang.org/docs/language/evolution.html#c-string-deprecation

**Comment by hokiegeek2** [comment]
@pierce314159 thanks so much for figuring this out!

**Comment by hokiegeek2** [comment]
@pierce314159 @bmcdonald3 confirmed getEnv is working correctly w/ Arkouda built w/ Chapel 1.32:

![image](https://github.com/Bears-R-Us/arkouda/assets/10785153/aff8bc8e-1001-455e-8a88-2af2f72214bc)

Thanks to you both for making this fix happen! 💯
