### ISSUE TITLE
Align arkouda dataframe with pandas

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#2898]
Parent issue capturing the work needed to be done to better align arkouda dataframes and pandas dataframes. Feel free to edit this description or drop a comment with more information!

- [ ] https://github.com/Bears-R-Us/arkouda/issues/2893
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2894
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2896
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2897
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2929
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2935
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2939
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2942
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2947
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2973
- [ ] https://github.com/Bears-R-Us/arkouda/issues/2975
- [ ] https://github.com/Bears-R-Us/arkouda/issues/3040

**Comment by ajpotts** [comment]
Spreadsheet documenting the discrepancies:
https://docs.google.com/spreadsheets/d/1akI6JuBu9Gj6QsFt1I5VEJUD_uURiZg-yXV5cJrI8-E/edit?usp=sharing

Contact ajpotts if you need access.

**Comment by ajpotts** [comment]
Replaced with milestone.
