### ISSUE TITLE
DataFrame.size to match pandas

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#2929]
DataFrame.size function should give the total number of bytes on the arkouda server, which will frequently be the number of rows times the number of columns.  However, it currently appears to be the number of rows.  Please see the example below.

`df = ak.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]})`

`df.size`
3
`df.to_pandas().size`
6

**Comment by pierce314159** [comment]
Linking comment from PR that's related to this issue: https://github.com/Bears-R-Us/arkouda/pull/2943#discussion_r1478571211
