### ISSUE TITLE
performance enhancement to join

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#297]
related to the performance of issue #211

**Comment by mhmerrill** [comment]
@ronawho I'd like to talk about this and extend this issue with different strategies

**Comment by ronawho** [comment]
If you get a chance, it'd be great to have an arkouda benchmark to help with the performance optimization investigation (and to run nightly so we can track future improvements.)

**Comment by mhmerrill** [comment]
I am going to close this until we need it again.
