### ISSUE TITLE
Strip out ArrayView

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#2978]
Strip out the array view code. This was never fully implemented, so it's presence will just be confusing for users who think we currently have multi-dimensional array support. The idea to view a single dimensional array as multi-dimensional was based on numpy but doesn't really make sense in a distributed setting. With the progress on the array api work, there's a possibility we will be able to add support using chapel multi dimensional arrays eventually

**Comment by pierce314159** [comment]
This is complicated by the fact that `histogram2d` and `histogramdd` have arrayview returns that don't really have a good alternative and I know this is used by `akviz`. We might need to keep arrayview around until we have some other multi-dim array support

**Comment by ajpotts** [comment]
`histogram2d`: 

```
In [2]: x = ak.arange(0, 10, 1)

In [3]:  y = ak.arange(9, -1, -1)

In [4]: nbins = 3

In [5]:  h, x_edges, y_edges = ak.histogram2d(x, y, bins=nbins)

In [6]: h
Out[6]: array([array([0 0 3]) array([0 2 1]) array([3 1 0])])

In [7]: type(h)
Out[7]: arkouda.pdarrayclass.pdarray

```

**Comment by ajpotts** [comment]
`histogramdd` :
```
In [8]:  x = ak.arange(0, 10, 1)

In [9]: y = ak.arange(9, -1, -1)

In [10]: z = ak.where(x % 2 == 0, x, y)

In [11]:  h, edges = ak.histogramdd((x, y,z), bins=(2,2,5))

In [12]: h
Out[12]: array([array([array([0 0 0 0 0]) array([1 1 1 1 1])]) array([array([1 1 1 1 1]) array([0 0 0 0 0])])])

In [13]: type(h)
Out[13]: arkouda.pdarrayclass.pdarray


```
