### ISSUE TITLE
Update libzmq version in Makefile

### ISSUE THREAD

**Issue by bretteiffert** [Bears-R-Us/arkouda#2985]
libzmq is not updated to the latest version in the Makefile (v4.3.5 - October 2023, first release in years). This causes libzmq, when building with `make install-deps` or `make install-zmq`, to not build with gcc 12.x.x - which seems to be the version of gcc both Chapel and Arkouda are using today. This, of course, blocks Arkouda from building.

Error when installing libzmq v4.3.4 via `make install-zmq`:
`src/curve_client_tools.hpp:183:16: error: ‘void* memcpy(void*, const void*, size_t)’ forming offset [1, 31] is out of the bounds [0, 1] [-Werror=array-bounds] memcpy (&initiate_plaintext[crypto_box_ZEROBYTES], public_key_, 32);`

I've been changing it manually to v4.3.5 and it works well, I just wonder if this could cause potential new users to turn away from Arkouda. There may be other reasons that I am unaware of, but I'm assuming this hasn't happened yet because many active users are not building dependencies through the Makefile. I'm interested in learning if this has or hasn't been an issue for anybody else. Thanks!

**Comment by pierce314159** [comment]
Thanks so much for pointing this out! Like you said, I'm fairly certain this is just because most users opt for other ways of getting their dependencies. We should def update this

**Comment by bretteiffert** [comment]
sweet! happy to help
