### ISSUE TITLE
Update `PROTO_tests`

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#3050]
Go through the files in `PROTO_test` and make sure they:
- cover everything from their associated file in the `tests` dir does (copy over any non-obvious ones)
- run and pass

The goal is to add a makefile command for theses and test it in the CI. Eventually we will make these our only tests

- [x] #3051
- [x] #3132
- [x] #3135
- [ ] #3478
- [ ] #3479
- [ ] #3480
- [ ] #3390
- [ ] #3391
- [ ] #3481
- [ ] #3415
- [ ] #3482
- [ ] #3483
- [ ] #3484
- [x] #3128
- [ ] #3127
- [ ] #3129
- [ ] #3485
- [ ] #3131
- [ ] #3133
- [ ] #3486
- [ ] #3487
- [ ] #3488
- [ ] #3489
- [ ] #3490
- [ ] #3491
- [x] #3130
- [ ] #3492
- [ ] #3389
- [x] #3226
- [ ] #3493
- [ ] #3494
- [ ] #3495
- [ ] #3134
- [ ] #3496
- [ ] #3497
- [ ] #3498
- [ ] #3499
- [ ] #3500
- [ ] #3501
- [ ] #3502

If i missed any feel free to add it! To start on one of the tests, click the little circle with a dot on the right hand side (it will say "convert to issue" when you scroll over it). Then add yourself as the assignee and a description to the issue.

When you finish with a test, click the little box beside it to show that the task is complete

 If you don't understand what I'm saying feel free to ask :)

**Comment by stress-tess** [comment]
Known failing tests are listed in #2965

**Comment by ajpotts** [comment]
Issues have been moved to the milestone: https://github.com/Bears-R-Us/arkouda/milestone/3
So the parent ticket is no longer necessary.
