### ISSUE TITLE
Failure reading `int64` column with null values with parquet

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#3087]
a user encountered this issue when trying to read a dataset from the [nyc tax cab data](https://data.cityofnewyork.us/browse?limitTo=datasets&q=yellow+taxi+trip+data&sortBy=relevance):
```python
ak.read_parquet('yellow_tripdata_2023-02.parquet')
```
resulting in: 
```
RuntimeError: 1 errors: Error: ParquetError 142 coforall_fn:ParquetMsg Unexpected end of stream
```

The user thinks this is due to `nan`s being present in some of the columns and that it's related to https://github.com/Bears-R-Us/arkouda/issues/2005

**Comment by stress-tess** [comment]
At first I thought it was our handling of `int32s`. Because reading the file with pandas and attempting to convert to an arkouda dataframe:
```python
ak.DataFrame(pd.read_parquet('yellow_tripdata_2023-02.parquet'))
```
gives
```
RuntimeError: Unhandled data type int32
```

Which was handled in https://github.com/Bears-R-Us/arkouda/pull/2333
```python
In [6]: df_pd = pd.DataFrame({
   ...: "int16": pd.Series([2**15-1, -2**15], dtype=np.int16),
   ...: "int32": pd.Series([2**31-1, -2**31], dtype=np.int32),
   ...: "uint16": pd.Series([2**15-1, 2**15], dtype=np.uint16),
   ...: "uint32": pd.Series([2**31-1, 2**31], dtype=np.uint32),
   ...: })
   ...: fname = 'pd_test'
   ...: df_pd.to_parquet(fname)
   ...: df_ak = ak.DataFrame(ak.read(fname+"*"))

In [7]: df_pd
Out[7]:
   int16       int32  uint16      uint32
0  32767  2147483647   32767  2147483647
1 -32768 -2147483648   32768  2147483648

In [8]: df_ak
Out[8]:
   int16       int32  uint16      uint32
0  32767  2147483647   32767  2147483647
1 -32768 -2147483648   32768  2147483648 (2 rows x 4 columns)
```
But it turns out that our initializer just can't handle smaller int types right now

```python
In [9]: ak.DataFrame(df_pd)
RuntimeError: Unhandled data type int16
```

**Comment by stress-tess** [comment]
A little more digging makes me think it's failing on `'passenger_count'`, which does have `nan`s

```python
In [6]: pddf['passenger_count']
Out[6]:
0          2.0
1          1.0
2          1.0
3          0.0
4          1.0
          ...
2913950    NaN
2913951    NaN
2913952    NaN
2913953    NaN
2913954    NaN
Name: passenger_count, Length: 2913955, dtype: float64
```

**Comment by bmcdonald3** [comment]
Thanks for digging into this and reporting. After I wrap up https://github.com/Bears-R-Us/arkouda/pull/3082, I've got this next on the list.

**Comment by stress-tess** [comment]
awesome! thanks ben!

**Comment by stress-tess** [comment]
based on my awful print statements in the c++ code `passenger_count` is being interpreted by arkouda as an `int64` even tho it has nulls. I thought we must be getting the type wrong, but using `parquet-tools` it looks like it's right and we need to support reading null values for ints as well

```
parquet-tools inspect yellow_tripdata_2023-02.parquet
...
############ Column(passenger_count) ############
name: passenger_count
path: passenger_count
max_definition_level: 1
max_repetition_level: 0
physical_type: INT64
logical_type: None
converted_type (legacy): NONE
compression: ZSTD (space_saved: 56%)
...
```

**Comment by stress-tess** [comment]
@bmcdonald3 suggested I try copying the `null` handling code from the `float64` case. Making it `int64_t* tmpArr` and commenting out the `chpl_ptr[i] = NAN;`. This does allow us to read the file and for `'passenger_count'` instead of `NaN`, we have `0`

```python
>>> akdf = ak.read_parquet('/Users/pierce/Downloads/yellow_tripdata_2023-02.parquet')
>>> akdf["passenger_count"]
array([2 1 1 ... 0 0 0])
```

This stops us from failing in this case but replacing `null`s with `0` is definitely not ideal. But actually converting to a `float64` like pandas seems pretty difficult because the array is already allocated

I'm pretty unfamiliar with the parquet but maybe it's possible that every type is nullable. If so, it might make sense to pass along an `isNan` boolean pdarray for reading any parquet column. Because then it would be fairly easy to convert the right values to `NaN` after the fact
