### ISSUE TITLE
failure in `test_sparse_sum_helper`

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#3088]
@bmcdonald3 reported a failure in `test_sparse_sum_helper` during their nightly run of our tests with the error:
```
FAILED tests/util_test.py::UtilTest::test_sparse_sum_helper - ValueError: shape mismatch [1271] [1269]
```
in my experience this is due to some off by ones in the index math

unfortunately this relies on `ak.randint` without a set seed, so reproducing this might be difficult to track down. I should definitely add a randomly generated set seed to this test so any future failures will be easier to reproduce

We should also consider having the sort based workflow be the default and have the merge based be opt in

**Comment by stress-tess** [comment]
I'm really struggling to reproduce this. I've modified the test to have a randomly selected set seed:
```python
def test_sparse_sum_helper(self):
    seed = np.random.default_rng().choice(2**63)
    ...
    def are_pdarrays_equal(pda1, pda2):
        # we first check the sizes so that we won't hit shape mismatch
        # before we can print the seed (due to short-circuiting)
        return (pda1.size == pda2.size) and ((pda1 == pda2).all())

    cond = (
        are_pdarrays_equal(merge_idx, sort_idx)
        and are_pdarrays_equal(merge_idx, gb_idx)
        and are_pdarrays_equal(merge_vals, sort_vals)
    )

    if not cond:
        print(f"Failure with seed = {seed}")
    self.assertTrue(cond)
```

I've verified that when I intentionally modify one of the arrays I'm testing to have different values that it fails and prints out the seed. It will look like the following:
```
----------------------------------------------- Captured stdout call -----------------------------------------------
Failure with seed = 3875030313406367833
```

So now I just have to find a seed that fails. I changed the `ARKOUDA_RUNNING_MODE` in `pytest.ini` to be `CLIENT`, so I can run the test with a multi-locale server. I then used the following bash loop to run the test over and over:
```
for run in {1..25}; do python3 -m pytest tests/util_test.py::UtilTest::test_sparse_sum_helper; don
```
I've tried this with different numbers of locales, but I still can't get  a failure

**Comment by bmcdonald3** [comment]
Interesting... It only popped up for one night on our nightly test and then resolved, so I'd say we can push this to the side for now and I'll let you know if it pops up with any consistency. Thanks for looking into it so quick!

**Comment by stress-tess** [comment]
Thanks @bmcdonald3! I went ahead and put up a PR modifying the test so hopefully it'll be easier to reproduce next time!

**Comment by stress-tess** [comment]
we got a hit! The nightly failed with the following seeds:
```
1000509587142185552,
5931535381009490148,
5631286082363685405,
3867516237354681488
```

but... i'm still struggling to reproduce this locally when running over subscribed with gasnet. I was running the following
```python
def test_sparse_sum_helper():
    import arkouda as ak
    import numpy as np
    ak.connect()

    seed1 = 1000509587142185552
    seed2 = 5931535381009490148
    seed3 = 5631286082363685405
    seed4 = 3867516237354681488
    cfg = ak.get_config()
    N = (10 ** 3) * cfg["numLocales"]
    select_from = ak.arange(N)
    inds1 = select_from[ak.randint(0, 10, N, seed=seed1) % 3 == 0]
    inds2 = select_from[ak.randint(0, 10, N, seed=seed2) % 3 == 0]
    vals1 = ak.randint(-(2 ** 32), 2 ** 32, inds1.size, seed=seed3)
    vals2 = ak.randint(-(2 ** 32), 2 ** 32, inds2.size, seed=seed4)

    merge_idx, merge_vals = ak.util.sparse_sum_help(inds1, inds2, vals1, vals2, merge=True)
    sort_idx, sort_vals = ak.util.sparse_sum_help(inds1, inds2, vals1, vals2, merge=False)
    gb_idx, gb_vals = ak.GroupBy(ak.concatenate([inds1, inds2], ordered=False)).sum(
        ak.concatenate((vals1, vals2), ordered=False)
    )

    def are_pdarrays_equal(pda1, pda2):
        return (pda1.size == pda2.size) and ((pda1 == pda2).all())

    cond = (
        are_pdarrays_equal(merge_idx, sort_idx)
        and are_pdarrays_equal(merge_idx, gb_idx)
        and are_pdarrays_equal(merge_vals, sort_vals)
    )

    print()
    if cond:
        print("WE PASSED!!!")
    else:
        print("we failed...")
        print()
    print(f"num locales:\n{cfg['numLocales']}")
    print(f"seeds:\n{seed1},\n{seed2},\n{seed3},\n{seed4}")
    assert cond
```
and got a passing result with 16 locales :/
```python
>>> test_sparse_sum_helper()
connected to arkouda server tcp://*:5555

WE PASSED!!!
num locales:
16
seeds:
1000509587142185552,
5931535381009490148,
5631286082363685405,
3867516237354681488
```
