### ISSUE TITLE
Support user-defined unicode arrays

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#314]
I believe the arkouda Strings infrastructure already handles UTF-8 internally and when read in from HDF5, but when the user calls `ak.array` on a python list containing unicode, it errors.

```python
>>> a1 = ak.array([chr(ri) for ri in np.random.randint(low=32, high=0xfff, size=50)])
IndexError in arkouda/pdarraycreation.py, line 76
```

The code in `ak.array` does not accout for multi-byte characters in the numpy array to be transmitted over the socket. Also, it uses whatever encoding numpy uses for strings, which I am beginning to suspect is not UTF-8. We should modify `ak.array` to first encode all input strings as UTF-8 (possibly bypassing numpy) and then pack the actual encoded bytes appropriately.

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 looks like this is working:

![image](https://user-images.githubusercontent.com/10785153/102784840-edca8900-436a-11eb-928c-bab598f7a8c1.png)

is this issue resolved or is there more work to do?

**Comment by reuster986** [comment]
Do unicode strings pass all the current tests?

**Comment by hokiegeek2** [comment]
@reuster986 I only tested the code example you posted, so I don't know

**Comment by ronawho** [comment]
It's possible this was resolved while working on https://github.com/Bears-R-Us/arkouda/issues/794, specifically in https://github.com/Bears-R-Us/arkouda/pull/870. The old `ak.array()` code used `struct.pack` and a bunch of other calls to convert the numpy array into something to send over the wire. Today we just directly take the numpy bytes and send them over the wire.

The code snippet in the description doesn't fail for me, but I'm not sure what all you'd want in terms of testing to feel confident this is done.

**Comment by Ethan-DeBandi99** [comment]
@reuster986 I just verified that this is functioning in Arkouda. Recommend closing this issue.

**Comment by mhmerrill** [comment]
i concur with closing this. if @reuster986 wants to reopen it we can.
