### ISSUE TITLE
chpldoc: not found

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#3140]
Recieve an error when I run `make doc`:

chpldoc --process-used-modules /home/amandapotts/git/arkouda//src/arkouda_server.chpl /home/amandapotts/git/arkouda//src/compat/e-132/* -o /home/amandapotts/git/arkouda//docs/server
/bin/sh: 1: chpldoc: not found
make: *** [Makefile:443: /home/amandapotts/git/arkouda//docs/server/index.html] Error 127

**Comment by stress-tess** [comment]
you gotta `make chpldoc` in ur `$CHPL_HOME` directory
```
(cd $CHPL_HOME && make chpldoc)
```
