### ISSUE TITLE
Add multi-dim pdarrays to standard API

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#3422]
Let's start flipping the switch on adding the multi-dim pdarray to the standard API, as part of this we should [strip out the arrayview](https://github.com/Bears-R-Us/arkouda/issues/2978) code.

**Comment by drculhane** [comment]
I spent part of this morning documenting the places in the python code where pdarrays are created.  This is what I've got so far.
[pdarray_creation_places.xlsx](https://github.com/user-attachments/files/16179032/pdarray_creation_places.xlsx)

**Comment by drculhane** [comment]
Here's an updated spreadsheet: 
[pdarray_creation_places.xlsx](https://github.com/user-attachments/files/16268597/pdarray_creation_places.xlsx)
