### ISSUE TITLE
unpin hdf5 library

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#3519]
The pandas io library is throwing the following error: 
```
E                   ImportError: Pandas requires version '3.8.0' or newer of 'tables' (version '3.7.0' currently installed).
```

But in order to upgrade `pytables`, `hdf5` needs to be upgraded as well, otherwise conda fails to solve environment.

**Comment by stress-tess** [comment]
I say let's try to update hdf5 to [1.14 ](https://www.hdfgroup.org/downloads/hdf5)

We have to make sure to update this in the Makefile as well as in the conda env yamls. I did something similar with arrow not too long ago:
https://github.com/Bears-R-Us/arkouda/pull/2806/files
