### ISSUE TITLE
Multidim random causing failures with multilocale

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#3627]
PR #3524 is causing failures in the nightly. It seems my conversion over to use the new framework makes it so even 1 dimensional random generation is causing failures with multi-locale

**Comment by stress-tess** [comment]
hmm running the following command with the 2 locales:
```python
ARKOUDA_RUNNING_MODE=CLIENT python3 -m pytest PROTO_tests/tests/random_test.py
```

I'm seeing a server crash. Enabling runtime checks gives me:
```
proj/arkouda//src/RandMsg.chpl:563: error: assert failed
```

And line 563 is:
https://github.com/Bears-R-Us/arkouda/blob/8df04761390896cd4f9bc11a1b7ac23063ebed4b/src/RandMsg.chpl#L562-L564

so the failing assertion isn't explicit. I'm gonna keep digging in but wanted to see if @jeremiah-corrado or @bmcdonald3 knows what this is offhand

**Comment by stress-tess** [comment]
I'm realizing now that I actually stripped out the multidim functionality for `choice` and forgot to drop the `orderToIndex`. So it might be an easy fix here

**Comment by stress-tess** [comment]
ah I think maybe the assertion it's failing is that they could both be remote? Cause I changed it to this and was still getting it:
```chapel
forall (idx, arrIdx) in zip(choiceIdx, 0..) with (var agg = newSrcAggregator(array_dtype)) {
    agg.copy(choiceArr[arrIdx], myArr[idx]);
}
```

I think previously the leading iterator was `choiceArr` but I switched the order when I wanted to use `0..` bc that would be a bad leading iterator. I think I could prob make the leading iter choiceArr.domain, but idk if that would've played nicely with `orderToIndex` or not

**Comment by jeremiah-corrado** [comment]
> but it's unclear to me if that's because of the remote to remote thing or because we made the domain distributed

If this is similar to the issue I was seeing in IndexingMsg that Ben mentioned, then I think it's because the domain became distributed.

Do you get the same assertion failure if you don't use aggregation, and just put an assignment in the loop body?
```chapel
choiceArr[arrIdx] = myArr[idx];
```
