### ISSUE TITLE
remove _is_dtype_in_union and _val_isinstance_of_union

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#3643]
Remove _is_dtype_in_union and _val_isinstance_of_union, as they are only used by `is_float`, `is_int`, and `is_numeric`.

**Comment by stress-tess** [comment]
I think I'm in favor of keeping these around. I think they could be useful if we end up working https://github.com/Bears-R-Us/arkouda/issues/3644 and updating our typeguard to the latest version

**Comment by ajpotts** [comment]
We'll keep these around for now.  They're being used more than I realized.
