### ISSUE TITLE
nonzero in ReductionMsg to preserve order

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#3676]
nonzero in ReductionMsg to preserve order

To match numpy,
https://numpy.org/doc/stable/reference/generated/numpy.nonzero.html
the order of the nonzero indices returned should be row-major, C-style order.  However, when running `test_nonzero` locally,
```
print(nz)
(Arkouda Array ((4,), int64)[0 1 2 3], Arkouda Array ((4,), int64)[1 2 2 2], Arkouda Array ((4,), int64)[0 3 2 1])
```
whereas in the CI
```
print(nz)
(Arkouda Array ((4,), int64)[0 2 3 1], Arkouda Array ((4,), int64)[1 2 2 2], Arkouda Array ((4,), int64)[0 2 1 3])
```

**Comment by jeremiah-corrado** [comment]
@ajpotts, were you seeing the incorrect output consistently in the CI or was it intermittent / different each run?
