### ISSUE TITLE
Enable casting of pdarray and Strings

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#380]
There are currently hacky ways to cast between pdarrays of different types, e.g. 1.0 * int64 => float64, but casting would benefit from a standard API. Also, there is currently no way to convert between Strings and pdarray.

In numpy, casting is done by calling the actual dtype on an array, e.g. `myint = np.int64(myfloat)`. Arkouda dtypes just alias numpy dtypes, but we could overload their `__call__` methods to handle pdarray and Strings arg types with this syntax. If this is problematic for some reason, we could just have an `ak.cast()` function.

Additional considerations:
* For casts from float64 to int64, we should probably implement both floor and ceiling.
* For casts from numeric to Strings, we have the option to get fancy, e.g. allowing the user to pass a chapel format string specifying the conversion. However, I think we should maybe just support the default behavior of `x:string` for now.
* For casts from Strings to numeric, we should allow the user to specify how to handle errors, e.g. raise errors or replace with an NA value.

**Comment by pierce314159** [comment]
This appears to be resolved by the mentioned PR, I am going to go ahead and close this issue. @reuster986, feel free to reopen (or open a new issue) if there's still functionality here that you'd like to have
