### ISSUE TITLE
Speed up CI testing

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#388]
gasnet CI testing takes ~45 minutes, which is a bit long for my taste especially since the comm=none testing only takes 6 minutes. The comm=none config is faster in both build and testing times. I don't think there's much we can do about the build times, but we should be able to improve testing times. I'm hoping we can get gasnet CI below 30 minutes. Things to try:
 - [x] use gasnet-smp instead of gasnet-udp (will use shared memory for comm instead of going through the kernel with udp)
 - [ ] try to speed up long running tests 
   - I suspect the sorting tests are the bottleneck. Even though we're sorting a small number of elements, the sort code has `2**16` buckets, which results in a lot fo communication regardless of how many elements are being sorted. We may just want to run fewer sorting tests as part of CI and rely on nightly testing or something for more exhaustive tests.

**Comment by ronawho** [comment]
comm=none `make python` takes 25s and gasnet-smp takes 19 minutes. Here's all tests under gasnet-smp that take over 5 seconds:

```
523.45s call     tests/groupby_test.py::GroupByTest::test_groupby_one_two_levels
123.86s call     tests/coargsort_test.py::CoargsortTest::test_int
 75.38s call     tests/operator_tests.py::OperatorsTest::testAllOperators
 67.09s call     tests/join_test.py::JoinTest::test_join_on_eq_with_true_dt_with_result_limit
 61.59s call     tests/join_test.py::JoinTest::test_join_on_eq_with_abs_dt_outside_window
 59.67s call     tests/coargsort_test.py::CoargsortTest::test_large
 39.85s call     tests/coargsort_test.py::CoargsortTest::test_float
 23.84s call     tests/setops_test.py::SetOpsTest::testOneDimensionalSetXor
 22.47s call     tests/coargsort_test.py::CoargsortTest::test_int_float
 11.09s call     tests/compare_test.py::CompareTest::test_compare_argsort
 11.04s call     tests/setops_test.py::SetOpsTest::testOneDimensionalSetUnion
 10.60s call     tests/setops_test.py::SetOpsTest::testOneDimensionalSetIntersection
  9.14s call     tests/setops_test.py::SetOpsTest::testOneDimensionalSetDifference
  9.03s call     tests/compare_test.py::CompareTest::test_compare_sort
```

**Comment by ronawho** [comment]
Current results where gasnet-smp took 48 minutes total (I'm just adding `--duration=0` to the pytest command to get this and running in CI):

```
647.66s call     tests/groupby_test.py::GroupByTest::test_groupby_one_two_levels
154.37s call     tests/string_test.py::StringTest::test_peel
120.51s call     tests/string_test.py::StringTest::test_in1d
116.15s call     tests/coargsort_test.py::CoargsortTest::test_int
81.54s call     tests/string_test.py::StringTest::test_argsort
76.24s call     tests/string_test.py::StringTest::test_groupby
72.74s call     tests/string_test.py::StringTest::test_stick
72.55s call     tests/operator_tests.py::OperatorsTest::testAllOperators
72.17s call     tests/string_test.py::StringTest::test_unique
72.16s call     tests/string_test.py::StringTest::test_pdarray_index
64.37s call     tests/join_test.py::JoinTest::test_join_on_eq_with_true_dt_with_result_limit
63.67s call     tests/join_test.py::JoinTest::test_join_on_eq_with_abs_dt_outside_window
63.33s call     tests/groupby_test.py::GroupByTest::test_groupby_on_one_level
62.71s call     tests/string_test.py::StringTest::test_error_handling
62.61s call     tests/string_test.py::StringTest::test_slice
61.44s call     tests/string_test.py::StringTest::test_ends_with
61.34s call     tests/string_test.py::StringTest::test_contains
61.15s call     tests/string_test.py::StringTest::test_index
59.93s call     tests/string_test.py::StringTest::test_str_output
59.36s call     tests/string_test.py::StringTest::test_starts_with
59.03s call     tests/string_test.py::StringTest::test_compare_strings
52.94s call     tests/coargsort_test.py::CoargsortTest::test_large
39.12s call     tests/coargsort_test.py::CoargsortTest::test_float
37.53s call     tests/numeric_test.py::NumericTest::testCast
28.39s call     tests/setops_test.py::SetOpsTest::test_setops
27.84s call     tests/numeric_test.py::NumericTest::testSeededRNG
21.94s call     tests/categorical_test.py::CategoricalTest::testContains
21.54s call     tests/categorical_test.py::CategoricalTest::testGroup
19.95s call     tests/categorical_test.py::CategoricalTest::testBaseCategorical
18.86s call     tests/coargsort_test.py::CoargsortTest::test_int_float
17.94s call     tests/check.py::CheckTest::testCoargsort
15.77s call     tests/groupby_test.py::GroupByTest::test_broadcast_ints
14.82s call     tests/groupby_test.py::GroupByTest::test_error_handling
14.40s call     tests/groupby_test.py::GroupByTest::test_broadcast_booleans
12.51s call     tests/check.py::CheckTest::testArgsort
11.61s call     tests/nan_test.py::NanTest::test_nan
10.50s call     tests/setops_test.py::SetOpsTest::testSetxor1d
10.36s call     tests/setops_test.py::SetOpsTest::testIntersectId
10.16s call     tests/compare_test.py::CompareTest::test_compare_argsort
```

**Comment by reuster986** [comment]
For `groupby_test.py`, what if we decreased the size of the test, e.g. `SIZE = 100` and `GROUPS = 8`? That would still catch most logic errors while (probably) greatly decreasing the runtime for gasnet. Meanwhile, we could create a groupby benchmark to run nightly, which I've been wanting to do anyway since groupby is such a workhorse for us.

**Comment by ronawho** [comment]
> For groupby_test.py, what if we decreased the size of the test, e.g. SIZE = 100 and GROUPS = 8? That would still catch most logic errors while (probably) greatly decreasing the runtime for gasnet. 

Yeah, that takes test_groupby_one_two_levels from 500-600 seconds down to 50 seconds, and speeds up the other groupby's a bit. Overall I think that shaves 10 minutes off the gasnet CI testing. 


> Meanwhile, we could create a groupby benchmark to run nightly, which I've been wanting to do anyway since groupby is such a workhorse for us.

I am always in favor of more benchmarks :)

**Comment by reuster986** [comment]
Great! Do you want me to tackle the groupby benchmark? I'm happy to do it, just want to make sure you haven't already started.

**Comment by ronawho** [comment]
Yeah, I'll let you tackle the groupby benchmark (I'm not familiar with groupby usage yet)

**Comment by mhmerrill** [comment]
@ronawho have we satisfied this yet... can we close it?

**Comment by ronawho** [comment]
Here are the current correct timings:

```
325.37s call     tests/string_test.py::StringTest::test_peel
114.62s call     tests/coargsort_test.py::CoargsortTest::test_int
112.32s call     tests/string_test.py::StringTest::test_in1d
100.13s call     tests/string_test.py::StringTest::test_stick
82.55s call     tests/join_test.py::JoinTest::test_join_on_eq_with_abs_dt_outside_window
79.51s call     tests/string_test.py::StringTest::test_argsort
79.41s call     tests/string_test.py::StringTest::test_flatten
77.72s call     tests/operator_tests.py::OperatorsTest::testAllOperators
68.50s call     tests/string_test.py::StringTest::test_groupby
67.91s call     tests/string_test.py::StringTest::test_pdarray_index
67.11s call     tests/groupby_test.py::GroupByTest::test_groupby_one_two_levels
65.14s call     tests/groupby_test.py::GroupByTest::test_groupby_on_one_level
62.12s call     tests/string_test.py::StringTest::test_unique
59.99s call     tests/join_test.py::JoinTest::test_join_on_eq_with_true_dt_with_result_limit
59.76s call     tests/string_test.py::StringTest::test_ends_with_delimiter_match
57.60s call     tests/string_test.py::StringTest::test_index
57.54s call     tests/string_test.py::StringTest::test_ends_with
55.81s call     tests/string_test.py::StringTest::test_contains
55.38s call     tests/string_test.py::StringTest::test_slice
54.57s call     tests/string_test.py::StringTest::test_error_handling
54.52s call     tests/string_test.py::StringTest::test_compare_strings
54.43s call     tests/string_test.py::StringTest::test_starts_with
53.63s call     tests/string_test.py::StringTest::test_str_output
52.09s call     tests/datetime_test.py::DatetimeTest::test_units
51.30s call     tests/coargsort_test.py::CoargsortTest::test_large
42.21s call     tests/datetime_test.py::DatetimeTest::test_op_types
36.90s call     tests/numeric_test.py::NumericTest::testCast
36.38s call     tests/coargsort_test.py::CoargsortTest::test_float
27.39s call     tests/numeric_test.py::NumericTest::testSeededRNG
26.14s call     tests/setops_test.py::SetOpsTest::test_setops
23.13s call     tests/datetime_test.py::DatetimeTest::test_plus_minus
20.54s call     tests/coargsort_test.py::CoargsortTest::test_int_float
18.08s call     tests/categorical_test.py::CategoricalTest::testBaseCategorical
17.25s call     tests/categorical_test.py::CategoricalTest::testContains
16.86s call     tests/check.py::CheckTest::testCoargsort
15.69s call     tests/categorical_test.py::CategoricalTest::testGroup
15.11s call     tests/groupby_test.py::GroupByTest::test_bitwise_aggregations
14.48s call     tests/groupby_test.py::GroupByTest::test_error_handling
14.33s call     tests/nan_test.py::NanTest::test_nan
11.75s call     tests/check.py::CheckTest::testArgsort
10.48s call     tests/join_test.py::JoinTest::test_join_on_eq_with_pos_dt_outside_window
10.03s call     tests/compare_test.py::CompareTest::test_compare_argsort
```

It may be worth looking at speeding up peel and stick, but most of the others use sort, which has a large fixed overhead regardless of the array size being sorted so I'm not sure how much we can do there. 

With the addition of the string benchmarks, the benchmark `--correctness-only` bumped from a couple seconds to 20 minutes.  

With everything the gasnet CI correctness testing takes an hour right now, which feels long to me. Do the long CI times bother you, or are you happy with how long things take currently?

**Comment by ronawho** [comment]
With https://github.com/mhmerrill/arkouda/pull/742 and https://github.com/mhmerrill/arkouda/pull/750 gasnet CI testing is down to ~35 minutes. Building/installing arkouda takes ~10 minutes and the arkouda pytest tests take ~20 minutes with the following breakdown:

```
95.24s call     tests/join_test.py::JoinTest::test_join_on_eq_with_abs_dt_outside_window
76.51s call     tests/string_test.py::StringTest::test_peel
53.70s call     tests/coargsort_test.py::CoargsortTest::test_int
50.66s call     tests/join_test.py::JoinTest::test_join_on_eq_with_true_dt_with_result_limit
36.66s call     tests/categorical_test.py::CategoricalTest::testConcatenate
31.17s call     tests/string_test.py::StringTest::test_argsort
29.74s call     tests/string_test.py::StringTest::test_flatten
25.75s call     tests/coargsort_test.py::CoargsortTest::test_large
24.49s call     tests/string_test.py::StringTest::test_groupby
23.93s call     tests/string_test.py::StringTest::test_stick
23.72s call     tests/string_test.py::StringTest::test_unique
21.17s call     tests/numeric_test.py::NumericTest::testCast
20.98s call     tests/string_test.py::StringTest::test_in1d
20.28s call     tests/string_test.py::StringTest::test_pdarray_index
20.13s call     tests/string_test.py::StringTest::test_string_registration
19.04s call     tests/string_test.py::StringTest::test_error_handling
19.01s call     tests/string_test.py::StringTest::test_contains
18.84s call     tests/string_test.py::StringTest::test_slice
18.83s call     tests/string_test.py::StringTest::test_starts_with
18.75s call     tests/string_test.py::StringTest::test_ends_with
18.45s call     tests/string_test.py::StringTest::test_compare_strings
18.43s call     tests/string_test.py::StringTest::test_index
18.33s call     tests/string_test.py::StringTest::test_ends_with_delimiter_match
18.22s call     tests/string_test.py::StringTest::test_str_output
17.50s call     tests/coargsort_test.py::CoargsortTest::test_float
17.32s call     tests/categorical_test.py::CategoricalTest::testBinop
17.08s call     tests/categorical_test.py::CategoricalTest::testEquality
16.69s call     tests/check.py::CheckTest::testCoargsort
16.31s call     tests/groupby_test.py::GroupByTest::test_groupby_one_two_levels
12.96s call     tests/groupby_test.py::GroupByTest::test_groupby_on_one_level
12.19s call     tests/categorical_test.py::CategoricalTest::testIn1d
11.24s call     tests/check.py::CheckTest::testArgsort
```

I think we could probably do something speed up the join tests and peel/stick, but I'm not personally very familiar with them. I'm pretty happy with CI testing taking around 30 minutes, so I'd be fine closing this now if you are @mhmerrill

**Comment by glitch** [comment]
I started looking into this and noticed a few things:

- If running from command line (i.e. python tests/string_test.py) this happens
```
Traceback (most recent call last):
  File "tests/string_test.py", line 355, in <module>
    run_test_stick(strings, test_strings, base_words, delim)
TypeError: run_test_stick() missing 1 required positional argument: 'N'
```
After fixing this the tetsts run in about 12 seconds.  (Note: this leads me to believe that this is really no longer being used)

- Running with the pytest framework string_test takes about 16 minutes on my local machine.  There is a lot of setup which happens per test but isn't necessarily used in each test (i.e. gremlins setup).  Gremlins setup takes about 11 seconds on my machine, but was only being used in 4 out of 17 tests.  Moving this into its own method so it could be generated on-demand slimmed my total test time down to about 13 minutes, so about a 3 minute savings.

I'm going to look into this a bit more to see if there is any other low-hanging fruit to make this series of tests to run faster.

**Comment by glitch** [comment]
Hmm... I should note the time referenced above were running in an IDE.  Running pytest manually from the command line via
```
# master branch
time pytest tests/string_test.py

real    1m19.225s
user    5m15.374s
sys     2m11.911s
```

and 
```
# with updates
time pytest tests/string_test.py
real    0m44.283s
user    2m38.308s
sys     1m14.621s
```

I'm not sure why there is such a huge discrepancy between the IDE and command-line that seems strange, but in both cases the test updates speed things up a bit.

**Comment by ronawho** [comment]
I don't use IDEs much, but I wonder if there's some environment variables that aren't set in your IDE configuration, but are set on your command line. Things like `CHPL_RT_OVERSUBSCRIBED=yes`

**Comment by glitch** [comment]
@ronawho That is a great point.  I had the env vars set in my bashrc file but the IDE wasn't picking those up even with the "include system env vars" option set.  Adding them to the test configuration manually sped everything up to normal (~35s for the whole suite).

These changes still offer some minor improvement so they should be considered, but they don't have as big of an impact.

**Comment by ronawho** [comment]
CI testing has gotten slower over the last month or two. It looks like ~10 minutes is being spent installing the python dependencies and specifically I'm guessing pandas is being built from source. e.g. https://github.com/Bears-R-Us/arkouda/runs/3758532109?check_suite_focus=true#step:5 takes 15 minutes to build/install arkouda but only 2.5 of those minutes is to build the arkouda_server.

Looks like things slowed down between these 2 runs:
 - https://github.com/Bears-R-Us/arkouda/runs/3137193798?check_suite_focus=true
 - https://github.com/Bears-R-Us/arkouda/runs/3163989792?check_suite_focus=true

Where one of the differences is that pandas 1.3.0 is used in the first run, and 1.3.1 is used in the second. 

I don't really understand python dependencies so I'm not sure why things would be getting built from source now.

**Comment by ronawho** [comment]
Doesn't look like pandas is being installed from source anymore, so installing python deps is fast again. Not sure what changed, but not going to worry about it.

**Comment by ronawho** [comment]
CI testing takes ~30 minutes right now, which feels reasonable to me. The current slowest aspect is the multi-locale arkouda pytests, and there are some that are a little slower (peel/stick, grouby, join) but nothing outrageously slow.

**Comment by ronawho** [comment]
CI testing is back above an hour, so we're going to limit multi-locale CI testing for the time being.
