### ISSUE TITLE
Improve error/check for Chapel installation

### ISSUE THREAD

**Issue by bradcray** [Bears-R-Us/arkouda#410]
In [this StackOverflow post](https://stackoverflow.com/questions/62629403/pip-install-arkouda-fails-even-when-chapel-installed), a user was confused about why pip installing Arkouda was leading to an error about Chapel not being installed when, to him, it clearly was.  This makes me wonder whether:

(a) Arkouda could be checking for Chapel installation via `which chpl` rather than `$CHPL_HOME` (in general, `$CHPL_HOME` is not required to be set when using `chpl`);
(b) if $CHPL_HOME must be set for some reason, updating the error message to indicate that the problem is actually that `$CHPL_HOME` isn't set (though this worries me a little as homebrew users, for example, don't tend to have `$CHPL_HOME` set.

**Comment by Ethan-DeBandi99** [comment]
The installation documentation has been updated to indicate to users that `$CHPL_HOME` needs to be set and how to set it.

**Comment by Ethan-DeBandi99** [comment]
@bradcray - Yes the `Makefile` uses `CHPL_HOME` specifically during install. We could adjust this moving forward, but I am not sure exactly what is required to make that work.

**Comment by bradcray** [comment]
If the Makefile is the only place that relies on it, it probably suffices to have the Makefile contain

```make
CHPL_HOME=$(shell chpl --print-chpl-home | head -1 | cut -f1')
```

Since Makefile variables take their defaults based on environment variables, I think this would only kick in if the user had not set CHPL_HOME.

The only downside to this approach that I can think of is that it relies on `--print-chpl-home` continuing to work and have a similar format.  However, as long as we don't ever make CHPL_HOME not be the first thing it prints out, I think it should be good.

**Comment by bradcray** [comment]
(also, note that I'm not at all insistent on this.  But I did encounter users recently who were very complimentary of how easy Arkouda was to get started with relative to Dask, which makes me wonder what other barriers we can reduce to simplify things).
