### ISSUE TITLE
Expand set of Arkouda examples/tutorials with Netflow data

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#427]
Develop Jupyter notebooks that detail a variety of Arkouda EDA workflows using Netflow data.

**Comment by pierce314159** [comment]
I'm recommending closing because I think this issue fits better in the `ArkoudaNotebooks` repo and should be moved over

**Comment by pierce314159** [comment]
Moved to https://github.com/Bears-R-Us/ArkoudaNotebooks/issues/19
