### ISSUE TITLE
Support all types/operations in benchmark codes

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#458]
The benchmarks track common types/operations, but it'd be good to be able to run all supported types. e.g. `bool` reductions are supported for reductions, but `reduce.py` can't run with bools and reduce.py only runs sum/prod/min/ max, but there are other operators like argmin/argmax/is_sorted.

See comments in https://github.com/mhmerrill/arkouda/pull/400 for more info.

**Comment by mhmerrill** [comment]
@ronawho is this done? if it is close it.
