### ISSUE TITLE
Arkouda does not support overwriting datasets in hdf5 -> should it?

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#474]
I noticed that, when I attempt to overwrite a dataset the entire hdf5 file is overwritten:

![image](https://user-images.githubusercontent.com/10785153/92112101-49243b80-edbb-11ea-811e-491e94610ae3.png)

Question -> should we support overwriting individual datasets? Just wanted to open it up for discussion.

--John

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 Thoughts on this one?

**Comment by reuster986** [comment]
@hokiegeek2 I think ideally we should support overwriting an individual dataset, but if it is too hard to implement, we don't need to make it a high priority.

**Comment by Ethan-DeBandi99** [comment]
@pierce314159, @joshmarshall1, @jaketrookman, @hokiegeek2 - Want to get your input here. I believe this would be extremely useful, though there are a few potential problems. If we add this to the current write funcitonality, Truncate mode would now need to only overwrite the columns with names matching the data being written, but not the entire file.

I am thinking the best way to handle this is to add `update` functions that would be linked to a new message and processing workflow in chapel that would update the columns if they exist or add them if they do not. Additionally, it would fail if the provided file name did not match. Does that make sense?

**Comment by hokiegeek2** [comment]
@hokiegeek2 I agree this would be a good feature and your plan sounds good to me 💯
