### ISSUE TITLE
Use Arkouda to interact with Chapel objects

### ISSUE THREAD

**Issue by buddha314** [Bears-R-Us/arkouda#559]
Suppose I have created a matrix A using the Arkouda package and now I want to do something with it that only Chapel can do. Is there a way to use the Arkouda ZMQ connection to do something like 

```
B = ak.doSomeCoolChapelStuff(cmd)
or 
B = ak.doSomeCoolChapelStuff(cmd, A)
```
where cmd is defined in a Chapel package? If not, can you suggest a way I can interact with the objects on the server side?

**Comment by mhmerrill** [comment]
@buddha314 
thanks! there is a basic flow in the docs to add a new command to the server

https://arkouda.readthedocs.io/en/latest/contributing.html#adding-functionality-to-the-arkouda-server

the doc needs to be updated but you will get the basic idea and it's mostly still correct

also, we try to keep the chapel-array functionality separate from the message, most of the modules have a Foo.chpl (chapel arrays functionality) and a FooMsg.chpl (message processing functionality/error check)

we have several users who have their own special version of the server, it is possible to keep a pretty clean separation but you will need to keep a repo and a branch with your functionality in it so you can merge in master every so often to keep up.

**Comment by buddha314** [comment]
Thanks! Do you have thoughts on the feasibility of this request?

**Comment by mhmerrill** [comment]
@buddha314 did you get any traction with this? do you have specific questions? would you like to have a online discussion?

**Comment by buddha314** [comment]
I wasn't able to try yet, I keep thinking I'll try this "tomorrow".  When I do, I would love to chat with you about it.  Is gitter a good way to reach out?

**Comment by mhmerrill** [comment]
@buddha314 we are cleaning up issues and were wondering if you needed anything with respect to this?

**Comment by pierce314159** [comment]
This issue has been outstanding a while. I think it should be covered by the `CONTRIBUTING.md`. I am going to recommend closing

**Comment by mhmerrill** [comment]
i concur with closing we now have examples in https://github.com/Bears-R-Us/arkouda-contrib
