### ISSUE TITLE
Upgrade to Python 3.8

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#612]
I recommend we upgrade to Python 3.8 as it has several [improvements](https://www.python.org/downloads/release/python-380/) including a new, more performant pickling protocol (pickle 5), shared memory for multiprocessing, and an enhanced typing package that can be used for further tighten static type checking as well as attribute/method inheritance rules.

**Comment by ronawho** [comment]
@hokiegeek2 can you ping me if/when you upgrade? (It takes some time for us to get newer python versions installed on the machines we do nightly testing on)

**Comment by reuster986** [comment]
How many of those features will we use? I can see using the typing enhancements, but are they really worth putting the burden on users to upgrade? Unless we have a really compelling use case, I'd prefer to keep the Python version requirements as open as possible.

**Comment by hokiegeek2** [comment]
@reuster986 The typing part is cool, and the pickle5 support is big for serialization which we may need at some point for client-side processing. But there's definitely no huge rush to upgrade.

**Comment by mhmerrill** [comment]
@hokiegeek2 we currently require at least Python 3.7, correct?

**Comment by hokiegeek2** [comment]
@mhmerrill yes

**Comment by Ethan-DeBandi99** [comment]
Should we update this to require python 3.9? Seems to have some worth while enhancements in addition to 3.8. https://docs.python.org/3/whatsnew/3.9.html

**Comment by mhmerrill** [comment]
@Bears-R-Us/arkouda-core-dev I am ok with moving up to Python 3.8, what does everyone think? 3.9 is ok with me also but I want to make sure we have that in our production build env.

**Comment by reuster986** [comment]
We are running 3.8

**Comment by mhmerrill** [comment]
OK, IMO we can move up to 3.8
I will make one final check at our team meeting this morning.
@ronawho you asked to be notified when this happened.

**Comment by ronawho** [comment]
Sounds good. FWIW NumPy 1.22.0 bumped their minimum python version to 3.8 as well.

I will plan on upgrading our internal systems to 3.10 so we don't have to worry about this for a while.
