### ISSUE TITLE
How do we become compatible with the most recent NumPy 1.20?

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#670]
How do we become compatible with the most recent NumPy 1.20?
What is the real issue to grapple with?

**Comment by hokiegeek2** [comment]
@mhmerrill the version available at our customer sites as well as mypy compatibility. I can make the latter a priority at your direction.

**Comment by mhmerrill** [comment]
this appears to be an incompatibility with `my-you

**Comment by hokiegeek2** [comment]
@mhmerrill After upgrading to Numpy 1.20.1, the following mypy errors occur:

![image](https://user-images.githubusercontent.com/10785153/108243088-ae76a980-711b-11eb-8661-333b74aa429c.png)

Some of the errors may be associated with this [deprecation notice](https://numpy.org/doc/stable/release/1.20.0-notes.html):

![image](https://user-images.githubusercontent.com/10785153/108243436-17f6b800-711c-11eb-87d1-c174c74adee7.png)

More info regarding Numpy data types is [here](https://numpy.org/doc/stable/user/basics.types.html#basics-types) and dtypes is [here](https://numpy.org/doc/stable/reference/arrays.dtypes.html#arrays-dtypes)

**Comment by glitch** [comment]
I posted & linked a PR for this.  The gist of it is that I was able to update to both 1.20.3, 1.21.5 (and test against older 1.19.2).  The latest numpy at this time is 1.22.0 but it drops support for python 3.7, which we still support, so I stopped at 1.21.5.
