### ISSUE TITLE
CI fails for Python 3.8.8

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#694]
CI Failed in the same place 3 times in a row using Python 3.8.8
Python 3.7 and 3.9 pass, weird...
Here is a link to the failed CI run.
https://github.com/mhmerrill/arkouda/runs/2042148592?check_suite_focus=true

**Comment by hokiegeek2** [comment]
Tested within the chapel 1.23-ubuntu docker image with a Python 3.8.5 virtualenv and the setops_test cases are passing:

![image](https://user-images.githubusercontent.com/10785153/110330157-73191d80-7feb-11eb-9381-b37d33beedde.png)

**Comment by hokiegeek2** [comment]
@mhmerrill it appears there's some kind of race condition as the 3.8 test is now failing again once I take the verbose pytest logging out:

![image](https://user-images.githubusercontent.com/10785153/110619153-759f8280-8165-11eb-8594-cb08cb7e0f01.png)

Please let me know how you'd like for me to proceed.

**Comment by hokiegeek2** [comment]
Switching to INFO-level logging with pytest -s also enables all compat tests to pass:

![image](https://user-images.githubusercontent.com/10785153/110678382-40feeb80-81a4-11eb-8f5a-6a4ee2b002c7.png)

**Comment by hokiegeek2** [comment]
Turning off client logging by running pytest (removing -s argument) and adding calls to repr on both input pdarrays also enabled the 3. 8 tests to pass:

![image](https://user-images.githubusercontent.com/10785153/110681104-6e996400-81a7-11eb-8e0b-63bc5c808ca0.png)

![image](https://user-images.githubusercontent.com/10785153/110681228-9688c780-81a7-11eb-905f-ccbeb1448f92.png)

**Comment by hokiegeek2** [comment]
@mhmerrill This change to setops_test addresses what appears to be a race condition specific to the 3.8 compatibility test as demonstrated in the [action](https://github.com/mhmerrill/arkouda/actions/runs/640468305) triggered in the action.

![image](https://user-images.githubusercontent.com/10785153/110689423-a9ec6080-81b0-11eb-9e57-ede285aa7a02.png)

![image](https://user-images.githubusercontent.com/10785153/110689583-d902d200-81b0-11eb-9c53-387017f0898f.png)

**Comment by mhmerrill** [comment]
Since no one has been able to reproduce the error outside of the CI flow, we decided to disable the Python compatibility checks. FYI we are testing 3.7in the Linux testing and 3.9 in the Mac testing

**Comment by ronawho** [comment]
Capturing some links that may be useful for reproducing.

act lets your run workflows locally. The default config is a light version of the github actions runners but I think you can download a docker image that's almost identical to the runners: https://github.com/nektos/act

tmate is a tool that might let us ssh to runners (but it's not obvious to me if that works for private runners only or the ones that github hosts too):
 - https://dev.to/github/debug-your-github-actions-via-ssh-by-using-tmate-1hd6
 - https://github.com/GitHub30/action-tmate
 - https://github.com/marketplace/actions/debugging-with-tmate

**Comment by hokiegeek2** [comment]
bwhoops, I *thought* I had the compatibility job running, but there's an error (at least now):

![image](https://user-images.githubusercontent.com/10785153/111512887-9bf58d00-8726-11eb-9440-60edcb9026d8.png)
