### ISSUE TITLE
arkouda_server fails on read_hdf when trying to access rank 4 datasets (corrupted size vs. prev_size)

### ISSUE THREAD

**Issue by wolfiex** [Bears-R-Us/arkouda#702]
Using the same file, I am able to list all the datasets and extract values from datasets with shape `Dataset {1/Inf, 101, 545}`, however each time I try to do the same on a variable with shape `Dataset {1/Inf, 47, 101, 545}` the code fails  with 

```*** Error in `/users/xxxx/scratch/arkouda/arkouda_server': corrupted size vs. prev_size: 0x00007fe52806c4c0 ***```

Is there a reason this might be happening. I have increased the available memory to well over what is required, with no luck whatsoever.

**Comment by mhmerrill** [comment]
Are you trying to use a multi-dimensional shape with Arkouda? We don't support that yet. Maybe this is a missed in the error handling. @reuster986 @hokiegeek2

**Comment by mhmerrill** [comment]
@wolfiex people have gotten around this buy rolling their own multi-dimensional wrapper class in python.

**Comment by mhmerrill** [comment]
@pierce314159 @Ethan-DeBandi99 now that we have ArrayView should we revisit this?

**Comment by Ethan-DeBandi99** [comment]
@mhmerrill I would think so. I will touch base with @pierce314159 and see if I can get this functioning properly.

**Comment by Ethan-DeBandi99** [comment]
@wolfiex - would it be possible for you to share your dataset? I am working on making multi-dimensional hdf5 functional in arkouda.
