### ISSUE TITLE
Add Python test for arkouda_server startup with --authenticate flag

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#723]
As a follow up to GH#714 we need to add a test for server start-up with the --authenticate flag.  (Working that bug-fix I started making a larger set of changes to the python testing code and it got big enough to warrant its own ticket.)  @pierce314159 is going to work this ticket with me to get some experience in the code base.

The test will launch an arkouda_server instance with the --authenticate flag and test a connection via client with the `ruok`/`imok` command/response.

**Comment by mhmerrill** [comment]
@Bears-R-Us/arkouda-core-dev does this test cover this issue?
https://github.com/Bears-R-Us/arkouda/blob/master/tests/security_test.py

**Comment by Ethan-DeBandi99** [comment]
@hokiegeek2 - do you have any thoughts on this? @pierce314159 was not 100% sure if it is still required.
