### ISSUE TITLE
Improve performance of `in1d` with large string arrays

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#731]
The current implementation of `segIn1d` is slow when the second array is large. Currently, it constructs a local associative domain from the second array and tests each element of the first array for membership in the domain. Constructing the local domain is probably what is scaling poorly. The analogous `in1d` function for integers switches to a sort-based algorithm for large arrays, so I suspect a similar strategy would be useful here.

**Comment by mhmerrill** [comment]
@reuster986 does this use or should this use sip-hashed string values?

**Comment by reuster986** [comment]
I don't thikn the current implementation uses hashing, but it would probably make sense to implement the sort-based strategy using hashed values.
