### ISSUE TITLE
Improve performance of `tohdfMsg` with strings

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#763]
Writing `ak.Strings` to disk seems quite slow. In a recent session working with 65 million-element arrays on a single locale, writing out a `Strings` array to Lustre was taking 10-12 minutes, whereas an equal-length integer array was taking about 1 second. Since this is single locale, it's probably nothing to do with data movement or communication, and should be pretty easy to test. Probably the first thing to do is write a benchmark in Chapel and then start adding timing statements.

**Comment by hokiegeek2** [comment]
Testing this now and I am seeing an array index out of bounds error with a single locale, opening up a new issue:

![image](https://user-images.githubusercontent.com/10785153/115380549-acbf7580-a1a0-11eb-9537-de8f464b763b.png)

The error occurs here:

![image](https://user-images.githubusercontent.com/10785153/115380758-e98b6c80-a1a0-11eb-9337-f217789a1c3d.png)

**Comment by hokiegeek2** [comment]
Opened new [issue](https://github.com/mhmerrill/arkouda/issues/767) for bug

**Comment by hokiegeek2** [comment]
Comparing the pdarrray vs Strings creation and tohdf times, it appears that, for the ranges I studied, the Strings creation times started off over two orders of magnitude longer than for int pdarrays, with the gap increasing to three orders of magnitude. For example, for 1 million ones and 1 million strings, the corresponding Strings object takes 352% longer than the pdarray, and the gap widens to over 1200% for 10 million length Strings vs pdarrays.

Similarly, the Strings save times start off over two orders of magnitude longer than pdarrays, with the gap widening to 3 orders of magnigute . For 1 million long pdarray and Strings objects, the Strings object takes roughly 800% longer, while for 10 million long pdarrays and Strings the gap increases to approximately 1800%.

![image](https://user-images.githubusercontent.com/10785153/115433203-486ad900-a1d5-11eb-86a1-d219b6da7837.png)

**Comment by hokiegeek2** [comment]
Added bypass logic to the  [write1DDistStrings](https://github.com/hokiegeek2/arkouda/blob/fa67284791b6342bf84ad5babc6f7a95b1d992b9/src/GenSymIO.chpl#L1237) function if the numLocales == 1

![image](https://user-images.githubusercontent.com/10785153/115613101-fea7ee80-a2b9-11eb-9ea8-5684fe785dd7.png)

Following this change, the 10 million-long Strings object write to HDF5 on one locale takes 23 seconds:

![image](https://user-images.githubusercontent.com/10785153/115613270-32831400-a2ba-11eb-8da4-211cb9a9e64c.png)

so the iterative shuffle logic required to address strings (char segments) spanning multiple locales in both directions is the performance bottleneck.

**Comment by hokiegeek2** [comment]
Testing with save of a Strings object 10 million in size on a 3 locale Arkouda instance:

![image](https://user-images.githubusercontent.com/10785153/115730569-6ad73080-a354-11eb-9140-5ee5d89eb812.png)

Of the nearly 400 seconds to save to hdf5, 256 seconds is spent in the generateValuesMetadata function across all locales. The generateValuesMetadata function generates the Strings bytes array metadata required to partition complete string char sequences across the locales. The generateValuesMetadata function is by far the most time-consuming element of Strings.save

Approximately 30 seconds is spent in the adjustForLeadingSlice function, which removes chars from the current locale that were shuffled to the previous locale to complete the last string in the previous locale, creating and returning a new values (chars) list as well as a corresponding segments list.

17 seconds is spent in converting the bytes array to a char list and corresponding segments list.

About 3 seconds is spent writing the values and segments lists to hdf5

The remaining sixty seconds is unaccounted for and needs to be instrumented. But, for now, there are several optimization candidates.

**Comment by hokiegeek2** [comment]
Have the generateValuesMetadata down to 146 seconds from 250 and the overall write time down to 180 seconds:

![image](https://user-images.githubusercontent.com/10785153/116078528-ba737000-a664-11eb-9041-2bb99b381398.png)

**Comment by hokiegeek2** [comment]
removed some debugging messages and got write down to 115 seconds:

![image](https://user-images.githubusercontent.com/10785153/116083524-ac285280-a66a-11eb-89ba-60486a9ee96e.png)

**Comment by hokiegeek2** [comment]
@reuster986 Latest version can write a 10-million Strings object on a 3-locale Arkouda cluster in 36 seconds:

![image](https://user-images.githubusercontent.com/10785153/116282347-a315af00-a758-11eb-9fcf-56280bdf2731.png)

The biggest time sink was generateValuesMetadata. I refactored it so that it does not have to iterate through the local slices.

**Comment by hokiegeek2** [comment]
The next area to investigate is the shuffle step. As @reuster986 pointed out, replacing Chapel lists with arrays will likely improve performance quite a bit.

**Comment by hokiegeek2** [comment]
The refactoring where I replaced list generation with slicing arrays resulted in the following error for 10 milion-length String on a 3-locale cluster:

![image](https://user-images.githubusercontent.com/10785153/117350436-8d9c3580-ae7a-11eb-945e-72968d8d0def.png)

In this section of code:

![image](https://user-images.githubusercontent.com/10785153/117350535-ad335e00-ae7a-11eb-9fdc-f04a85a5c58f.png)

**Comment by hokiegeek2** [comment]
As of the current version a write of a 10 million length Strings object on a 3-node cluster is ~ 15 seconds:

![image](https://user-images.githubusercontent.com/10785153/117802736-d3af1b80-b223-11eb-8001-c5868929dd08.png)

The most expensive operation now is extending the character list with locale slices:

![image](https://user-images.githubusercontent.com/10785153/117803038-2d174a80-b224-11eb-8c48-9bed73da3f51.png)

**Comment by hokiegeek2** [comment]
After removing the majority of the timing statements, I have the 10 million Strings write on a 3-node Arkouda cluster on AWS down to ~ 8 seconds:

![image](https://user-images.githubusercontent.com/10785153/117960868-78486080-b2eb-11eb-8a8c-d63ea10050e2.png)

**Comment by reuster986** [comment]
I'm going to close this for now. If we want to revisit string write performance, we can reopen or start a new issue.
