### ISSUE TITLE
Type Aliasing

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#778]
The goal of this proposal is to make arkouda more readable, maintainable, and stable by using type aliases. Many arkouda functions are generic, in the sense that they are designed to accept multiple types of arguments. Examples:
- Functions like `arange`, `randint`, and `zeros` take scalars from both python and numpy, possibly of both int and float type.
- `GroupBy` should accept `int64` `pdarray`, `Strings`, `Categorical`, or a list/iterable of any combination of these. 
- Almost every function that accepts `ak.Strings` should also accept `ak.Categorical`, because they are designed to be interchangeable.

The current type checking in arkouda relies on explicit lists of allowed types for each function argument. Using type aliases in place of explicit type lists would have the following advantages:
- Function signatures would be more readable by users (e.g. in Jupyter using Shift+Tab or '?'), with a descriptive type name like `Groupable`, rather than `Union[List[Union[pdarray, Strings, Categorical]], Union[pdarray, Strings, Categorical]]`
- The code would be more maintainable, because type updates would be localized to the alias definition, rather than requiring updates to dozens of source files
- Type aliasing would guard against incorrect type annotations, like overly restrictive type checking (see #777 ), where a type that should be allowed is mistakenly omitted from a list.

If we choose to move to type aliasing, probably the first thing we should do is look through the source code, compile a list of  type aliases that we should have, and agree on their definitions. Then someone can replace all explicit type lists with the aliases.

- [ ] Compile and define type aliases
- [ ] Replace explicit types with aliases

**Comment by reuster986** [comment]
PR #845 implements type aliasing for `GroupBy`, which is probably the most complicated case, and the source of most of the type-related issues I've seen. Question for the group: should we close this issue, or go through and implement type aliasing more thoroughly?

**Comment by hokiegeek2** [comment]
@reuster986 In general I vote yes for aliasing. We are already doing aliasing with scalars and can do the same in some case you mentioned above. For methods that accept scalars, Strings/Categoricals/pdarrays as well as Iterables of each, not sure.

**Comment by glitch** [comment]
This may only be semi-related, but the `multidispatch` module (https://github.com/mrocklin/multipledispatch) may be helpful here.

It lets you annotate functions with the same name but with different arg types to handle dispatch to the proper func based on type.  We might be able to clean up a lot of the conditional logic going on when we have many types in the input args etc.

**Comment by mhmerrill** [comment]
@Bears-R-Us/arkouda-core-dev  is what we have currently good enough to close this?

**Comment by reuster986** [comment]
I think we're doing pretty well here.
