### ISSUE TITLE
.nunique aggregation slow on IB

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#780]
Testing arkouda on an IB cluster, performance looks good overall, but one case where it gets hung up is in `GroupBy.nunique()`, which calls `src/ReductionMsg.chpl:segNumUnique` under the hood. This works fine on XC, so I'm thinking we just missed an opportunity for aggregation in this function somewhere. However, the function itself is fairly old and unnecessarily complex -- I should know because I wrote it :) -- so it is probably time for a replacement.

I propose two stages:
- [x] Write a python-side method that performs nunique via another groupby:
```python
class GroupBy:
...

    def nunique(self, vals):
        uksize = ... # get length of self.unique_keys
        ukidx = self.broadcast(ak.arange(uksize), permute=True)
        # Find unique pairs of (key, val)
        g = GroupBy([ukidx, vals])
        # Group pairs again by keyidx 
        g2 = GroupBy(g.unique_keys[0], assume_sorted=True)
        # Count number of unique vals per keyidx
        _, nuniq = g2.count()
        # Re-join unique counts with original keys (sorting guarantees same order)
       return self.unique_keys, nuniq

    def aggregate(...):
        # Insert special case to handle 'nunique' by calling above method instead of sending a server message
```

- [ ] Once the above is stable, port the logic over to a new Chapel function. This would greatly benefit from making some arkouda behaviors available as pure Chapel functions that can be called on Chapel arrays (or a custom array class), like:
  - broadcast
  - gather (`array[indices]` and `array[mask]`)
  - findSegments, or `ediff`, or whatever we want to call it
  - coargsort

**Comment by reuster986** [comment]
@hokiegeek2 had you started working on this yet, or am I ok to take over?

**Comment by hokiegeek2** [comment]
@reuster986 I have not so, feel free to take this on

**Comment by reuster986** [comment]
PR #845 addresses the first half of this issue. I'm thinking of rolling the second half into a broader issue about refactoring groupby, findSegments, and unique.
