### ISSUE TITLE
Discussion about `pdarray` for strings in symbol table as well as possible other arrays

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#786]
Maybe we should extend the base symbol table to include `pdarray`s of other types like `strings` as well as maybe `complex` or `timestamp `. This to me makes a lot of sense as a step toward making a symbol table of more complex objects.

**Comment by hokiegeek2** [comment]
👍

**Comment by mhmerrill** [comment]
We might want to make a stab at making `SegString` a subclass of `GenSymEntry` or something like that.

**Comment by hokiegeek2** [comment]
@mhmerrill may not be a bad idea to capture in the  [wiki](https://github.com/mhmerrill/arkouda/wiki/String-pdarrays-in-Symbol-Table-Design-Discussion---Notes) all the functional and system requirements driving this issue.

One possible element of this could be a composite key that encapsulates all the metadata required to link elements of complex objects such as Strings (in this case, the chars and segments pdarray ids).

**Comment by glitch** [comment]
Hi all, sorry for the commit spam.  I have a working implementation using a new `SegStringSymEntry:GenSymEntry` which is a composite entry of the previous offsets/bytes (aka segments/values) previously used by the Strings construct.  Check it out here: https://github.com/Bears-R-Us/arkouda/pull/819

Also, I'm putting together a wiki entry (https://github.com/Bears-R-Us/arkouda/wiki/SegStringSymEntry-to-encapsulate-Strings-as-single-entity) on some of the implementation details and common patterns & problems I was able to discover by tracing out the various usages in the code. 👍
