### ISSUE TITLE
GroupBy rate decreases for large problem sizes on IB

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#793]
On 16 nodes of 128-core/2TB AMD with IB, the rate of the groupby benchmark peaks at a problem size of 10**9 elements/node for < 8 arrays and then falls off. All rates below are in GiB/s.

| elem/node | 1-array rate | 2-array rate | 8-array rate | 16-array rate |
| ------ | ---------- | ------- | ------ | -------- |
| 10**6 | 0.0953 | 0.0544 | 0.0163 | 0.0065 |
| 10**7 | 0.8931 | 0.6009 | 0.1716 | 0.0664 |
| 10**8 | 3.8745 | 3.1622 | 1.0653 | 0.5642 |
| 10**9 | 5.8647 | 5.0061 | 3.1355 | 2.7681 |
| 10**10 | 4.5569 | 3.525 | 3.1916 | 3.0995 |

This performance dropoff after 10**9 is not observed with coargsort, gather, or scan, which are the main kernels used in groupby.

**Comment by ronawho** [comment]
Just wanted to note that I believe I have been able to reproduce this on an internal machine. I think it's a bit different from your machine. Mine has 128-core AMD CPUs, faster IB, 512 GB of ram and only 8 nodes are available at the moment. The memory limit prevents me from running `10**10`, but I can use 3/4 of that for the 1-array version. Here's what I see:

| size       | 1-array rate |
| ---------- | -----------: |
| 750000     | 0.0598 GiB/s |
| 7500000    | 0.5393 GiB/s |
| 75000000   | 3.1262 GiB/s |
| 750000000  | 6.1954 GiB/s |
| 7500000000 | 5.1889 GiB/s |

**Comment by ronawho** [comment]
For me this seems to start around 4.2B elements:

```
$ ./benchmarks/run_benchmarks.py groupby -nl 8 --size=4000000000
1-array Average time = 36.3968 sec
1-array Average rate = 6.5505 GiB/sec

$ ./benchmarks/run_benchmarks.py groupby -nl 8 --size=4200000000
1-array Average time = 37.2988 sec
1-array Average rate = 6.7117 GiB/sec

$ ./benchmarks/run_benchmarks.py groupby -nl 8 --size=4400000000
1-array Average time = 42.7702 sec
1-array Average rate = 6.1319 GiB/sec
```

I was originally wondering if after a certain point the CPU can no longer boost or has to go to a lower frequency, but 4B elements for multiple trials does not decrease performance so that's probably not it.

I'll work on gathering some subtimers to try and understand where the time is going better.

**Comment by ronawho** [comment]
Ah, so I think this is just an artifact of the benchmark. The element values in the array are based on the array length, so as the the array gets bigger the element values increase, which at some point pushes us from 2 to 3 rounds of radixsort. 


If I change:

https://github.com/Bears-R-Us/arkouda/blob/2b0b33186ace57448afad330d7f48a4d4b9961d4/benchmarks/groupby.py#L13-L16

to do 

```python 
a = ak.randint(0, 2**32, N//numArrays, seed=seed)
```

I no longer see the perf dropoff. Conversely if I change the argsort benchmark to follow groupby I do see the dropoff.

**Comment by ronawho** [comment]
So I think this is good news. There's no true regression or anything IB specific here (you'd see this on XC but you'd probably need more nodes to get the array size large enough)

I'd be inclined to change groupby (and aggregate) to not base the element values off the array size, but I'll defer to you.

**Comment by reuster986** [comment]
Wow, excellent catch! Good news indeed :)

I am on board with your recommendation, especially since the current sort implementation does not depend at all on the number of groups.
