### ISSUE TITLE
__iter__ for pdarray, Strings, and Categorical

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#795]
I noticed that `pdarray` and `Strings` have not implemented `__iter__` methods. I wasn't sure if this is to discourage users from iterating over these presumably large arrays on client side or if this just hasn't been implemented yet

For example:
```python
>>> mystr = ak.array(['a', 'b', 'c'])
>>> for char in mystr:
        print(char)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/arkouda/arkouda/strings.py", line 106, in __iter__
    raise NotImplementedError('Strings does not support iteration')
NotImplementedError: Strings does not support iteration
```
This can be worked around by doing either using `to_ndarray()` (which has a built-in size limit):
```python
>>> for char in mystr.to_ndarray():
        print(char)  
a
b
c
```
or by indexing the Strings/pdarray object directly:
```python
>>> for i in range(len(mystr)):
        print(mystr[i])
a
b
c
```
I was wondering if others thought it would be best to either:
- implement `__iter__` methods for these classes
- change the error message to say something like `__iter__` has not been implemented since Strings/pdarray objects can be quite large and `to_ndarray` should be called to iterate over them
- or leave it as is? 

My main concern is a user new to arkouda will probably default to indexing these objects directly before calling `to_ndarray` on them if not pointed in the right direction

**Comment by hokiegeek2** [comment]
@pierce314159 Yes, __iter__ is not supported for Arkouda pdarrays, Strings, or Categoricals. Adding more detail to the error message sounds fine to me. 👍
