### ISSUE TITLE
Update README "Arkouda docs at Github Pages" to proper link

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#801]
The hyperlink pointing to the Github Pages arkouda documentation is out of date now that the repo has move to Bears-R-Us organization.  It needs to be updated to link to the proper location

```[Arkouda docs at Github Pages](https://mhmerrill.github.io/arkouda)```

The link should be:  ```https://bears-r-us.github.io/arkouda/```

(This is a good first issue for someone wanting to make sure they have their fork set up correctly and know how to issue a Pull Request against the main project.)

**Comment by mhmerrill** [comment]
oops I guess I ran into this and then submitted a PR #803
