### ISSUE TITLE
fix failing datetime unit test due to pandas version API change

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#814]
In latest pull from master a Pandas API-related error occurs in the pytest test harness: 

![image](https://user-images.githubusercontent.com/10785153/118962847-d0a6e000-b933-11eb-8356-45579083efe7.png)

I have pandas 1.1.0 installed on my system:

![image](https://user-images.githubusercontent.com/10785153/118963230-3e530c00-b934-11eb-8063-16b093bc6d57.png)

The datetime_test passes w/ pandas 1.2.0:

![image](https://user-images.githubusercontent.com/10785153/118964771-e0bfbf00-b935-11eb-9ebe-8414e2c0a214.png)

And all remaining tests pass with pandas 1.2.0:

![image](https://user-images.githubusercontent.com/10785153/118965044-37c59400-b936-11eb-85d9-f26f14be9134.png)

**Comment by glitch** [comment]
Side note, looks like Pandas added support for it here: https://github.com/pandas-dev/pandas/pull/37436 in the 1.2.0 release (https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.2.0.html)

**Comment by reuster986** [comment]
Hey guys, @mhmerrill and I talked about it, and we're hesitant to require a certain pandas version just for a unit test.

Actually, looking at the unit test itself, it should be calling `.std()` on a `Timedelta`, rather than a `Datetime`. If we change that line in the unit test to:

```python
pd_timedel_std = pd.to_timedelta([123, 456, 789], unit='s').std()
```

Does that eliminate the error?

**Comment by hokiegeek2** [comment]
@reuster986 it does indeed. I will remove this PR and do a new one to fix the unit test failure

**Comment by reuster986** [comment]
Thanks @hokiegeek2 !

**Comment by mhmerrill** [comment]
this can be closed
