### ISSUE TITLE
Enable `ak.read_all()` to ignore/warn of bad files

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#821]
Currently, `ak.read_all(filenames)` will raise an error if any file has any of the following issues:
* permission error
* bad HDF5 header
* missing dataset/column
* dataset with incorrect dtype

In some use cases, there are so many files that the likelihood of one of them having an issue is high, and we don't always want `ak.read_all` to hard fail in that condition. We should make a keyword arg, like `ak.read_all(filenames, errors='warn')` that will warn the user of problematic files but skip over them and read the remaining files anyway. The warning message should contain the number of bad files and the corresponding filenames, so the user can investigate.

**Comment by hokiegeek2** [comment]
👍 agree, this would be a nice, time-saving enhancement

**Comment by mhmerrill** [comment]
@glitch maybe you could tackle this in conjunction with #834

**Comment by glitch** [comment]
One thing I noticed is that the client no longer calls the single `readhdf` -> `readhdfMsg` path; [see here](https://github.com/Bears-R-Us/arkouda/blob/91ba907e6c57798382ce324298f6661f4f5cad77/arkouda/pdarrayIO.py#L78).  It looks like that was changed in Feb2020, see commit e2324284d8204b032cea340ff6b9b71d68c90ee7

For now I'm going to mark the various code sections as DEPRECATED, but it looks like we can remove the server side `readhdfMsg` proc in GenSymIO along with the associated bits leading to it:

- arkouda_server.chpl -> cmd routing section
- GenSymIO.chpl -> readhdfMsg
- UnitTestStringType.chpl -> will need update to readAllHdf version
- io_test.py -> associated unit tests can be removed

If you think it should be removed in this round, let me know.

**Comment by glitch** [comment]
In creating a client side unit test for this, I ran into an interesting problem.  The client `pdarrayIO.py::read_all` function makes a call to `pdarraIO.py::get_datasets` when the datasets option is `None`.  This in turn makes a server request `ls_hdf` on the first file.

`ls_hdf` throws a RuntimeError if it can't read the file, so it looks like we'll need to keep trying files until we can find a _good one_.
