### ISSUE TITLE
Support writing `ak.Categorical` to HDF5

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#822]
Add an `ak.Categorical.save()` method, similar to `ak.Strings.save()`. The method signature should be:

```python
def save(self, prefix_path : str, name : str='categorical_array', mode : str='truncate')
```

And the layout of the resulting HDF5 file should look like:

```
<name>               Group
    categories       Group
        segments     Dataset (int64)
        values       Dataset (uint8)
    codes            Dataset (int64)
```

I haven't tried yet, but I think this could be accomplished by creating a HDF5 group in Chapel with the user-specified name, then in Python calling 
```python
cat.categories.save(prefix_path+'/'+name, dataset='categories')
cat.codes.save(prefix_path+'/'+name, dataset='codes')
```

**Comment by glitch** [comment]
@ezfman I was thinking of picking this ticket up since it looks like it may have stalled, are you still working it?  Let me know, thanks!

**Comment by ezfman** [comment]
@glitch go for it; I got sucked down a rabbit hole thinking about associated data stored in different ways via HDF5.  I'll try to get this done quickly.

**Comment by mhmerrill** [comment]
@glitch I am assigning this to you now, please contact @ezfman and continue/leverage his work or create your own.

**Comment by glitch** [comment]
PR 898 was submitted for this issue.
