### ISSUE TITLE
 GroupBy.nunique() fails on Categorical.from_codes()

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#825]
I ran into the following bug while working Issue #692 
```python       
cat = ak.Categorical.from_codes(codes=ak.array([0, 1, 0, 1, 2]), categories=ak.array(['a', 'b', 'c']))
i = ak.arange(cat.size)

cat_group = ak.GroupBy(cat)
cat_labels, cat_values = cat_group.nunique(i)
```
calling nunique on a `Categorical.from_codes()` results in a `TypeError`

This only seems to impact `Categorical`s made using `.from_codes()` because the following runs fine
```python
cat = ak.Categorical(ak.array(['a', 'b', 'a', 'b', 'c']))
i = ak.arange(cat.size)

cat_group = ak.GroupBy(cat)
cat_labels, cat_values = cat_group.nunique(i)
```

This seems similar to Issue #777, so I expect this is the result of overly restrictive typing in `aggregate`

**Comment by hokiegeek2** [comment]
@pierce314159 I will look into this first thing tomorrow (like 0530)

**Comment by pierce314159** [comment]
> 
> 
> @pierce314159 I will look into this first thing tomorrow (like 0530)

@hokiegeek2  Okay! Thank you!

**Comment by hokiegeek2** [comment]
@pierce314159 working this...definitely a tricky one

**Comment by hokiegeek2** [comment]
@pierce314159 I added 'Categorical' (needs to be in quotes due to circular dependencies between groupbyclass and categorical) as a return type:

![image](https://user-images.githubusercontent.com/10785153/119822084-43c6ce00-bec1-11eb-9e3e-3a798c4967f1.png)

However, this causes a NameError:

![image](https://user-images.githubusercontent.com/10785153/119822254-71137c00-bec1-11eb-8380-efb285e5dafa.png)

We are using the __future__ annotations for parameter type checking within groupbyclass.GroupBy and that works fine, but it appears to be problematic in a return clause. That's what I am investigating now.

**Comment by hokiegeek2** [comment]
@pierce314159 One interesting thing I determined is that this import clause is unneeded:

![image](https://user-images.githubusercontent.com/10785153/119823994-6ce85e00-bec3-11eb-85f7-9df6a9f39c7c.png)

![image](https://user-images.githubusercontent.com/10785153/119824070-8093c480-bec3-11eb-8f1a-4e5b766b0931.png)

**Comment by hokiegeek2** [comment]
@pierce314159 Okay, an immediate fix is to widen the scope of the return tuple[0] reference to typing.Any:

![image](https://user-images.githubusercontent.com/10785153/119824995-7faf6280-bec4-11eb-85b0-44f19e18c5a4.png)

![image](https://user-images.githubusercontent.com/10785153/119825253-c309d100-bec4-11eb-9f2d-46c85f70ce83.png)

@reuster986 this may be a good middle ground of some sorts between duck typing and more stringent type checking for certain use cases where (1) the parameter and/or return types can vary significantly and (2) dynamic elements of the Arkouda API that will likely evolve in the future type-wise

**Comment by hokiegeek2** [comment]
However...debugging a pytest error that occurs when all tests are run but not when registration_test is run individually:

![image](https://user-images.githubusercontent.com/10785153/119827367-07966c00-bec7-11eb-92a9-98c206e76770.png)

**Comment by hokiegeek2** [comment]
This is really odd. I can get registration_test to fail consistently on a line that has nothing to do with the test:

![image](https://user-images.githubusercontent.com/10785153/119835922-492b1500-becf-11eb-9d4e-dd9165d6bbd2.png)

ak.ones is invoked many times in the pytest test harness:

![image](https://user-images.githubusercontent.com/10785153/119836260-97d8af00-becf-11eb-8829-a85379df7d16.png)

**Comment by hokiegeek2** [comment]
And now I've tested 5 times in a row and no longer seeing this error. This looks like a race condition of some sorts and it may be related to the order of tests:

![image](https://user-images.githubusercontent.com/10785153/119839582-467def00-bed2-11eb-8949-b8fd7fcbb3ba.png)

![image](https://user-images.githubusercontent.com/10785153/119839687-5990bf00-bed2-11eb-9f9c-168efa3d12b6.png)

**Comment by hokiegeek2** [comment]
@pierce314159 @reuster986 I am gonna submit a PR for this so that Pierce can get back to his immediate task and I'll look a bit further into other possible options. Sound good?
