### ISSUE TITLE
PEP-8 and auto formatting?

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#837]
I think we should consider formatting our python code to adhere to [PEP-8 style guide](https://www.python.org/dev/peps/pep-0008/). This is the style guide most projects follow

Some major benefits of adopting PEP-8 are:

- Increased readability for new developers or users wanting to take a look at how things are implemented since PEP-8 is so widely adopted
- Consistent formatting within the code base
- More emphasis on functionality changes than formatting in future code reviews/PRs

Going a step further, I think there's a good argument to use an auto formatting tool like [Black](https://github.com/psf/black). Black follows all the PEP-8 rules with some extra for reasons like determinism and smaller diffs. Some benefits of using black:

- Everyone can write code however they like 
- Code is formatted in a way to minimize diffs, making code review easier because diffs will be actual functionality changes instead of formatting changes
- Abstract Syntax Trees are used to verify the formatted code is effectively equivalent to the original
- Widely adopted:
  - Used by many open-source projects including pytest and pandas
  - Used by organizations including Facebook, Dropbox, Mozilla, Quora
- We could add a check for black formatting to the CI to ensure that the entire codebase is formatted uniformly 

One thing to note, Black is still in beta. This is what they have to say on their github about that:
"What this means for you is that until the formatter becomes stable, you should expect some formatting to change in the future. That being said, no drastic stylistic changes are planned, mostly responses to bug reports."

There's a [Black Playground](https://black.vercel.app/) if you want to get a feel for how it formats things

What do y'all think about this? I think it'll be a fair amount of upfront changes, but increased readability, more efficient code reviews, and being in line with best practices are likely worth it

**Comment by pierce314159** [comment]
A potential compromise on trying black out but not changing the entire code base is to use something like darker which applies black only to regions modified by the developer

https://github.com/akaihola/darker
https://dev.to/akaihola/improving-python-code-incrementally-3f7a

To me the main drawback of this is we'd actually see more distracting formatting changes per PR. Another idea is to apply black on a few files at a time and see if it's something we think works well for us?

**Comment by glitch** [comment]
A previous project I worked on did this and while there were some initial bumps, in the end it worked out really well as long as we had a formatting guide/settings included in the repo (in this case it's PEP8 which is public and `black` would handle the heavy lifting for most people).

If we go this route, the next question is how to apply it and make sure it gets continually applied?  I _think_ the general internet consensus is to have a _linter_ configured to fail a build on bad formatting... which it looks like we have one already to check for tabs in chapel code so it shouldn't be much of a problem to set one up for the python code.

For what it's worth I'm pro-consistent formatting, it's one less thing to worry about once everyone is on the same page.

**Comment by mhmerrill** [comment]
This subject has been touched on before in #168

**Comment by pierce314159** [comment]
I'm gonna go ahead and close this since there hasn't been much movement on it. I still think an autoformatter would be worthwhile since it would be one and done. But I think a good middle ground is to explicitly lay out our coding standards (PEP8 for python, etc). This is covered by #1301
