### ISSUE TITLE
Uncaught Chapel Logging Error

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#847]
There is a user who is getting an uncaught BlockingIOError when calling `ak.read_all()` on a list of several thousand filenames. The error is thrown by a Chapel function and somehow not caught in the main server loop. Sanitized text of the terminal output:

```
uncaught BlockingIOError: Resource temporarily (in channel.flush with path "pipe:[<somenumber>]" offset <othernumber>)
$ARKOUDA_HOME/src/Logging.chpl:52: thrown here
$ARKOUDA_HOME/src/arkouda_server.chpl:168: uncaught here
```

Throwing function:
https://github.com/Bears-R-Us/arkouda/blob/e9053141904bbb462f29a6ada346272692d9d15e/src/Logging.chpl#L48-L54

Non-catching function:
https://github.com/Bears-R-Us/arkouda/blob/e9053141904bbb462f29a6ada346272692d9d15e/src/arkouda_server.chpl#L161-L173

I think we should do two things:
1. Add a `throws` to the signature of `sendRepMsg`, so that errors will be passed up to the big try/catch in the main server loop.
2. Add logic in all the `Logger` methods to gracefully handle logging errors that do not affect the actual computation, so that the user's workflow can proceed uninterrupted.

The first is a safety net to ensure that the server doesn't crash, but the second is necessary because logging failures should not really interrupt execution.

**Comment by hokiegeek2** [comment]
@reuster986 I'm on it

**Comment by hokiegeek2** [comment]
@reuster986 submitted [PR](#849)

**Comment by hokiegeek2** [comment]
@pierce314159 I believe so, but that's Mike's or Bill's call
