### ISSUE TITLE
Limit Length of Logging Lines

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#848]
Above alliteration is assuredly accidental.

This is related to the error in #847 . I speculate that the cause of that error was that the logger was trying to write several thousand filenames to the terminal and immediately flush stdout. While #847 aims to tighten up error handling for logging, I think we should also impose a limit on the size of messages that get logged, similar to how we do not log the binary data that gets transferred with `ak.array()` and `.to_ndarray()`. The code that logs incoming commands and their args is here: 

https://github.com/Bears-R-Us/arkouda/blob/e9053141904bbb462f29a6ada346272692d9d15e/src/arkouda_server.chpl#L262-L274

I propose we set a threshold for the length of `args`, and if it exceeds that threshold, only print out [first N characters `...` last N chars]. This will not only help avoid logging errors, but will also make the logs more readable.

**Comment by pierce314159** [comment]
I've put up a PR (#890) for this issue. @mhmerrill left a comment which I'm copying here so the discussion isn't tied to PR (in case it gets closed):
> I am unsure about limiting all logging lines because we parse these lines with a script sometimes. Maybe a intermediate solution is to limit the number of filenames from the I/O calls. I am open to discussion about this. 

@reuster986, what do you think about this approach?
