### ISSUE TITLE
CI workflow build failures on mypy & doc targets

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#852]
It looks like the CI workflow actions are failing again for `mypy` and `doc` targets, this time due to an hdf5 issue.

To test/reproduce I created a one line change to the README.md to trigger a build on my fork.  You can see the failures here:
https://github.com/glitch/arkouda/actions/runs/961367325

The error message for both `mypy` and `doc` actions was
```
    Loading library to get build settings and version: libhdf5.so
    error: Unable to load dependency HDF5, make sure HDF5 is installed properly
    error: libhdf5.so: cannot open shared object file: No such file or directory
```

All other actions work just fine.

**Comment by ronawho** [comment]
Weird. The docs and mypy CI tests don't install hdf5 since I couldn't imagine what would require them. Does the following patch seem to work:

```diff
diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
index 228d7b3..58a5585 100644
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -22,7 +22,7 @@ jobs:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: |
-        apt-get update && apt-get install -y python3-pip
+        apt-get update && apt-get install -y libhdf5-dev hdf5-tools libzmq3-dev python3-pip
         python3 -m pip install -e .[dev]
     - name: Arkouda mypy
       run: |
@@ -36,7 +36,7 @@ jobs:
     - uses: actions/checkout@v2
     - name: Install dependencies
       run: |
-        apt-get update && apt-get install -y python3-pip
+        apt-get update && apt-get install -y libhdf5-dev hdf5-tools libzmq3-dev python3-pip
         python3 -m pip install -e .[dev]
     - name: Arkouda make doc
       run: |
```

**Comment by glitch** [comment]
@ronawho Yes that's what I ended up doing; it looks like it works: https://github.com/glitch/arkouda/actions/runs/961546918

It's a head scratcher why it seemingly _broke for no reason_

**Comment by mhmerrill** [comment]
You need at least the Python install because of autoapi for the doc flow.

**Comment by glitch** [comment]
[PR-853](https://github.com/Bears-R-Us/arkouda/pull/853) addresses the immediate issue.
