### ISSUE TITLE
`a[mask] = b` fails silently when b and mask are incompatible

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#869]
Reproducer:

```python
a = ak.zeros(10)
mask = ak.arange(10) < 5
b = ak.ones(10)
a[mask] = b  # Should raise ValueError but doesn't
a
array([0 0 0 0 0 0 0 0 0 0])
# Nothing set in a
```

The third line should raise a ValueError, because `mask` only has 5 `True`s and `b` has 10 values, which is illegal. However, instead of raising a ValueError, it just returns as if everything is ok, without changing `a` at all.

In the server log, the `repMsg` does start with `"Error: "`, so the client is not picking it up somehow.

**Comment by hokiegeek2** [comment]
Fixed it: 

![image](https://user-images.githubusercontent.com/10785153/124644163-f181b100-de5f-11eb-99b6-001892962af0.png)

There was some inconsistent data handling that needed to be cleaned up.
