### ISSUE TITLE
Memory Limit Misleading in printServerSplashMessage

### ISSUE THREAD

**Issue by ezfman** [Bears-R-Us/arkouda#878]
In the `arkouda_server.chpl` script, locale memory limit is displayed using `Memory.Diagnostics.locale.phsyicalMemory()`, but the number of locales is not indicated--this kind of information is useful for arkouda users.

**Comment by glitch** [comment]
Just a note, there is a user/client facing way to get this information:
```
import arkouda as ak
ak.connect("localhost")

# Print the configuration information
cfg = ak.get_config()
cfg["numLocales"]
cfg["pyhsicalMemory"]

# direct shot
ak.get_config()["numLocales"]
```

**Comment by ezfman** [comment]
That's good to know @glitch ; it will definitely be useful moving forward!

**Comment by reuster986** [comment]
@ezfman can we close this, since the number of locales is available through the client API?
