### ISSUE TITLE
Better Json support for client/server messages

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#888]
After a conversation with Mike we decided to open an issue to implement better arkouda support for passing messages in json from both the client and server.  This is a multi-part issue and we will need to

- [ ] Create a helper class to more generally parse and create json messages on the Chapel side with better list and dictionary support.  Note: Chapel already has some json support to help with this so we need to better understand what it supports and where it doesn't fit our needs (i.e. turning a list of complex objects into json may not do what we expect it to do.. or we may need to add methods to some of our existing classes to enable better support).
- [ ] Start with a simple set of messages to change into full json on both sides
- [ ] Create a general schema we want to follow and try to standardize our key names along with the expected set of keys everything should have (i.e. data_type, cmd, etc.)

We talked about whether we want to stick with general `Map<String, String>` where the value would itself be just another blob of json (i.e. serialized object) or whether we wanted to make some type of `Map<String, GenericValue>` where we could subclass GenericValue with specific versions kind of like the pattern in the SymTab / GenSymEntry|SymEntry.  We decided to play around with it a bit to see which works best for us.

**Comment by glitch** [comment]
Note: Improvements to Chapel's json impl were documented in https://github.com/chapel-lang/chapel/issues/18156

**Comment by Ethan-DeBandi99** [comment]
Added recommend closing tag here because we have added JSON support for message arguments and are in the process of updating individual messages to use it.

@pierce314159, @joshmarshall1, @mhmerrill - do agree with closing this issue?

**Comment by hokiegeek2** [comment]
@Ethan-DeBandi99 I vote to close.
