### ISSUE TITLE
Duplicate pdarray return name causing some "unknown symbol" errors

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#900]
https://github.com/Bears-R-Us/arkouda/blob/6ecd185cb695a13c3b5e43e3d6e80285e7afd9c5/src/FindSegmentsMsg.chpl#L107

The `findSegments` command is supposed to return two pdarrays (segments and unique_key_indices), but in the case of zero-length input, the above code accidentally returns the attributes of the same array twice. In the client, these both get instantiated as pdarray objects with the same server-side name, but one of them goes out of scope fairly quickly and calls "delete" on the server side. Meanwhile, the other array gets saved as the `.segments` attribute of the `GroupBy`, and the next time it is referenced, the server complains about an unknown symbol.

Here's a reproducer:
```python
g = ak.GroupBy(ak.zeros(0, dtype=ak.int64))
g.segments
[unknown symbol error]
```

I suspect that our other elusive unknown symbol errors have a similar cause. Maybe we should create a DEBUG mode for `create_pdarray()` or `pdarray.__init__()` that checks whether the name is already used in the server? This check should probably not be turned on by default, since it would add a lot of overhead to array creation, but maybe just for the CI, or so that we can spot check.

**Comment by glitch** [comment]
Looks like the issue is inside [this block](https://github.com/Bears-R-Us/arkouda/blob/6ecd185cb695a13c3b5e43e3d6e80285e7afd9c5/src/FindSegmentsMsg.chpl#L100) at line 107 where the second created portion should be `n2` instead of `n1`
```
        if (size == 0) {
            // Return two empty integer entries
            var n1 = st.nextName();
            st.addEntry(n1, 0, int);
            var n2 = st.nextName();
            st.addEntry(n2, 0, int);

>>>            repMsg = "created " + st.attrib(n1) + " +created " + st.attrib(n1);   <<< The second one should be n2
            fsLogger.debug(getModuleName(),getRoutineName(),getLineNumber(),repMsg);
            return new MsgTuple(repMsg, MsgType.NORMAL);
        }
```

I also noticed some of the indentation in this proc is off in various places so I'm going to fix that too.
