### ISSUE TITLE
categorical_test.py failures on distributed systems

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#904]
https://github.com/Bears-R-Us/arkouda/pull/899 added some tests that write files to `/tmp`, but `/tmp` is usually a filesystem that's local to each machine. For clusters, including the ones we do nightly testing on, this is causing some failures for those tests since the results written by the server aren't visible to the clients.

This is a similar problem to https://github.com/Bears-R-Us/arkouda/issues/437, which was resolved by https://github.com/Bears-R-Us/arkouda/pull/439 by writing the files to the current working directory.

The following patch gets testing working on these systems:

```diff
diff --git a/tests/categorical_test.py b/tests/categorical_test.py
index 65dacb1..01de0f5 100644
--- a/tests/categorical_test.py
+++ b/tests/categorical_test.py
@@ -2,6 +2,7 @@ import numpy as np
 import tempfile
 from context import arkouda as ak
 from base_test import ArkoudaTest
+import os


 class CategoricalTest(ArkoudaTest):
@@ -194,7 +195,7 @@ class CategoricalTest(ArkoudaTest):
         with self.assertRaises(ValueError):  # Expect error for mode not being append or truncate
             cat.save("foo", dataset="bar", mode="not_allowed")

-        with tempfile.TemporaryDirectory() as tmp_dirname:
+        with tempfile.TemporaryDirectory(dir=os.getcwd()) as tmp_dirname:
             dset_name = "categorical_array"  # name of categorical array

             # Test the save functionality & confirm via h5py
@@ -233,7 +234,7 @@ class CategoricalTest(ArkoudaTest):
         pda1 = ak.zeros(5)
         strings1 = ak.random_strings_uniform(9, 10, 5)

-        with tempfile.TemporaryDirectory() as tmp_dirname:
+        with tempfile.TemporaryDirectory(dir=os.getcwd()) as tmp_dirname:
             df = {
                 "cat1": c1,
                 "cat2": c2,
```

But I'm not sure if you want to go with something like that or if you want to mirror what was done in https://github.com/Bears-R-Us/arkouda/pull/439 .

**Comment by ronawho** [comment]
FYI @glitch we do some nightly correctness and performance testing. The performance results are graphed at https://chapel-lang.org/perf/arkouda/, but correctness results aren't visible externally so I just generally report issues as they crop up like this.

**Comment by glitch** [comment]
@ronawho shoot, sorry about that, I'll take a look at #439 along with some of our other tests using temp dirs and get this fixed up.  Thanks for the head's up.

**Comment by ronawho** [comment]
No problem, part of the reason we run nightly testing is to catch issues like this that you'll only see on distributed systems and not local ones like where CI testing runs.

And note that using temp dirs isn't always an issue, it's just when expecting that dir to be mounted on both the client and server that you can run into issues. If there's other tests using temp dirs beyond categorical_test.py I don't think we're seeing any problems with them.

**Comment by ronawho** [comment]
@glitch Sorry, I spoke too soon on this. I only tested #905 with 2 locales, but this is still failing in nighty testing, which uses 16. 

Compiling with `ARKOUDA_DEVELOPER=true` I see the following errors at 5+ nodes:

```
/src/GenSymIO.chpl:1581: error: halt reached - array index out of bounds
note: index was 4 but array bounds are 4..3
```

I suspect this is because `c1` only has 4 elements, so locale 5 is operating on something that's empty. I'm not sure if this is a case where there should be a guard in the code, or the test should just have enough elements to work with the nightly testing. 

In case it's helpful: https://github.com/Bears-R-Us/arkouda/issues/721, https://github.com/Bears-R-Us/arkouda/issues/805, and https://github.com/Bears-R-Us/arkouda/issues/706 are prior instances of tests (especially IO tests) being sensitive to the number of locales used.

**Comment by glitch** [comment]
@ronawho Thanks for the heads up.  If I understand this correctly the issue isn't with Categorical, rather it's a general boundary condition we didn't handle down in GenSymIO::write1DDistArray when the array is smaller than the number of locales.

Some of the past issues band-aided over the problem by upping the number of items in an array for testing purposes, but it looks like [this PR](https://github.com/Bears-R-Us/arkouda/pull/808/files) high-lights an actual fix (test that the locale actually has work/data to process).  Does that sound right?

I'm going to take the same approach of trying to get it to break on our 2 locale CI image (gasnet) and then trying to fix it for `write1DDistArray` in general.

**Comment by ronawho** [comment]
> Some of the past issues band-aided over the problem by upping the number of items in an array for testing purposes, but it looks like this PR highlights an actual fix (test that the locale actually has work/data to process). Does that sound right?

That sounds right to me.

**Comment by ronawho** [comment]
> I'm going to take the same approach of trying to get it to break on our 2 locale CI image (gasnet) and then trying to fix it for write1DDistArray in general.

👍  FYI you can run gasnet oversubscribed locally too. If you want to repro in CI you should be able to bump the number of locales used and to speed things up maybe limit the number of tests run. I think something like:

```diff
diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
index 86b8ff9..8858903 100644
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -95,20 +95,11 @@ jobs:
       run: |
         make
         python3 -m pip install -e .[dev]
-    - name: Arkouda make check
-      run: |
-        make check
     - name: Arkouda unit tests
       env:
         ARKOUDA_PYTEST_OPTIONS: "--durations=0 --durations-min=5.0"
       run: |
-        make test-python
-    - name: Arkouda benchmark --correctness-only
-      run: |
-        ./benchmarks/run_benchmarks.py --correctness-only
-        if [ "${{matrix.image}}" != "chapel-gasnet-smp" ]; then
-          ./benchmarks/run_benchmarks.py --size=100 --gen-graphs
-        fi
+        ARKOUDA_NUMLOCALES=5 python3 -m pytest tests/categorical_test.py
 
   chapel_unit_tests_linux:
     runs-on: ubuntu-latest
```

**Comment by glitch** [comment]
Just an update:  I've been digging into this over the last few days and the general issue is what to do on the lower-end boundary condition when an array (either numeric or string based) has less elements than there are locales.

Reconfiguring to run multiple locales on my workstation I can get the server code to `SIGSEGV` when testing with strings/categorical (occurs on the save operation in GenSymIO::generateStringsMetadata).  I know this is different error than reported but I think it is still indicative of the fundamental problem.

I believe I am going to put up a band-aid fix here and open a new issue for fixing the underlying "What do we do when we have a strings array with fewer elements than locales" problem since it's more involved than I previously thought.

**Comment by ronawho** [comment]
Sounds good. FWIW if you build with `ARKOUDA_DEVELOPER=true` you'll probably see the out-of-bounds error intead of the segfault.
