### ISSUE TITLE
Categorical/Strings array with size smaller than num locales fails read/write to HDF5

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#914]
As identified in issue #904 we have an issue where both Strings & Categoricals appear to fail reading / writing to HDF5 when the size of the array is less than the number of locales.

This can be produced by modifying the unit test `tests/categorical_test.py::CategoricalTest::testSaveAndLoadCategorical` and setting the number of elements to something smaller than the number of locales.

Note: It is probably best to make an explicit unit test to cover this issue.
Reproducible via:
```python
# mkdir -p /tmp/junk
# ./arkouda_server -nl 2 --logLevel=LogLevel.DEBUG --GenSymIO.logLevel=LogLevel.DEBUG

import arkouda as ak
ak.connect("localhost")
c1 = ak.Categorical(ak.array(["abc"]))
c1.save("/tmp/junk/cat", dataset="c1_array")
x = ak.load_all("/tmp/junk/cat")
c2 = x["c1_array"]
```

NOTE: To enable more than one locale for local testing you need to turn on the following environment variables when compiling and running (see also chapel-lang docs for running multi-locale https://chapel-lang.org/docs/usingchapel/multilocale.html#readme-multilocale )
```
export CHPL_COMM=gasnet
export CHPL_COMM_SUBSTRATE=smp
export CHPL_RT_OVERSUBSCRIBED=yes

# It's a good idea to also turn on
export ARKOUDA_DEVELOPER=true
```

**Comment by glitch** [comment]
What's interesting is that I can get the same operation to fail in different places depending on whether or not `ARKOUDA_DEVELOPER` is turned on.  I believe the issue is still the same underlying problem (elements < num_locales), but it fails trying to write out Categorical.codes (AK_DEV=true) and Categorical.categories (AK_DEV=false).  These are separate areas in the code but in general we are trying to roughly the same thing.

**Comment by glitch** [comment]
Based on the current master branch these are the fundamental breaking conditions
```python
import arkouda as ak
ak.connect("localhost")
a1 = ak.array([1, 2])
a1.save("/tmp/junk/a1")
>> src/GenSymIO.chpl:1581: error: halt reached - array index out of bounds
```

```python
import arkouda as ak
ak.connect("localhost")
s1 = ak.array(["abc", "xyz"])
s1.save("/tmp/junk/s1")
>> src/GenSymIO.chpl:1856: error: halt reached - back called on an empty array
```

`Categorical` is just a combination of these depending on which underlying component gets written first.
I added some boundary conditions to get things to write correctly but it causes errors when trying to load because the dataset may not exist in all files.  By updating the `load` and `load_all` functions with `allow_errors` and `strictTypes` flags I can get things to load with only warning messages but the Strings values array was off because of the shuffle.  This was more an issue of my fixes which will need to be reworked.

My plan here is to see if I can write an empty/nil value for a given array when the number of locales exceed the number of elements.

IMPORTANT: This may seem like a useless endeavor because we wouldn't normally expect to run into the case of having less data than locales.  However, Categorical is the exception because it represents a reduction to unique elements where it becomes much more likely to have fewer elements than locales.

**Comment by glitch** [comment]
We talked about this a bit and can to the conclusion that we should probably use the `offsets` array as assignment for "what strings go with which locale" and then use Chapel `aggregators` to pull the bytes (`uint(8)` array) locale to that locale and write it to that locale's file.

While the files _may_ end up slightly lopsided in the case where there are large strings clumping together, we feel that's a reasonable trade-off the the reduction in code complexity.  (If it turns out to be a problem in the future it shouldn't be too hard to shuffle the offset numbers over to a different locale and continue to use the aggregators, i.e. create a write plan / config for a different distribution of strings etc.).

Using aggregators should be pretty performant and we will be able to continue to have "whole strings" contained in a single file versus splitting a string across boundaries.  This should make it pretty much backwards compatible with any other pre-existing code / files.

**Comment by reuster986** [comment]
I completely agree with shifting to offset-based locality :)
