### ISSUE TITLE
Sporadic Unknown symbol error for pytests

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#924]
On 09/16 some of our nightly testing configurations started failing for registration_test.py with an unknown symbol error. Full test failure:

<details>

```
=================================== FAILURES ===================================
_____________________ RegistrationTest.test_in_place_info ______________________

self = <registration_test.RegistrationTest testMethod=test_in_place_info>

    def test_in_place_info(self):
        """
        Tests the class level info method for pdarray, String, and Categorical
        """
        cleanup()
        my_pda = ak.ones(10, ak.int64)
        self.assertFalse(any([sym['registered'] for sym in json.loads(my_pda.info())]),
                        msg='no components of my_pda should be registered before register call')
        my_pda.register('my_pda')
        self.assertTrue(all([sym['registered'] for sym in json.loads(my_pda.info())]),
                        msg='all components of my_pda should be registered after register call')

        my_str = ak.random_strings_uniform(1, 10, UNIQUE, characters='printable')
        self.assertFalse(any([sym['registered'] for sym in json.loads(my_str.info())]),
                        msg='no components of my_str should be registered before register call')
        my_str.register('my_str')
        self.assertTrue(all([sym['registered'] for sym in json.loads(my_str.info())]),
                        msg='all components of my_str should be registered after register call')

>       my_cat = ak.Categorical(ak.array([f"my_cat {i}" for i in range(1, 11)]))

tests/registration_test.py:248:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
arkouda/categorical.py:79: in __init__
    self.codes = g.broadcast(arange(self.categories.size), permute=True)
python-deps/lib/python3.7/site-packages/typeguard/__init__.py:891: in wrapper
    retval = func(*args, **kwargs)
arkouda/groupbyclass.py:970: in broadcast
    repMsg = generic_msg(cmd=cmd,args=args)
arkouda/client.py:546: in generic_msg
    return _send_string_message(cmd=cmd, args=args, recv_binary=recv_binary)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = 'broadcast', recv_binary = False, args = 'id_45 id_48 id_52 True 10'

    def _send_string_message(cmd : str, recv_binary : bool=False,
                             args : str=None) -> Union[str, memoryview]:
        """
        Generates a RequestMessage encapsulating command and requesting
        user information, sends it to the Arkouda server, and returns
        either a string or binary depending upon the message format.

        Parameters
        ----------
        cmd : str
            The name of the command to be executed by the Arkouda server
        recv_binary : bool, defaults to False
            Indicates if the return message will be a string or binary data
        args : str
            A delimited string containing 1..n command arguments

        Returns
        -------
        Union[str,memoryview]
            The response string or binary data sent back from the Arkouda server

        Raises
        ------
        RuntimeError
            Raised if the return message contains the word "Error", indicating
            a server-side error was thrown
        ValueError
            Raised if the return message is malformed JSON or is missing 1..n
            expected fields
        """
        message = RequestMessage(user=username, token=token, cmd=cmd,
                              format=MessageFormat.STRING, args=args)

        logger.debug('sending message {}'.format(message))

        socket.send_string(json.dumps(message.asdict()))

        if recv_binary:
            frame = socket.recv(copy=False)
            view = frame.buffer
            # raise errors sent back from the server
            if bytes(view[0:len(b"Error:")]) == b"Error:":
                raise RuntimeError(frame.bytes.decode())
            return view
        else:
            raw_message = socket.recv_string()
            try:
                return_message = ReplyMessage.fromdict(json.loads(raw_message))

                # raise errors or warnings sent back from the server
                if return_message.msgType == MessageType.ERROR:
>                   raise RuntimeError(return_message.msg)
E                   RuntimeError: UnknownSymbolError Line 225 In MultiTypeSymbolTable.checkTable: Error: lookup: unknown symbol: id_48

arkouda/client.py:349: RuntimeError
----------------------------- Captured stderr call -----------------------------
connected to arkouda server tcp://*:5555
[GroupBy] Line 185 DEBUG: created id_48 int64 10 1 (10) 8 ,created id_49 int64 10 1 (10) 8
```

</details>

@reuster986 started seeing this too in https://github.com/Bears-R-Us/arkouda/pull/922.

The configs testing chapel 1.24.1 are failing, so I don't think this is from any Chapel changes and the Arkouda code didn't change for a few days around when our testing started failing so I don't think it's from changes to Arkouda either. My current guess is that this is related to upgrading to pyzmq version 22.3.0, which came out on the 16th. https://github.com/zeromq/pyzmq/pull/1590 seems like the most suspicious PR. I'm not sure if there's a bug on the pyzmq size, or if this exposed a bug on our end.

It's also not clear to me why this isn't more consistent and easier to reproduce. I can't repro locally and I can't even repro trying to set up my configuration to match the nightly testing.

For now my recommendation is to limit to pyzmq 22.2.1 to see if that cleans up nightly testing, and come back to investigate when we have more time.

**Comment by ronawho** [comment]
Limiting pyzmq to 22.2.1 resolved the errors in our nightly testing so I think that gives us some confidence the new pyzmq version is what exposed this problem. Hoping to look into this more later, but probably won't have time for a while.

**Comment by hokiegeek2** [comment]
@ronawho Wow, well-done sir! That looks like it was tricky to troubleshoot.

**Comment by hokiegeek2** [comment]
@ronawho Ah, interesting! I know that running pytest locally all tests are executed within the same python process:

![image](https://user-images.githubusercontent.com/10785153/153426264-064a1687-812f-4688-9f5e-8ed808f45623.png)

Moreover, pytests are run serially by default, so that's why I've personally have never seen UnknownSymbolError in the context of running pytest on my dev box. Note: the only time I've personally seen UnknownSymbolError is when I stop/start the Arkouda server w/out restarting the Arkouda python client.

Looking at the CI workflow now

**Comment by reuster986** [comment]
@ronawho that explanation resonates with anecdotal user experience, where we tend to see UnknownSymbolErrors when we use the same python interpreter across multiple server sessions.

I like all of your suggestions; number 4 alone would completely eliminate this issue (in theory), but the others would still be valuable for promoting good hygiene between client and server.

**Comment by hokiegeek2** [comment]
looking at CI/CD running right now, and the tests are run sequentially:

![image](https://user-images.githubusercontent.com/10785153/153434774-f3e4f43c-6d71-4f85-bc1b-988c0e5552cf.png)

Again, since the Arkouda instance is class-scoped for each test case (I specifically designed the test framework that way),  I'm not sure how it's possible for there to be crosstalk between two Arkouda server instances within the same pytest run.

**Comment by hokiegeek2** [comment]
I agree with @reuster986 that option 4 from @ronawho is a good idea as this treats the root problem.

**Comment by hokiegeek2** [comment]
@ronawho I am still investigating, but based upon the pytest docs I've read, it does not seem possible for what you're describing to happen within a pytest run since (1) there is one Arkouda server per test class and (2) the Arkouda server assigned to each test class is torn down when all of the test cases have executed.

**Comment by ronawho** [comment]
I'm saying pytest is resulting in something like:

```python
# test 1
start_arkouda_server()
ak.connect(...)
long_lived_ref = ak.array([1, 1]) # id_1
stop_arkouda_sever()

# test 2
start_arkouda_server()
ak.connect(...)
a = ak.array([2, 2]); # id_1
del long_lived_ref # deletes "id_1", this is a reference from a dead server, but the name is still valid
b = a + 1 # tries to use now deleted id_1
```

Obviously there's not explicit deletes, but it's not easy to predict when then gc will run, so it's possible that objects that refer to shutdown servers get gc'd after a new server is started and I think that's what we're seeing.

**Comment by hokiegeek2** [comment]
@ronawho ahhhh...okay, that's right, the Arkouda client is not an object w/ instance-scoped attributes. So it appears that client state spans multiple test classes, and the client has stale object references due to the server startup/shutdown at the setUpClass/tearDownClass sequence of each test case.

**Comment by ronawho** [comment]
My current plan is:
1. Give each server a unique identifier prefix (maybe 8 chars long to give enough randomness without making the ids unreadable.) -- @reuster986 will this mess up any scripts you use to parse the server traces?
2. Call `gc.collect()` before disconnecting from server in `ak.disconnet()` (just to reduce memory overhead on a long-lived server from stale references.) I do not see a strong need to `collect()` when shutting down since the server is going away anyways. I guess it could be beneficial to avoid calling a new server with stale ids (which wouldn't cause any issues in the new world, but would be some time wasted sending messages)
3. Remove all our previous workarounds for this (bump pyzmq version, remove manual register calls in tests, re-add python portability testing)

I still think it would be beneficial to add some client code to track if we ever get duplicate ids (to help issues like this down or bugs on the server side returning ids twice, but I'd like to leave that for somebody else)
