### ISSUE TITLE
Investigate importing hdf5 file created from Pandas/PyTables

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#953]
A community member working through the TaxiCab dataset (https://github.com/Bears-R-Us/ArkoudaNotebooks/blob/master/NYCTaxi.ipynb) had modified the notebook to write the dataframe out to HDF5 via pandas dataframe.
i.e.
```python
df.to_hdf(out_filename, key="data", format="table", mode="w")
```

While Arkouda is capable of reading HDF5 as a format, output like above is not something it can currently handle.   We should investigate what it would take to read in a simple data frame / table exported from Pandas.  If it's a "quick win" this may be a good alternative for folks to import data into Arkouda instead of trying to pass the data over the ZMQ socket.

Note: Under the hood I believe the Pandas implementation uses PyTables to format and write the data into HDF5.
- https://www.pytables.org/
- https://github.com/PyTables/PyTables
- https://portal.hdfgroup.org/display/HDF5/HDF5

**Comment by glitch** [comment]
Long story short I may have found a potential blocker for this issue. Using PyTables to export a Pandas dataframe to HDF5 results in the column names being encoded in a strange fashion.  After some debugging etc. I finally realized it is really a Python pickled list which isn't really a portable format.  Here is an example from the TaxiCab dataset using `h5ls` to dump the file attributes, i.e.   `h5ls -v <file>/data/table`
```
    Attribute: values_block_0_kind scalar
        Type:      153-byte null-terminated ASCII string
        Data:  "(lp0\nVtrip_distance\np1\naVfare_amount\np2\naVextra\np3\naVmta_tax\np4\naVtip_amount\np5\naVimprovement_surcharge\np6\naVtotal_amount\np7\naVcongestion_surcharge\np8\na."
```

Using python to unpickle it:
```python
>>> import pickle
>>> x = b"(lp0\nVtrip_distance\np1\naVfare_amount\np2\naVextra\np3\naVmta_tax\np4\naVtip_amount\np5\naVimprovement_surcharge\np6\naVtotal_amount\np7\naVcongestion_surcharge\np8\na."
>>> pickle.loads(x)
['trip_distance', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge']
```
I still think I can make something work, but it's likely to be fragile since pickling objects in Python is not portable.

**Comment by mhmerrill** [comment]
@Ethan-DeBandi99 does this overlap with the Parquet table thing we recently did?

**Comment by Ethan-DeBandi99** [comment]
@mhmerrill it overlaps somewhat but in the opposite direction. I was testing the we could write to Parquet and then Pandas could read it. I will work on testing the opposite and making sure everything also works for HDF5.

**Comment by Ethan-DeBandi99** [comment]
I have been doing a bit of research on this. I put together a Jupyter Notebook for testing import/export of HDF5 and Parquet files. This is all client side, but was just to give an idea of how this should all work and what we will need to do for import/export.
# HDF5
- Main issue with import is that Pandas pickles column names. We should be ok because we are not using older versions of Python, but should be noted.
- We can use `h5py`, `Pytable`, or `Pandas` to read out and format so Arkouda can Read.

# Parquet
- Export format can be read directly by `Pandas`
- Files generated with pandas can be formatted easily with `pyarrow`
