### ISSUE TITLE
performance drop in substring search methods

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#963]
https://chapel-lang.org/perf/arkouda/16-node-xc/?startdate=2021/10/20&enddate=2021/11/03&configs=release,nightly&graphs=substringsearchperformance

The performance of the substring search benchmark dropped significantly after switching to use `Matcher(pattern).get_match(MatchType).matched()` to calculate `contains`, `startswith`, and `endswith` in PR #958 

The benefit of routing through `Matcher` is this information is cached so subsquent calls to these methods (or any `Match` methods) require no calculation, but this requires a lot of overhead to calculate the locations for every match type when the substring search methods are called before a `Matcher` object has been created

Strategy:
- check if the `Matcher` has already been chached and if so, return the appropriate `matched` pdarray
- if not fall back to more performant `contains`, `startswith`, `endswith`

This way the substring search methods take advantage of the `Matcher` object if it's been created but don't take the performance hit if someone just wants the boolean array

**Comment by ronawho** [comment]
Note that there was a performance hit for most benchmarks on 16-node-cs-hdr on the same night -- https://chapel-lang.org/perf/arkouda/16-node-cs-hdr/?startdate=2021/10/26&enddate=2021/11/10&configs=release&graphs=argsortperformance,coargsortperformance,groupbyperformance,setoperationsperformance,substringsearchperformance,stringargsortperformance,stringcoargsortperformance,stringgroupbyperformance

I don't really see how that PR would have impacted performance of argsort and other operations, but I'll see if I can dig a little more.
