### ISSUE TITLE
Compilation failure on newer versions of HDF5

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#975]
@mhmerrill was getting a compilation failure with HDF5 version 1.12.1 and it looks like the macro compatibility of HDF5 between versions 1.10.x and 1.12.x  has an issue with function H5Oget_info_by_name (versions 1 vs 3, the proxy function now points to 3 which takes more args).

For now we should explicitly call version 1.

**Comment by glitch** [comment]
Linking issue #979 (and #452), it looks like the newer version of HDF5 is causing a runtime failure on the unit tests.  That is likely related to the proxy version of the functions failing in some strange way.  My goal is to try to reproduce with an updated HDF5 version.

**Comment by glitch** [comment]
This doesn't make me feel good :(

```
${HOME}/projects/arkouda//src/c_helpers/help_h5ls.c:16:49: warning: incompatible pointer types passing 'H5O_info2_t *' (aka 'struct H5O_info2_t *') to parameter of type 'H5O_info1_t *' (aka 'struct H5O_info1_t *') [-Wincompatible-pointer-types]
    status = H5Oget_info_by_name1(loc_id, name, info_t_ptr, H5P_DEFAULT);
                                                ^~~~~~~~~~
${HOME}/opt/hdf5-1.12.1/include/H5Opublic.h:2052:81: note: passing argument to parameter 'oinfo' here
H5_DLL herr_t H5Oget_info_by_name1(hid_t loc_id, const char *name, H5O_info1_t *oinfo, hid_t lapl_id);
```

On a build of HDF5 v1.12.1 (using default options) it looks like the proxied type-struct for H5O_info_t was updated to version 2 ... but version 1 doesn't actually exist by name in 1.10.6 so we can't explicitly point to it by name.  I'm not sure if this is the issue that Mike ran into, but it's in the general area of the failure he experienced.

**Comment by ronawho** [comment]
You've probably already found the compatibly doc https://portal.hdfgroup.org/display/HDF5/API+Compatibility+Macros, but I find it to be very confusing. I _think_ a short-term workaround would be to compile Arkouda with `-DH5_USE_110_API` to force the old API, but it's really not clear to me how you're supposed to be compatible with multiple versions of HDF5. I was hoping there would be a simple macro you can check versions against and choose which version you use, but I don't see that.

**Comment by glitch** [comment]
@ronawho Yeah, I've read through that doc before, thanks :)
I just rebuilt HDF5 1.12.1 with `--with-default-api-version=v110` and now I can get the tests to run without hanging (they still all fail).  I think your suggestion with the application compilation option might work with a few changes to the code. 👍

**Comment by glitch** [comment]
Just a follow up and cross-posting from issue #979 I was able to get this working locally and @ronawho was also able to test locally against HDF5 1.12.1 with passing tests.
