### ISSUE TITLE
`make test` hangs during categorical test on my iMac

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#979]
`make test` hangs during categorical test on my iMac
This happened after a `brew upgrade` to get the newest version of chapel but I think I also got newer versions of HDF5 and ZMQ potentially.
I will check it out later today and provide version number and config  info here.

**Comment by glitch** [comment]
This _may_ be related to Issue https://github.com/Bears-R-Us/arkouda/issues/924 and PR https://github.com/Bears-R-Us/arkouda/pull/925

Can you post the version of ZMQ that's being used?

**Comment by mhmerrill** [comment]
the server is linking against these libraries:
Found ZMQ version: 4.3.4
Found HDF5 version: 1.12.1

**Comment by glitch** [comment]
I should note I'm using `pyzmq -> 20.0.0` which in turn is using `zmq 4.3.3` and my HDF5 version is `1.10.6` via `h5py-> v2.10.0`
I believe @pierce314159 is using zmq 4.3.4, so I don't think that is the issue.

**Comment by mhmerrill** [comment]
> I should note I'm using `pyzmq -> 20.0.0` which in turn is using `zmq 4.3.3` and my HDF5 version is `1.10.6` via `h5py-> v2.10.0`
> I believe @pierce314159 is using zmq 4.3.4, so I don't think that is the issue.

@glitch i think it's the HDF5

**Comment by mhmerrill** [comment]
`2021-11-30:14:06:27 [arkouda_server] main Line 266 INFO [Chapel] >>> "lshdf" "[\"/Users/mike/chapel/arkouda/arkouda/categorical_test/tmp5zt4ii39/cat-save-test_LOCALE0000\"]"
Abort trap: 6`

**Comment by glitch** [comment]
Linking issue #975 , I think I have a working fix for this.  Sent @mhmerrill a patch to test on his machine.  If it looks good I'll post a PR for it.  Essentially it adds an arkouda/chapel ccflag to force HDF5 API 110 over 112 as @ronawho mentioned in #975 and reverts the change of `help_h5ls.c` to use the proxy function & struct versions again versus the explicit versions.

**Comment by ronawho** [comment]
Just as a point of reference https://github.com/glitch/arkouda/commit/83ecf6ef931717f82a0d0790202549792d798839 works for me. Without that I was seeing warnings during the build and the same hangs Mike was(I'm on my mac with HDF5 Version 1.12.1)
