### ISSUE TITLE
Allow externally-generated server tokens

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#980]
When arkouda_server is started with authenticate=true, Chapel generates a token (server-side) that the user has to manually retrieve to login. This does not work well in situations where the user lacks access to the node Arkouda is launched from.

Allowing an externally-generated token to be passed into arkouda_server as a CLI or env variable will enable users to designate a token, obviating the need for a user to login to the host node to retrieve the complete connect string including token.

**Comment by mhmerrill** [comment]
@hokiegeek2 is this done or still in process or superseded?

**Comment by hokiegeek2** [comment]
hey @mhmerrill! I have not worked on it yet but will rock it out tomorrow or Friday and get a PR in

**Comment by hokiegeek2** [comment]
Have the logic implemented and tested: 

![image](https://user-images.githubusercontent.com/10785153/149322531-3422bb9d-af65-457a-b09e-205fcc290f04.png)

![image](https://user-images.githubusercontent.com/10785153/149322890-d33bb5b1-3a59-422a-91e1-5e9df73654fa.png)
