### ISSUE TITLE
Modularization of the Arkouda build process 

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#994]
This is the backing issue for #978; see that PR for the code.

### Summary
The approach taken in this prototype was adding a map that maps from command strings to first class functions and removed the majority of commands from the main select cmd statement so that they would not be required with every Arkouda build. A ServerModules.cfg configuration file was added that takes the name of modules to include in the build, one per line, and generates import statements for those modules and adds their messaging functions to the command map only when in the configuration file to avoid compiling files that are not desired in a given Arkouda build.

### Proposed remaining work
1. A user should be able to specify Chapel modules from any location to be optionally built into the server
    - The current branch only works with modules in Arkouda's src/ directory
2. Clear "backbone modules should be decided upon
    - The initial brainstorm landed us at 4 core functions that should be included with every build: (1) the modules required to run the server (2) indexing into pdarrays (3) generating random pdarrays (4) doing basic arithmetic on pdarrays
3. A user should be able to easily add their client-side code to call their added modules
    - A good story/documentation around this may be enough, more discussion should be had

### Adding client-side code today
Running a script like the one below will add a function to enable it to be called with `ak.test_command()` for example. It is still up for discussion whether or not this is acceptable as "good enough" for allowing a user to add their client-side code, but if it is, clear documentation and examples will likely need to be created and inserted into the Arkouda repo.
```
import arkouda as ak
from arkouda.client import generic_msg

def test_command():
    rep_msg = generic_msg(cmd='test-command')

ak.__dict__["test_command"] = test_command
```
Another limitation with this script is it only allows you to add functions with `ak.myFunc()` and does not allow you to do `pdarray.myFunc()`, like you would do with a call to `pdarray.save("hdf-file")`, for example, so that would need to be fleshed out as well

Edit: just a reminder to self that we also want to move the code from `CommandMap.chpl` module into `ServerConfig.chpl`, since that module represents what is available globally in Arkouda

**Comment by bradcray** [comment]
1) Sounds good (and important!) to me, though I don't have good ideas about how to specify where they should come from.  Did you and Mike?  Spitballing: We could switch from having the configuration file list module names to having it just list file names which would be precise, but somehow feels more clunky/low-level to me (but maybe I'm just being too pure).  It also may be slightly more long-winded to list fully-pathed filenames if a bunch of modules are in a single similar directory where a `-M` style option on the Chapel command line would serve the same purpose.  But on the other hand, having the configuration file go from simple text to some sort of formatted text like yaml/toml/etc. to specify "look for these modules in these directories" also feels like over-engineering.  So curious what thoughts you both had.

2) I'm happy to defer to Mike on what the backbone should be.  The slight pause I have with 2-4 is "pdarrays of what type(s)?"  E.g., I think it would be attractive to get to the point where we could say "give me 1D pdarrays of bools and ints, but don't bother giving me 1D pdarrays of strings, reals, complexes, or uints, and no multidimensional arrays."  If we had that, I tend to think of items 2 and 4 as coming automatically with the inclusion of a pdarray type (part of its basic capabilities), and this is partially why I suggested we start looking into a "2d array of ints" module to see how well or poorly we could selectively compile in a given array type and its core operations.  I'm imagining we have a `CoreOps` module that defines all of these operations in a generic way, and then a module per pdarray type that would instantiate CoreOps for that type.  I haven't looked at this code recently enough to know how realistic/practical this is or not.

It wouldn't occur to me to include random array generation as part of the core functionality of a pdarray like indexing and arithmetic, but I wouldn't oppose it either.

3) I agree with this.

(I also agreed with Mike's comment on the PR itself that it'll be interesting to continue to explore how integrating mason more into Arkouda would look and how it would work... but not in this initial PR, more as an ongoing effort).

**Comment by bmcdonald3** [comment]
Thinking of the backbone modules discussed, here are some numbers I collected on how each of the modules proposed affect the build time:

Modules | Build time
-- | --
Main branch today | 223.3 s
Bare (no optional) | 46.9 s
Only Rand | 47.4 s
Only Indexing | 53.9 s
Only Operators | 75.1 s
Rand/Indexing only | 56.6 s
Rand/Indexing/Operators | 86.7 s



I believe that a significant chunk of the bare ~47 second build time comes from the `GenSymIO` module (which is included with the "bare" build I have measured since it has essential server functions in it today), so that number would likely be much smaller if we refactor that module in the IO rework effort, but I can't yet collect numbers on that with how things are setup today.

With these build times in mind, how comfortable are people with including the array operations as a "backbone" module? Also, any additional thoughts on what is essential Arkouda build would be appreciated for determining the backbone modules.

**Comment by bradcray** [comment]
> how comfortable are people with including the array operations as a "backbone" module?

I'm probably not the person you were most hoping to hear from, but when you say "array operations" do you mean including all of indexing, operators, and random?  (basically the last line of this table, which presumably is still leaving out a bunch of stuff from the main branch given the big difference in timings?).

When I think of wanting to use arrays, I think of indexing as "coming with the arrays" and probably operators as well (depending on the operators), so those seem like no-brainers to me.  Rand seems less obviously to be a batteries included type of feature to me, though I think I remember someone else saying that they'd like it (maybe?).

When I think of optional modules and arrays, my thinking goes more toward wanting to opt into or out of arrays of particular element types of ranks rather than of operations that seem core to arrays.  E.g., if I could cut the compile times by 20% by not compiling in arrays of reals or strings or bools in cases where I didn't want to use them, I'd probably opt to do that.

But again, my opinion isn't as valuable here as that of actual Arkouda users...

**Comment by bmcdonald3** [comment]
> when you say "array operations" do you mean including all of indexing, operators, and random?

By "array operations", I actually meant only the "array operators" (edited comment to reflect that) and my reasoning for targeting only operators was that was the largest build time increase (~20 seconds/80).

Thinking about this again after having come back from break (and also reading your comment), I think it makes sense to include the operators as part of the initial backbone.

> wanting to opt into or out of arrays of particular element types of ranks rather than of operations that seem core to arrays

This makes sense, but my understanding was that we were putting off the ability to opt in/out of particular array types/ranks for this initial PR and would take that on as a potential next step. 

For this modularization effort, I have been focusing on the modules and Arkouda server functions specifically as those seemed like the low-hanging fruit for the initial work (and, selfishly, it also makes developing in Arkouda much more enjoyable with the reduced compilation times...). Do you agree with this initial direction for the effort or would you like to see the focus more heavily on types/ranks for this initial work?

**Comment by bradcray** [comment]
> and would take that on as a potential next step.
> ...
> Do you agree with this initial direction for the effort or would you like to see the focus more heavily on types/ranks for this initial work?

I completely buy that approach—just noting where I think of the most obvious lines around array opt-in/opt-out features as being, ultimately.

**Comment by glitch** [comment]
One thing we wanted to mention so it doesn't get lost is the desire for 2 things
1. Faster development build times where developers can turn things on/off to speed up compile times.
2. The ability for external folks to compile in their own modules without having to put their code in our project space.  i.e. Eventually have an option to point to an arbitrary directory outside of the project and outside of arkouda source control so folks can include their own private modules.

I believe Chapel folks found an issue (https://github.com/chapel-lang/chapel/pull/18912) which currently prevents  number 2, but we're fine to wait.

Optionally as an interim solution we could add a directory under `src/` and add it to the `.gitignore` file so anything under it is excluded.
